import { getFirestoreDb } from '@/lib/firebase/server'

// Per-stage record of which model produced what during generation. Stages
// not run (e.g. no repair was needed, or fact source did not call an LLM)
// are simply omitted. Stored on AIQuestion so we can attribute quality
// regressions to a model swap and run before/after analyses.
export interface QuestionGenerationModels {
  facts?: string
  question?: string
  repair?: string
  review?: string
}

export interface AIQuestion {
  id: string
  question: string
  correctAnswer: string
  explanation?: string
  category: string
  difficulty: 'easy' | 'medium' | 'hard'
  type: 'free-text'
  // New fields for infinite mode.
  // 'legacy' = generated by the pre-Anthropic pipeline (gpt-4o); kept in
  // the collection for audit/analytics but excluded from sampling and
  // warm-pool counting. 'removed' is reserved for admin-flagged-bad
  // questions; do not conflate the two.
  status: 'active' | 'flagged' | 'removed' | 'legacy'
  timesShown: number
  timesCorrect: number
  avgTimeMs: number | null
  // Rating counters. Maintained transactionally by the rate route
  // alongside the per-user rating doc at aiQuestions/{id}/ratings/{uid}.
  // Source of truth is still the subcollection (one doc per voter); these
  // are denormalized for cheap reads at display time. Backfill script
  // exists in case they ever drift.
  likeCount: number
  dislikeCount: number
  // Provenance for generated questions. `appVersion` is the commit hash
  // that produced the question (proxy for prompt version); `models` records
  // which LLM ran each stage. Optional for backwards compatibility with
  // pre-existing docs that pre-date this tracking.
  appVersion?: string
  models?: QuestionGenerationModels
}

export interface SeenQuestion {
  at: FirebaseFirestore.Timestamp
  correct: boolean
}

export async function saveAIQuestion(
  question: Omit<AIQuestion, 'status' | 'timesShown' | 'timesCorrect' | 'avgTimeMs' | 'likeCount' | 'dislikeCount'>
): Promise<string> {
  const db = getFirestoreDb()
  const doc: AIQuestion = {
    ...question,
    status: 'active',
    timesShown: 0,
    timesCorrect: 0,
    avgTimeMs: null,
    likeCount: 0,
    dislikeCount: 0,
  }
  const ref = db.collection('aiQuestions').doc(question.id)
  // Firestore rejects `undefined` values; strip optional provenance fields
  // when callers omit them so older code paths keep working.
  const cleaned: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(doc)) {
    if (v !== undefined) cleaned[k] = v
  }
  await ref.set(cleaned)
  return ref.id
}
