import { FieldValue } from 'firebase-admin/firestore'

import { getFirestoreDb } from '@/lib/firebase/server'

// Per-stage record of which model produced what during generation. Stages
// not run (e.g. no repair was needed, or fact source did not call an LLM)
// are simply omitted. Stored on AIQuestion so we can attribute quality
// regressions to a model swap and run before/after analyses.
export interface QuestionGenerationModels {
  facts?: string
  factPicker?: string
  question?: string
  repair?: string
  review?: string
  easySpecialistCheck?: string
}

export interface AIQuestion {
  id: string
  question: string
  correctAnswer: string
  explanation?: string
  category: string
  difficulty: 'easy' | 'medium' | 'hard'
  type: 'free-text'
  // New fields for infinite mode.
  // 'legacy' = generated by the pre-Anthropic pipeline (gpt-4o); kept in
  // the collection for audit/analytics but excluded from sampling and
  // warm-pool counting. 'removed' is reserved for admin-flagged-bad
  // questions; do not conflate the two.
  status: 'active' | 'flagged' | 'removed' | 'legacy'
  timesShown: number
  timesCorrect: number
  avgTimeMs: number | null
  // Rating counters. Maintained transactionally by the rate route
  // alongside the per-user rating doc at aiQuestions/{id}/ratings/{uid}.
  // Source of truth is still the subcollection (one doc per voter); these
  // are denormalized for cheap reads at display time. Backfill script
  // exists in case they ever drift.
  likeCount: number
  dislikeCount: number
  // Provenance for generated questions. `appVersion` is the commit hash
  // that produced the question (proxy for prompt version); `models` records
  // which LLM ran each stage; `sourceUrl` is the grounding citation from
  // the FactSource (set when the source is grounded — Perplexity, future
  // Wikipedia/Wikidata — and absent for parametric LLM facts); `seed` is
  // the "seedWord :: modifier" string fed to the FactSource, persisted so
  // we can diagnose duplicate-answer clusters and (later) dedupe by seed.
  // Optional for backwards compatibility with pre-existing docs.
  appVersion?: string
  models?: QuestionGenerationModels
  sourceUrl?: string
  seed?: string
  // Uniform [0,1) value assigned at write time so the sampler can pick a
  // random window via `orderBy('random').startAt(r).limit(N)` instead of
  // scanning the full pool on every /next.
  random: number
  // uid of the player whose /next call triggered this question's
  // generation (either pool-exhausted on-demand or background warm).
  // Required on all docs written after this field was introduced; older
  // docs are missing it and are therefore excluded from the "questions
  // generated by me" view. Anonymous Firebase uids are stored too, but
  // the mine-view server rejects requests from anonymous callers, so
  // anonymous-attributed docs are effectively unreachable from the UI.
  createdBy?: string
  // Server-side wall-clock at write time. Drives the library's
  // newest/oldest sorts. Optional on the type because pre-existing docs
  // never had it; the questions API tolerates the missing case.
  createdAt?: FirebaseFirestore.Timestamp
}

export interface SeenQuestion {
  at: FirebaseFirestore.Timestamp
  correct: boolean
}

// Backstop against the convergence pattern: different seeds returning
// the same Perplexity listicle and producing many active questions
// whose correctAnswer was the same name (e.g. "Mona Lisa" landing as
// the answer for seeds across Art and General Knowledge). Returns the
// id of any active question whose correctAnswer matches verbatim, so
// the generator can re-roll instead of saving yet another copy.
//
// Single-field equality query → no composite index needed; we filter
// by status in code. The same correctAnswer rarely shows up on more
// than a handful of docs, so capping at 5 is plenty.
//
// Case-sensitive on purpose: the upstream LLM is consistent about
// proper-noun casing, and lower-casing would require a parallel field.
// If we start seeing case drift in practice we can layer normalization
// then.
export async function findActiveDuplicateAnswer(
  correctAnswer: string
): Promise<string | null> {
  const trimmed = correctAnswer.trim()
  if (!trimmed) return null
  const db = getFirestoreDb()
  const snap = await db
    .collection('aiQuestions')
    .where('correctAnswer', '==', trimmed)
    .limit(5)
    .get()
  for (const doc of snap.docs) {
    const status = (doc.data() as { status?: string }).status
    if (status === 'active') return doc.id
  }
  return null
}

export async function saveAIQuestion(
  question: Omit<
    AIQuestion,
    'status' | 'timesShown' | 'timesCorrect' | 'avgTimeMs' | 'likeCount' | 'dislikeCount' | 'random' | 'createdAt'
  > & { createdBy: string }
): Promise<AIQuestion> {
  const db = getFirestoreDb()
  const doc: AIQuestion = {
    ...question,
    status: 'active',
    timesShown: 0,
    timesCorrect: 0,
    avgTimeMs: null,
    likeCount: 0,
    dislikeCount: 0,
    random: Math.random(),
  }
  const ref = db.collection('aiQuestions').doc(question.id)
  // Firestore rejects `undefined` values; strip optional provenance fields
  // when callers omit them so older code paths keep working.
  const cleaned: Record<string, unknown> = {}
  for (const [k, v] of Object.entries(doc)) {
    if (v !== undefined) cleaned[k] = v
  }
  cleaned.createdAt = FieldValue.serverTimestamp()
  await ref.set(cleaned)
  return doc
}
