import { getOpenTDBCategoryName } from '@/app/trivia/data/seeds/categoryNames'
import { getFirestoreDb } from '@/lib/firebase/server'
import type { AIQuestion } from '@/lib/trivia/aiQuestions'
import { CATEGORY_META } from '@/lib/trivia/categories'
import {
  CURRENT_MIGRATION_VERSION,
  type UnansweredPoolEntry,
  canonicalCategoryKey,
  ensureMigratedTriviaState,
  readTriviaState,
  writeUnansweredPool,
} from '@/lib/trivia/triviaState'

export interface SamplerOptions {
  uid: string
  streak: number
  type?: 'free-text' // v1 only free-text
  // List of category ids to draw from. Empty/undefined = all categories.
  // Single-element arrays behave the same as the old single-category mode.
  categoryIds?: number[]
}

// Number of candidates to fetch around a random cursor on the all-
// category / multi-category rebuild path. Power users with large seen
// sets (e.g. seenCount > activeCount after flagging churn) exhaust a
// small window almost entirely — a 100-doc window can easily land
// fully inside the seen set even when a handful of unseen exist in the
// global pool. We pay 500 reads once per rebuild and the result lands
// in the per-player pool cache, so subsequent /next calls don't repeat
// the cost. Matches POOL_CACHE_SIZE so we cap reads at exactly what we
// can fit in the cache.
const CANDIDATE_WINDOW = 500

// Single-category runs use a larger one-shot fetch instead of the random
// window. For categories with <= this many active docs the fetch is
// exhaustive — every unseen question is visible to the filter, so the
// sampler returns null iff the player has genuinely seen everything in
// the category. For larger categories we still get a 6x bigger random
// sample than the windowed path, dramatically lowering the null rate
// at high seen-ratios. ~300 reads per /next is still cheap.
const SINGLE_CATEGORY_FETCH = 300

// Cap on the cached unanswered pool stored on the per-player state doc.
// At ~80 bytes per entry the cap keeps the cache around ~40 KB, well
// under the 1 MiB doc limit even alongside the full seen-id set.
const POOL_CACHE_SIZE = 500

// Periodic-refresh cadence. Every Nth /next we rebuild the cache from
// Firestore even if it still has entries, so freshly-warmed questions
// (generated by other players' sessions since the last rebuild) show
// up without the player needing to drain their cache first.
const POOL_REFRESH_EVERY_N = 10

/**
 * Difficulty mix for the sampler. Fixed 4:2:1 (easy:medium:hard) —
 * roughly 57% / 29% / 14% — regardless of streak. Earlier versions
 * ramped toward hard as streak grew (up to 70% hard at streak 20+),
 * but observation showed easy questions weren't surfacing nearly
 * often enough; players want easy to dominate even when streaking.
 *
 * The streak param is preserved on the function signature so callers
 * don't have to change; if we ever want streak progression back, this
 * is the only place it needs to land. Freshness bias
 * (1/(1+timesShown)) still surfaces under-seen questions within each
 * difficulty bucket, so the pool doesn't stagnate on the 4-easy
 * majority.
 */
function getDifficultyWeights(_streak: number): [number, number, number] {
  return [4, 2, 1]
}

// Weighted random selection over an array of items with numeric weights
function weightedRandom<T>(items: T[], weights: number[]): T {
  const total = weights.reduce((a, b) => a + b, 0)
  let rand = Math.random() * total
  for (let i = 0; i < items.length; i++) {
    rand -= weights[i]
    if (rand <= 0) return items[i]
  }
  return items[items.length - 1]
}

// Compute per-question weight within a difficulty bucket.
// Lower timesShown → higher weight (freshness bias).
function freshnessWeight(timesShown: number): number {
  return 1 / (1 + timesShown)
}

// Build the base candidate query (status + type + optional category filter).
// Returned as a Query so callers can layer ordering/cursors on top.
function buildCandidateQuery(
  db: FirebaseFirestore.Firestore,
  type: 'free-text',
  categoryIds: number[] | undefined,
): FirebaseFirestore.Query {
  // `status == 'active'` is the flag filter: when any user flags a
  // question, the flag route flips status to 'flagged' atomically with
  // creating the flag doc (see api/v1/trivia/questions/[id]/flag/route).
  // So this single equality filter excludes everything in any question's
  // /flags subcollection without a separate read per candidate.
  let query: FirebaseFirestore.Query = db
    .collection('aiQuestions')
    .where('status', '==', 'active')
    .where('type', '==', type)

  // Resolve the optional category filter to category-name strings.
  // Questions are stored with the OpenTDB-prefixed name (e.g.
  // "Entertainment: Film", not "Film") — see the note in
  // categories.ts about the two naming conventions. CATEGORY_META is
  // for UI display; getOpenTDBCategoryName is the storage format.
  // Firestore `in` clause caps at 30 values, comfortably more than our
  // 24 categories.
  if (categoryIds && categoryIds.length > 0) {
    const names = categoryIds
      .filter((id) => CATEGORY_META[id] !== undefined)
      .map((id) => getOpenTDBCategoryName(id))
    if (names.length === 1) {
      query = query.where('category', '==', names[0])
    } else if (names.length > 1) {
      query = query.where('category', 'in', names)
    }
  }
  return query
}

// Single-category one-shot fetch. Pulls up to SINGLE_CATEGORY_FETCH docs
// ordered by `random` (which doubles as a stable shuffle). For
// categories at or below the limit this returns every active question
// in the category; for larger categories it still returns a random
// sample 6x the windowed path, lowering the chance that a high
// seen-ratio leaves zero unseen in the sample.
async function fetchSingleCategoryCandidates(
  query: FirebaseFirestore.Query,
  limit: number,
): Promise<AIQuestion[]> {
  const snap = await query.orderBy('random').limit(limit).get()
  return snap.docs.map((d) => ({ id: d.id, ...(d.data() as Omit<AIQuestion, 'id'>) }))
}

// Fetch up to LIMIT candidates near a random cursor, wrapping around to
// the start of the random ordering if the forward window comes back short
// (happens when r is close to 1 or the pool is small). De-dupes by id.
async function fetchCandidateWindow(
  query: FirebaseFirestore.Query,
  limit: number,
): Promise<AIQuestion[]> {
  const r = Math.random()
  const fwd = await query.orderBy('random').startAt(r).limit(limit).get()

  const seen = new Set<string>()
  const out: AIQuestion[] = []
  for (const d of fwd.docs) {
    if (seen.has(d.id)) continue
    seen.add(d.id)
    out.push({ id: d.id, ...(d.data() as Omit<AIQuestion, 'id'>) })
  }

  if (out.length < limit) {
    const more = await query.orderBy('random').limit(limit - out.length).get()
    for (const d of more.docs) {
      if (seen.has(d.id)) continue
      seen.add(d.id)
      out.push({ id: d.id, ...(d.data() as Omit<AIQuestion, 'id'>) })
    }
  }

  return out
}

function toPoolEntry(q: AIQuestion): UnansweredPoolEntry {
  return {
    id: q.id,
    category: q.category,
    difficulty: q.difficulty,
    random: q.random,
    timesShown: q.timesShown,
  }
}

// Refresh the cached unanswered pool from Firestore for the given
// category context. Runs the same windowed/single-category scan the
// sampler used pre-cache, filters out anything in the seen set, and
// caps at POOL_CACHE_SIZE. The returned entries are the fresh cache;
// the caller writes them back to the state doc alongside the popped
// selection.
async function rebuildUnansweredPool(
  db: FirebaseFirestore.Firestore,
  seenSet: Set<string>,
  type: 'free-text',
  categoryIds: number[] | undefined,
): Promise<UnansweredPoolEntry[]> {
  const query = buildCandidateQuery(db, type, categoryIds)
  const fetched = categoryIds && categoryIds.length === 1
    ? await fetchSingleCategoryCandidates(query, SINGLE_CATEGORY_FETCH)
    : await fetchCandidateWindow(query, CANDIDATE_WINDOW)
  const unseen = fetched
    .filter((q) => !seenSet.has(q.id))
    .slice(0, POOL_CACHE_SIZE)
  return unseen.map(toPoolEntry)
}

// Pick a single unanswered entry from the cached pool using the same
// difficulty-bucketed, freshness-biased weighting the pre-cache
// sampler used. Returns null when no bucket has candidates (which is
// indistinguishable, for the caller, from a genuinely-exhausted pool).
function pickFromPool(
  pool: UnansweredPoolEntry[],
  streak: number,
): UnansweredPoolEntry | null {
  if (pool.length === 0) return null

  const byDifficulty: Record<'easy' | 'medium' | 'hard', UnansweredPoolEntry[]> = {
    easy: [],
    medium: [],
    hard: [],
  }
  for (const q of pool) {
    byDifficulty[q.difficulty].push(q)
  }

  const [easyW, mediumW, hardW] = getDifficultyWeights(streak)
  const availableDifficulties: Array<{ key: 'easy' | 'medium' | 'hard'; weight: number }> = []
  if (byDifficulty.easy.length > 0)   availableDifficulties.push({ key: 'easy',   weight: easyW })
  if (byDifficulty.medium.length > 0) availableDifficulties.push({ key: 'medium', weight: mediumW })
  if (byDifficulty.hard.length > 0)   availableDifficulties.push({ key: 'hard',   weight: hardW })

  if (availableDifficulties.length === 0) return null

  const chosenDifficulty = weightedRandom(
    availableDifficulties.map((d) => d.key),
    availableDifficulties.map((d) => d.weight)
  )
  const bucket = byDifficulty[chosenDifficulty]
  const bucketWeights = bucket.map((q) => freshnessWeight(q.timesShown))
  return weightedRandom(bucket, bucketWeights)
}

export async function sampleNextQuestion(options: SamplerOptions): Promise<AIQuestion | null> {
  const { uid, streak, type = 'free-text', categoryIds } = options
  const normalizedCategoryIds = categoryIds ?? []
  const db = getFirestoreDb()

  // 1. Load the per-user state doc. Lazily (re-)migrate users whose
  //    state predates the current migration version — pays a one-time
  //    full subcollection scan per migration bump, then every subsequent
  //    /next is a single doc read.
  let state = await readTriviaState(uid)
  if (state === null || state.migrationVersion < CURRENT_MIGRATION_VERSION) {
    state = await ensureMigratedTriviaState(uid)
  }
  const seenSet = new Set(state.recentSeen)

  // 2. Decide whether to use the cached unanswered pool or rebuild it.
  //    Rebuild when:
  //      - no cache exists yet (new user / post-migration),
  //      - the cache was built for a different categoryIds context,
  //      - the cache went empty after sanity-filtering against the
  //        latest seen set,
  //      - the periodic refresh tick has come around.
  //    Otherwise pop from the existing cache for an aiQuestions-read-
  //    free sample.
  const requestedKey = canonicalCategoryKey(normalizedCategoryIds)
  const nextTick = (state.poolTick ?? 0) + 1
  const cachedKey = canonicalCategoryKey(state.unansweredPoolMeta?.categoryIds)
  const periodicRebuild = nextTick % POOL_REFRESH_EVERY_N === 0
  const cacheMatches = state.unansweredPool !== undefined && cachedKey === requestedKey

  let pool: UnansweredPoolEntry[]
  if (!cacheMatches || periodicRebuild) {
    pool = await rebuildUnansweredPool(db, seenSet, type, normalizedCategoryIds)
  } else {
    pool = (state.unansweredPool ?? []).filter((entry) => !seenSet.has(entry.id))
    if (pool.length === 0) {
      pool = await rebuildUnansweredPool(db, seenSet, type, normalizedCategoryIds)
    }
  }

  // 3. Sample one entry, then persist the pool minus that entry plus
  //    the incremented tick. A null pick after a rebuild means the
  //    player has genuinely exhausted what's currently in the bank for
  //    this filter — propagate the null and let the route fall through
  //    to on-demand generation.
  const selectedEntry = pickFromPool(pool, streak)
  if (selectedEntry === null) {
    await writeUnansweredPool(uid, pool, normalizedCategoryIds, nextTick)
    return null
  }

  const remaining = pool.filter((entry) => entry.id !== selectedEntry.id)
  await writeUnansweredPool(uid, remaining, normalizedCategoryIds, nextTick)

  // 4. Cache holds only the bookkeeping fields the sampler needs.
  //    Fetch the full doc once we know which id we're returning so the
  //    /next route can ship the question text, explanation, etc.
  const doc = await db.collection('aiQuestions').doc(selectedEntry.id).get()
  if (!doc.exists) {
    // Doc was deleted between cache build and sample. Drop through to
    // null; the route will generate on demand.
    return null
  }
  return { id: doc.id, ...(doc.data() as Omit<AIQuestion, 'id'>) }
}
