// FactSource is the abstraction the question generator uses to obtain
// candidate facts about a topic. Today the only implementation is
// LLMFactSource (parametric knowledge); tomorrow we plan to add
// WikipediaFactSource and possibly others (Wikidata, Perplexity).
//
// The interface intentionally hides whether the source is grounded
// against an external corpus or generated by an LLM. Question
// construction shouldn't care — it just receives Facts and builds
// trivia from them.

export type Difficulty = 'easy' | 'medium' | 'hard'

export interface Fact {
  // A verifiable claim written as a complete sentence.
  // The keyDetail must appear verbatim (or as a clear synonym) in
  // the claim — that's what makes the fact "answerable" by a question.
  // Example: "The Legend of Zelda was first released in Japan on
  // February 21, 1986."
  claim: string

  // The single concrete detail in the claim that will become the
  // trivia answer. Must be a name, date, number, place, or short
  // phrase — typically 1-3 words.
  // Example: "1986"
  keyDetail: string

  // Optional citation. Null for ungrounded LLM-generated facts; a
  // URL or stable id (e.g. "wikipedia:Pulp_Fiction#1923") for
  // grounded sources. Stored on the saved question so flagged
  // questions can be traced back to their source.
  source: string | null
}

export interface FetchFactsOptions {
  // Internal numeric category id (matches CATEGORY_META keys).
  // Sources may use this to scope their queries (e.g. Wikipedia
  // category trees) without doing their own string matching.
  categoryId: number

  // Human-readable category name, e.g. "Music". Sources that don't
  // need a numeric id can use this directly in prompts.
  category: string

  // Optional inspirational seed phrase. LLM-style sources use this
  // to nudge the topic toward a specific angle (e.g. "boss fight ::
  // cut content"). Grounded sources may ignore it.
  seed?: string

  // The intended difficulty of questions that will be built from
  // these facts. Affects how niche / surprising the surfaced facts
  // should be.
  difficulty: Difficulty

  // How many facts to return. The generator picks one to build a
  // question from; the rest can be cached for later reuse.
  count: number
}

export interface FactSource {
  // Returns up to `count` facts about the requested topic. May
  // return fewer if the source can't produce enough good ones.
  // Throws on hard failure (network, auth) — soft failures (no
  // facts found) should resolve to an empty array.
  fetchFacts(options: FetchFactsOptions): Promise<Fact[]>

  // Identifier used in logs and saved citations to track which
  // implementation produced a fact. e.g. "llm:claude-sonnet-4-6",
  // "wikipedia", "perplexity:sonar-medium-online".
  readonly id: string

  // Optional: the underlying model id, when the source is LLM-backed.
  // Recorded on saved questions so we can attribute fact-quality
  // regressions to a model swap. Grounded sources can omit this.
  readonly model?: string
}
