import { Achievement } from '@/app/tap-tap-adventure/models/achievement'

export const ACHIEVEMENTS: Achievement[] = [
  // Travel
  {
    id: 'travel_first_steps',
    name: 'First Steps',
    description: 'Travel a distance of 10',
    category: 'travel',
    requirement: 10,
    icon: '👣',
    reward: { gold: 5 },
  },
  {
    id: 'travel_wanderer',
    name: 'Wanderer',
    description: 'Travel a distance of 100',
    category: 'travel',
    requirement: 100,
    icon: '🥾',
    reward: { gold: 15 },
  },
  {
    id: 'travel_explorer',
    name: 'Explorer',
    description: 'Travel a distance of 500',
    category: 'travel',
    requirement: 500,
    icon: '🧭',
    reward: { gold: 50, reputation: 5 },
  },
  {
    id: 'travel_nomad',
    name: 'Nomad',
    description: 'Travel a distance of 1000',
    category: 'travel',
    requirement: 1000,
    icon: '🏕️',
    reward: { gold: 100, reputation: 10 },
  },
  {
    id: 'travel_legend',
    name: 'Legend of the Road',
    description: 'Travel a distance of 5000',
    category: 'travel',
    requirement: 5000,
    icon: '🌍',
    reward: { gold: 500, reputation: 25 },
  },

  // Combat
  {
    id: 'combat_first_blood',
    name: 'First Blood',
    description: 'Win your first combat',
    category: 'combat',
    requirement: 1,
    icon: '⚔️',
    reward: { gold: 10 },
  },
  {
    id: 'combat_warriors_path',
    name: "Warrior's Path",
    description: 'Win 10 combats',
    category: 'combat',
    requirement: 10,
    icon: '🗡️',
    reward: { gold: 30, reputation: 5 },
  },
  {
    id: 'combat_slayer',
    name: 'Slayer',
    description: 'Win 50 combats',
    category: 'combat',
    requirement: 50,
    icon: '💀',
    reward: { gold: 100, reputation: 15 },
  },
  {
    id: 'combat_boss_killer',
    name: 'Boss Killer',
    description: 'Defeat a boss enemy',
    category: 'combat',
    requirement: 1,
    icon: '👑',
    reward: { gold: 50, reputation: 10 },
  },
  {
    id: 'combat_untouchable',
    name: 'Untouchable',
    description: 'Win a combat at full HP',
    category: 'combat',
    requirement: 1,
    icon: '🛡️',
    reward: { gold: 25, reputation: 5 },
  },

  // Collection
  {
    id: 'collection_collector',
    name: 'Collector',
    description: 'Own 5 items',
    category: 'collection',
    requirement: 5,
    icon: '🎒',
    reward: { gold: 10 },
  },
  {
    id: 'collection_hoarder',
    name: 'Hoarder',
    description: 'Own 20 items',
    category: 'collection',
    requirement: 20,
    icon: '📦',
    reward: { gold: 50, reputation: 5 },
  },
  {
    id: 'collection_spell_scholar',
    name: 'Spell Scholar',
    description: 'Learn 3 spells',
    category: 'collection',
    requirement: 3,
    icon: '📖',
    reward: { gold: 30, reputation: 5 },
  },
  {
    id: 'collection_well_equipped',
    name: 'Well Equipped',
    description: 'Equip all 3 equipment slots',
    category: 'collection',
    requirement: 3,
    icon: '🛡️',
    reward: { gold: 20 },
  },

  // Progression
  {
    id: 'progression_level_2',
    name: 'Level 2',
    description: 'Reach level 2',
    category: 'progression',
    requirement: 2,
    icon: '⬆️',
    reward: { gold: 10 },
  },
  {
    id: 'progression_level_5',
    name: 'Level 5',
    description: 'Reach level 5',
    category: 'progression',
    requirement: 5,
    icon: '⬆️',
    reward: { gold: 30, reputation: 5 },
  },
  {
    id: 'progression_level_10',
    name: 'Level 10',
    description: 'Reach level 10',
    category: 'progression',
    requirement: 10,
    icon: '⬆️',
    reward: { gold: 100, reputation: 15 },
  },
  {
    id: 'progression_rich',
    name: 'Rich',
    description: 'Accumulate 100 gold',
    category: 'progression',
    requirement: 100,
    icon: '💰',
    reward: { reputation: 5 },
  },
  {
    id: 'progression_famous',
    name: 'Famous',
    description: 'Reach 50 reputation',
    category: 'progression',
    requirement: 50,
    icon: '⭐',
    reward: { gold: 50 },
  },

  // Special
  {
    id: 'special_survivor',
    name: 'Survivor',
    description: 'Survive combat with less than 5 HP',
    category: 'special',
    requirement: 1,
    icon: '💗',
    reward: { gold: 25, reputation: 5 },
  },
  {
    id: 'special_shopkeeper_friend',
    name: "Shopkeeper's Friend",
    description: 'Buy 10 items from shops',
    category: 'special',
    requirement: 10,
    icon: '🏪',
    reward: { gold: 20, reputation: 5 },
  },
  {
    id: 'special_death_defier',
    name: 'Death Defier',
    description: 'Die and continue your journey',
    category: 'special',
    requirement: 1,
    icon: '☠️',
    reward: { gold: 15, reputation: 3 },
  },
]
