import { GeneratedClass } from '@/app/tap-tap-adventure/models/generatedClass'

export const FALLBACK_CLASSES: GeneratedClass[] = [
  // Martial
  {
    id: 'iron-sentinel',
    name: 'Iron Sentinel',
    combatStyle: 'martial',
    modifier: 'iron',
    description: 'An immovable bastion clad in heavy iron plate, shrugging off blows that would fell lesser warriors.',
    statDistribution: { strength: 8, intelligence: 4, luck: 6, charisma: 5 },
    favoredSchool: 'war',
    manaMultiplier: 0.6,
    spellSlots: 2,
    startingAbility: {
      name: 'Iron Guard',
      description: 'Brace behind an iron shield, reducing incoming damage and retaliating with a crushing counter.',
      manaCost: 5,
      cooldown: 3,
      target: 'self',
      effects: [
        { type: 'shield', value: 12 },
        { type: 'buff', value: 3, stat: 'defense', duration: 2 },
      ],
      tags: ['war', 'defense', 'iron'],
    },
    startingWeapon: { name: 'Iron Sword', description: 'A sturdy iron blade, well-balanced and reliable.', effects: { strength: 2, range: 'close' } },
  },
  {
    id: 'flame-knight',
    name: 'Flame Knight',
    combatStyle: 'martial',
    modifier: 'fire',
    description: 'A templar whose blade burns with sacred flame, scorching foes with every strike.',
    statDistribution: { strength: 8, intelligence: 5, luck: 5, charisma: 5 },
    favoredSchool: 'war',
    manaMultiplier: 0.7,
    spellSlots: 3,
    startingAbility: {
      name: 'Blazing Slash',
      description: 'Ignite your weapon and deliver a fiery cut that leaves the enemy burning.',
      manaCost: 6,
      cooldown: 2,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 8, element: 'fire' },
        { type: 'damage_over_time', value: 3, duration: 2, element: 'fire' },
      ],
      tags: ['war', 'fire', 'melee'],
    },
    startingWeapon: { name: 'Wooden Club', description: 'A heavy wooden club, simple but effective.', effects: { strength: 2, range: 'close' } },
  },
  {
    id: 'storm-berserker',
    name: 'Storm Berserker',
    combatStyle: 'martial',
    modifier: 'storm',
    description: 'A raging warrior channeling the fury of thunderstorms into devastating melee assaults.',
    statDistribution: { strength: 9, intelligence: 3, luck: 6, charisma: 5 },
    favoredSchool: 'war',
    manaMultiplier: 0.6,
    spellSlots: 2,
    startingAbility: {
      name: 'Thunder Strike',
      description: 'Slam the ground with electrified fists, dealing lightning damage and stunning the target.',
      manaCost: 7,
      cooldown: 3,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 12, element: 'lightning' },
        { type: 'stun', value: 1 },
      ],
      tags: ['war', 'storm', 'melee'],
    },
    startingWeapon: { name: 'Simple Axe', description: 'A basic hand axe with a sharp edge.', effects: { strength: 2, range: 'close' } },
  },

  // Arcane
  {
    id: 'frost-weaver',
    name: 'Frost Weaver',
    combatStyle: 'arcane',
    modifier: 'ice',
    description: 'A sorcerer who threads ice crystals through the air, freezing enemies in place.',
    statDistribution: { strength: 3, intelligence: 10, luck: 5, charisma: 5 },
    favoredSchool: 'arcane',
    manaMultiplier: 1.4,
    spellSlots: 6,
    startingAbility: {
      name: 'Frost Bolt',
      description: 'Hurl a shard of pure ice that damages and slows the target.',
      manaCost: 4,
      cooldown: 1,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 10, element: 'ice' },
        { type: 'debuff', value: 2, stat: 'attack', duration: 2 },
      ],
      tags: ['arcane', 'ice', 'ranged'],
    },
    startingWeapon: { name: 'Apprentice Wand', description: 'A plain wooden wand, standard issue for novice mages.', effects: { intelligence: 2, range: 'far' } },
  },
  {
    id: 'void-channeler',
    name: 'Void Channeler',
    combatStyle: 'arcane',
    modifier: 'void',
    description: 'A mage who taps the empty space between worlds, draining life and sanity from foes.',
    statDistribution: { strength: 3, intelligence: 9, luck: 6, charisma: 5 },
    favoredSchool: 'arcane',
    manaMultiplier: 1.3,
    spellSlots: 5,
    startingAbility: {
      name: 'Void Drain',
      description: 'Open a rift to the void, dealing shadow damage and restoring your mana.',
      manaCost: 5,
      cooldown: 2,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 8, element: 'shadow' },
        { type: 'mana_restore', value: 3 },
      ],
      tags: ['arcane', 'void', 'ranged'],
    },
    startingWeapon: { name: 'Oak Staff', description: 'A tall oak staff, worn smooth from use.', effects: { intelligence: 2, range: 'far' } },
  },
  {
    id: 'tempest-sage',
    name: 'Tempest Sage',
    combatStyle: 'arcane',
    modifier: 'storm',
    description: 'A scholar of elemental storms who commands lightning and wind with academic precision.',
    statDistribution: { strength: 4, intelligence: 9, luck: 5, charisma: 5 },
    favoredSchool: 'arcane',
    manaMultiplier: 1.3,
    spellSlots: 5,
    startingAbility: {
      name: 'Chain Lightning',
      description: 'Unleash a bolt of lightning that arcs to deal damage and builds combo momentum.',
      manaCost: 6,
      cooldown: 2,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 11, element: 'lightning' },
        { type: 'combo_boost', value: 1 },
      ],
      tags: ['arcane', 'storm', 'ranged'],
    },
    startingWeapon: { name: 'Simple Scepter', description: 'A basic scepter topped with a dull crystal.', effects: { intelligence: 2, range: 'far' } },
  },

  // Shadow
  {
    id: 'shadow-blade',
    name: 'Shadow Blade',
    combatStyle: 'shadow',
    modifier: 'void',
    description: 'An assassin who strikes from tears in reality, vanishing before the enemy can react.',
    statDistribution: { strength: 5, intelligence: 4, luck: 9, charisma: 5 },
    favoredSchool: 'shadow',
    manaMultiplier: 0.8,
    spellSlots: 3,
    startingAbility: {
      name: 'Umbral Strike',
      description: 'Phase through shadows to strike a vital point, boosting combo count.',
      manaCost: 5,
      cooldown: 2,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 9, element: 'shadow' },
        { type: 'combo_boost', value: 2 },
      ],
      tags: ['shadow', 'melee', 'stealth'],
    },
    startingWeapon: { name: 'Worn Dagger', description: 'A short dagger with a leather-wrapped grip.', effects: { strength: 1, range: 'close' } },
  },
  {
    id: 'blood-stalker',
    name: 'Blood Stalker',
    combatStyle: 'shadow',
    modifier: 'blood',
    description: 'A predator who feeds on the lifeblood of enemies, growing stronger with each kill.',
    statDistribution: { strength: 6, intelligence: 3, luck: 9, charisma: 5 },
    favoredSchool: 'shadow',
    manaMultiplier: 0.7,
    spellSlots: 3,
    startingAbility: {
      name: 'Blood Siphon',
      description: 'Drive a cursed blade into the target, draining their life to restore your own.',
      manaCost: 6,
      cooldown: 2,
      target: 'enemy',
      effects: [
        { type: 'lifesteal', value: 8 },
        { type: 'bleed', value: 3, duration: 2 },
      ],
      tags: ['shadow', 'blood', 'melee'],
    },
    startingWeapon: { name: 'Rusty Shortsword', description: 'A battered shortsword, still sharp enough.', effects: { strength: 1, range: 'close' } },
  },
  {
    id: 'beast-lurker',
    name: 'Beast Lurker',
    combatStyle: 'shadow',
    modifier: 'beast',
    description: 'A feral hunter who stalks prey through darkness, striking with bestial ferocity.',
    statDistribution: { strength: 6, intelligence: 3, luck: 9, charisma: 5 },
    favoredSchool: 'shadow',
    manaMultiplier: 0.7,
    spellSlots: 3,
    startingAbility: {
      name: 'Pounce',
      description: 'Leap from the shadows with claws bared, dealing damage and stunning the prey.',
      manaCost: 5,
      cooldown: 3,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 10 },
        { type: 'stun', value: 1 },
      ],
      tags: ['shadow', 'beast', 'melee'],
    },
    startingWeapon: { name: 'Chipped Knife', description: 'A utility knife pressed into service as a weapon.', effects: { strength: 1, range: 'close' } },
  },

  // Divine
  {
    id: 'light-warden',
    name: 'Light Warden',
    combatStyle: 'divine',
    modifier: 'light',
    description: 'A holy guardian who channels radiant energy to protect allies and smite the unholy.',
    statDistribution: { strength: 6, intelligence: 7, luck: 5, charisma: 5 },
    favoredSchool: 'arcane',
    manaMultiplier: 1.1,
    spellSlots: 4,
    startingAbility: {
      name: 'Divine Shield',
      description: 'Call upon holy light to form a protective barrier and heal minor wounds.',
      manaCost: 6,
      cooldown: 3,
      target: 'self',
      effects: [
        { type: 'shield', value: 10 },
        { type: 'heal', value: 5 },
      ],
      tags: ['divine', 'light', 'defense'],
    },
    startingWeapon: { name: 'Wooden Mace', description: 'A sturdy mace with an iron-banded head.', effects: { strength: 1, intelligence: 1, range: 'close' } },
  },
  {
    id: 'nature-priest',
    name: 'Nature Priest',
    combatStyle: 'divine',
    modifier: 'nature',
    description: 'A healer drawing power from the living world, mending wounds with vines and pollen.',
    statDistribution: { strength: 5, intelligence: 8, luck: 5, charisma: 5 },
    favoredSchool: 'nature',
    manaMultiplier: 1.2,
    spellSlots: 5,
    startingAbility: {
      name: 'Verdant Mend',
      description: 'Summon regenerative vines that heal over time and cleanse harmful effects.',
      manaCost: 5,
      cooldown: 2,
      target: 'self',
      effects: [
        { type: 'heal_over_time', value: 4, duration: 3 },
        { type: 'cleanse', value: 0 },
      ],
      tags: ['nature', 'heal', 'divine'],
    },
    startingWeapon: { name: 'Iron Flail', description: 'A simple flail with a weighted chain.', effects: { strength: 1, intelligence: 1, range: 'close' } },
  },
  {
    id: 'time-keeper',
    name: 'Time Keeper',
    combatStyle: 'divine',
    modifier: 'time',
    description: 'A chronomancer who bends the flow of time, slowing enemies and hastening allies.',
    statDistribution: { strength: 4, intelligence: 8, luck: 6, charisma: 5 },
    favoredSchool: 'arcane',
    manaMultiplier: 1.2,
    spellSlots: 5,
    startingAbility: {
      name: 'Temporal Shift',
      description: 'Warp time around the enemy, slowing their attacks while boosting your own speed.',
      manaCost: 7,
      cooldown: 3,
      target: 'enemy',
      effects: [
        { type: 'debuff', value: 3, stat: 'attack', duration: 2 },
        { type: 'combo_boost', value: 1 },
      ],
      tags: ['divine', 'time', 'ranged'],
    },
    startingWeapon: { name: 'Plain Hammer', description: 'A well-worn hammer, practical and dependable.', effects: { strength: 1, intelligence: 1, range: 'close' } },
  },

  // Primal
  {
    id: 'beast-tamer',
    name: 'Beast Tamer',
    combatStyle: 'primal',
    modifier: 'beast',
    description: 'A wild warrior who fights alongside spectral beasts, combining brute force and cunning.',
    statDistribution: { strength: 7, intelligence: 4, luck: 7, charisma: 5 },
    favoredSchool: 'nature',
    manaMultiplier: 0.8,
    spellSlots: 3,
    startingAbility: {
      name: 'Spirit Claw',
      description: 'Summon a spectral beast claw that rends the enemy and builds combo stacks.',
      manaCost: 5,
      cooldown: 2,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 9, element: 'nature' },
        { type: 'combo_boost', value: 1 },
      ],
      tags: ['primal', 'beast', 'melee'],
    },
    startingWeapon: { name: 'Wooden Spear', description: 'A sharpened spear with a fire-hardened tip.', effects: { strength: 1, intelligence: 1, range: 'mid' } },
  },
  {
    id: 'flame-shaman',
    name: 'Flame Shaman',
    combatStyle: 'primal',
    modifier: 'fire',
    description: 'A tribal mystic who dances with wildfire, healing through destruction.',
    statDistribution: { strength: 6, intelligence: 6, luck: 6, charisma: 5 },
    favoredSchool: 'nature',
    manaMultiplier: 1.0,
    spellSlots: 4,
    startingAbility: {
      name: 'Wildfire Totem',
      description: 'Plant a fiery totem that burns the enemy over time.',
      manaCost: 6,
      cooldown: 3,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 5, element: 'fire' },
        { type: 'damage_over_time', value: 4, duration: 3, element: 'fire' },
      ],
      tags: ['primal', 'fire', 'totem'],
    },
    startingWeapon: { name: 'Hunting Bow', description: 'A simple shortbow made from flexible wood.', effects: { strength: 1, intelligence: 1, range: 'mid' } },
  },
  {
    id: 'ice-warden',
    name: 'Ice Warden',
    combatStyle: 'primal',
    modifier: 'ice',
    description: 'A guardian of frozen wilds who commands permafrost to shield and slow.',
    statDistribution: { strength: 7, intelligence: 5, luck: 6, charisma: 5 },
    favoredSchool: 'nature',
    manaMultiplier: 0.9,
    spellSlots: 3,
    startingAbility: {
      name: 'Permafrost Armor',
      description: 'Encase yourself in ice, gaining a shield and reducing incoming damage.',
      manaCost: 6,
      cooldown: 3,
      target: 'self',
      effects: [
        { type: 'shield', value: 10 },
        { type: 'damage_reduction', value: 0, percentage: 20, duration: 2 },
      ],
      tags: ['primal', 'ice', 'defense'],
    },
    startingWeapon: { name: 'Quarterstaff', description: 'A solid wooden staff, good for keeping distance.', effects: { strength: 1, intelligence: 1, range: 'mid' } },
  },

  // Psionic
  {
    id: 'mind-bender',
    name: 'Mind Bender',
    combatStyle: 'psionic',
    modifier: 'void',
    description: 'A psychic who twists reality with thought alone, leaving enemies disoriented and broken.',
    statDistribution: { strength: 3, intelligence: 8, luck: 7, charisma: 5 },
    favoredSchool: 'arcane',
    manaMultiplier: 1.3,
    spellSlots: 5,
    startingAbility: {
      name: 'Psychic Blast',
      description: 'Assault the enemy\'s mind with a wave of psionic force, dealing damage and stunning.',
      manaCost: 7,
      cooldown: 3,
      target: 'enemy',
      effects: [
        { type: 'damage', value: 10, element: 'arcane' },
        { type: 'stun', value: 1 },
      ],
      tags: ['psionic', 'void', 'ranged'],
    },
    startingWeapon: { name: 'Crystal Focus', description: 'A rough crystal that hums faintly when held.', effects: { intelligence: 1, range: 'far' } },
  },
  {
    id: 'blood-seer',
    name: 'Blood Seer',
    combatStyle: 'psionic',
    modifier: 'blood',
    description: 'A hemomancer who reads the future in blood, sacrificing vitality for devastating foresight.',
    statDistribution: { strength: 4, intelligence: 7, luck: 7, charisma: 5 },
    favoredSchool: 'shadow',
    manaMultiplier: 1.1,
    spellSlots: 4,
    startingAbility: {
      name: 'Crimson Vision',
      description: 'Spill your own blood to gain deadly insight, buffing your attacks at a health cost.',
      manaCost: 4,
      cooldown: 2,
      target: 'self',
      effects: [
        { type: 'buff', value: 5, stat: 'attack', duration: 3 },
        { type: 'damage', value: 3 },
      ],
      tags: ['psionic', 'blood', 'self-harm'],
    },
    startingWeapon: { name: 'Simple Rod', description: 'A plain metal rod used to channel mental energy.', effects: { intelligence: 1, range: 'far' } },
  },
]
