import { ClassSkillTree } from '@/app/tap-tap-adventure/models/classSkillTree'

export const FALLBACK_SKILL_TREES: Record<string, ClassSkillTree> = {
  warrior: {
    classId: 'warrior',
    className: 'Warrior',
    nodes: [
      // Tier 1 (2 nodes, level 2)
      {
        id: 'warrior_t1_iron_fortitude',
        name: 'Iron Fortitude',
        description: 'Your body is hardened through years of combat training, granting you additional maximum HP.',
        icon: '🛡️',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'maxHp', value: 15 },
        requiredLevel: 2,
      },
      {
        id: 'warrior_t1_battle_hardened',
        name: 'Battle Hardened',
        description: 'Constant combat sharpens your instincts, increasing your attack power.',
        icon: '⚔️',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'attack', value: 3 },
        requiredLevel: 2,
      },
      // Tier 2 (3 nodes, level 5)
      {
        id: 'warrior_t2_shield_mastery',
        name: 'Shield Mastery',
        description: 'Mastery of defensive stances greatly improves your ability to deflect incoming blows.',
        icon: '🔰',
        tier: 2,
        prerequisiteIds: ['warrior_t1_iron_fortitude'],
        effect: { type: 'percentage_bonus', target: 'maxHp', value: 10 },
        requiredLevel: 5,
      },
      {
        id: 'warrior_t2_weapon_expertise',
        name: 'Weapon Expertise',
        description: 'Deep understanding of weapon mechanics lets you find openings others cannot.',
        icon: '🗡️',
        tier: 2,
        prerequisiteIds: ['warrior_t1_battle_hardened'],
        effect: { type: 'flat_bonus', target: 'attack', value: 5 },
        requiredLevel: 5,
      },
      {
        id: 'warrior_t2_battle_cry',
        name: 'Battle Cry',
        description: 'Your fearsome war cry shakes the resolve of enemies, improving your combat effectiveness.',
        icon: '📣',
        tier: 2,
        prerequisiteIds: ['warrior_t1_iron_fortitude'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 8 },
        requiredLevel: 5,
      },
      // Tier 3 (3 nodes, level 8)
      {
        id: 'warrior_t3_unbreakable',
        name: 'Unbreakable',
        description: 'Your sheer physical resilience makes you nearly impossible to bring down.',
        icon: '🪨',
        tier: 3,
        prerequisiteIds: ['warrior_t2_shield_mastery'],
        effect: { type: 'percentage_bonus', target: 'maxHp', value: 15 },
        requiredLevel: 8,
      },
      {
        id: 'warrior_t3_blade_fury',
        name: 'Blade Fury',
        description: 'In the heat of battle you unleash a flurry of strikes, increasing your attack dramatically.',
        icon: '🌀',
        tier: 3,
        prerequisiteIds: ['warrior_t2_weapon_expertise'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 12 },
        requiredLevel: 8,
      },
      {
        id: 'warrior_t3_veteran',
        name: 'Veteran',
        description: 'Battle-worn experience improves all of your combat attributes.',
        icon: '🎖️',
        tier: 3,
        prerequisiteIds: ['warrior_t2_battle_cry'],
        effect: { type: 'stat_bonus', target: 'all_stats', value: 2 },
        requiredLevel: 8,
      },
      // Tier 4 (1 capstone node, level 12)
      {
        id: 'warrior_t4_warlord',
        name: 'Warlord',
        description: 'The pinnacle of martial mastery — you are a living weapon whose every step shakes the earth.',
        icon: '👑',
        tier: 4,
        prerequisiteIds: ['warrior_t3_unbreakable', 'warrior_t3_blade_fury', 'warrior_t3_veteran'],
        effect: { type: 'percentage_bonus', target: 'all_stats', value: 10 },
        requiredLevel: 12,
      },
    ],
  },

  mage: {
    classId: 'mage',
    className: 'Mage',
    nodes: [
      // Tier 1
      {
        id: 'mage_t1_arcane_focus',
        name: 'Arcane Focus',
        description: 'Sharpening your concentration amplifies your magical reserves.',
        icon: '🔮',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'maxMana', value: 20 },
        requiredLevel: 2,
      },
      {
        id: 'mage_t1_spellcraft',
        name: 'Spellcraft',
        description: 'Refined study of arcane formulae boosts the raw damage of your spells.',
        icon: '📜',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'attack', value: 2 },
        requiredLevel: 2,
      },
      // Tier 2
      {
        id: 'mage_t2_mana_well',
        name: 'Mana Well',
        description: 'You tap into a deep reservoir of arcane energy, greatly expanding your maximum mana.',
        icon: '💧',
        tier: 2,
        prerequisiteIds: ['mage_t1_arcane_focus'],
        effect: { type: 'percentage_bonus', target: 'maxMana', value: 20 },
        requiredLevel: 5,
      },
      {
        id: 'mage_t2_ley_conduit',
        name: 'Ley Conduit',
        description: 'You channel ambient magical energy, accelerating your mana regeneration.',
        icon: '⚡',
        tier: 2,
        prerequisiteIds: ['mage_t1_arcane_focus'],
        effect: { type: 'flat_bonus', target: 'mana_regen', value: 2 },
        requiredLevel: 5,
      },
      {
        id: 'mage_t2_spell_weaving',
        name: 'Spell Weaving',
        description: 'Interweaving spell matrices allows you to cast more efficiently and powerfully.',
        icon: '🌟',
        tier: 2,
        prerequisiteIds: ['mage_t1_spellcraft'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 10 },
        requiredLevel: 5,
      },
      // Tier 3
      {
        id: 'mage_t3_arcane_overload',
        name: 'Arcane Overload',
        description: 'Pushing beyond normal limits floods your spells with overwhelming arcane energy.',
        icon: '💥',
        tier: 3,
        prerequisiteIds: ['mage_t2_spell_weaving'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 15 },
        requiredLevel: 8,
      },
      {
        id: 'mage_t3_wellspring',
        name: 'Wellspring',
        description: 'Your connection to magical sources becomes nearly inexhaustible.',
        icon: '🌊',
        tier: 3,
        prerequisiteIds: ['mage_t2_mana_well'],
        effect: { type: 'percentage_bonus', target: 'maxMana', value: 25 },
        requiredLevel: 8,
      },
      {
        id: 'mage_t3_runic_insight',
        name: 'Runic Insight',
        description: 'Deep arcane knowledge improves all of your magical capabilities.',
        icon: '🔯',
        tier: 3,
        prerequisiteIds: ['mage_t2_ley_conduit'],
        effect: { type: 'stat_bonus', target: 'all_stats', value: 2 },
        requiredLevel: 8,
      },
      // Tier 4
      {
        id: 'mage_t4_archmage',
        name: 'Archmage',
        description: 'You have attained the highest pinnacle of magical mastery — your power transcends mortal limits.',
        icon: '✨',
        tier: 4,
        prerequisiteIds: ['mage_t3_arcane_overload', 'mage_t3_wellspring', 'mage_t3_runic_insight'],
        effect: { type: 'percentage_bonus', target: 'maxMana', value: 30 },
        requiredLevel: 12,
      },
    ],
  },

  rogue: {
    classId: 'rogue',
    className: 'Rogue',
    nodes: [
      // Tier 1
      {
        id: 'rogue_t1_quick_fingers',
        name: 'Quick Fingers',
        description: 'Lightning-fast hands let you pick pockets and act before others can react.',
        icon: '🤏',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'luck', value: 2 },
        requiredLevel: 2,
      },
      {
        id: 'rogue_t1_shadow_walk',
        name: 'Shadow Walk',
        description: 'Moving silently through shadows makes it easier for you to escape dangerous situations.',
        icon: '👤',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'flee_chance', value: 10 },
        requiredLevel: 2,
      },
      // Tier 2
      {
        id: 'rogue_t2_shadow_step',
        name: 'Shadow Step',
        description: 'Teleporting through shadows, you reappear next to your enemy for a devastating strike.',
        icon: '🌑',
        tier: 2,
        prerequisiteIds: ['rogue_t1_shadow_walk'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 10 },
        requiredLevel: 5,
      },
      {
        id: 'rogue_t2_poison_craft',
        name: 'Poison Craft',
        description: 'You coat your weapons in deadly toxins, adding persistent damage to your attacks.',
        icon: '☠️',
        tier: 2,
        prerequisiteIds: ['rogue_t1_quick_fingers'],
        effect: { type: 'flat_bonus', target: 'attack', value: 4 },
        requiredLevel: 5,
      },
      {
        id: 'rogue_t2_larceny',
        name: 'Larceny',
        description: 'Skilled thievery nets you extra gold from every encounter.',
        icon: '💰',
        tier: 2,
        prerequisiteIds: ['rogue_t1_quick_fingers'],
        effect: { type: 'percentage_bonus', target: 'gold_bonus', value: 15 },
        requiredLevel: 5,
      },
      // Tier 3
      {
        id: 'rogue_t3_lethal_precision',
        name: 'Lethal Precision',
        description: 'Years of targeting vital spots makes your strikes devastatingly effective.',
        icon: '🎯',
        tier: 3,
        prerequisiteIds: ['rogue_t2_poison_craft'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 15 },
        requiredLevel: 8,
      },
      {
        id: 'rogue_t3_ghost',
        name: 'Ghost',
        description: 'You become almost impossible to track, greatly improving your chances of escaping combat.',
        icon: '👻',
        tier: 3,
        prerequisiteIds: ['rogue_t2_shadow_step'],
        effect: { type: 'percentage_bonus', target: 'flee_chance', value: 20 },
        requiredLevel: 8,
      },
      {
        id: 'rogue_t3_treasure_sense',
        name: 'Treasure Sense',
        description: 'A honed instinct for wealth improves your fortune in all things.',
        icon: '💎',
        tier: 3,
        prerequisiteIds: ['rogue_t2_larceny'],
        effect: { type: 'flat_bonus', target: 'luck', value: 3 },
        requiredLevel: 8,
      },
      // Tier 4
      {
        id: 'rogue_t4_shadow_master',
        name: 'Shadow Master',
        description: 'The ultimate master of shadow and subterfuge — death itself cannot catch you unawares.',
        icon: '🥷',
        tier: 4,
        prerequisiteIds: ['rogue_t3_lethal_precision', 'rogue_t3_ghost', 'rogue_t3_treasure_sense'],
        effect: { type: 'stat_bonus', target: 'all_stats', value: 3 },
        requiredLevel: 12,
      },
    ],
  },

  ranger: {
    classId: 'ranger',
    className: 'Ranger',
    nodes: [
      // Tier 1
      {
        id: 'ranger_t1_eagle_eye',
        name: 'Eagle Eye',
        description: 'Razor-sharp vision lets you spot enemies and opportunities from great distances.',
        icon: '🦅',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'loot_chance', value: 5 },
        requiredLevel: 2,
      },
      {
        id: 'ranger_t1_natures_bond',
        name: "Nature's Bond",
        description: 'Your bond with the natural world hastens your recovery while traveling.',
        icon: '🌿',
        tier: 1,
        prerequisiteIds: [],
        effect: { type: 'flat_bonus', target: 'heal_rate', value: 2 },
        requiredLevel: 2,
      },
      // Tier 2
      {
        id: 'ranger_t2_beast_companion',
        name: 'Beast Companion',
        description: 'A loyal animal companion fights by your side, adding to your attack power.',
        icon: '🐺',
        tier: 2,
        prerequisiteIds: ['ranger_t1_natures_bond'],
        effect: { type: 'flat_bonus', target: 'attack', value: 4 },
        requiredLevel: 5,
      },
      {
        id: 'ranger_t2_hunters_mark',
        name: "Hunter's Mark",
        description: 'Marking your quarry reveals their weaknesses, dramatically improving your accuracy.',
        icon: '🎯',
        tier: 2,
        prerequisiteIds: ['ranger_t1_eagle_eye'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 10 },
        requiredLevel: 5,
      },
      {
        id: 'ranger_t2_pathfinder',
        name: 'Pathfinder',
        description: 'Knowledge of hidden trails lets you move faster and discover more treasures.',
        icon: '🗺️',
        tier: 2,
        prerequisiteIds: ['ranger_t1_eagle_eye'],
        effect: { type: 'percentage_bonus', target: 'loot_chance', value: 10 },
        requiredLevel: 5,
      },
      // Tier 3
      {
        id: 'ranger_t3_primal_fury',
        name: 'Primal Fury',
        description: 'Tapping into primal instincts unleashes devastating animal ferocity.',
        icon: '🔥',
        tier: 3,
        prerequisiteIds: ['ranger_t2_beast_companion'],
        effect: { type: 'percentage_bonus', target: 'attack', value: 12 },
        requiredLevel: 8,
      },
      {
        id: 'ranger_t3_wilderness_mastery',
        name: 'Wilderness Mastery',
        description: 'Total mastery of the wild lets you thrive where others perish.',
        icon: '🌲',
        tier: 3,
        prerequisiteIds: ['ranger_t2_hunters_mark'],
        effect: { type: 'flat_bonus', target: 'maxHp', value: 20 },
        requiredLevel: 8,
      },
      {
        id: 'ranger_t3_keen_senses',
        name: 'Keen Senses',
        description: 'Sharpened senses give you an edge in all aspects of adventuring.',
        icon: '👁️',
        tier: 3,
        prerequisiteIds: ['ranger_t2_pathfinder'],
        effect: { type: 'stat_bonus', target: 'all_stats', value: 2 },
        requiredLevel: 8,
      },
      // Tier 4
      {
        id: 'ranger_t4_apex_predator',
        name: 'Apex Predator',
        description: 'You are the ultimate hunter — no prey escapes and no terrain can slow you.',
        icon: '🏹',
        tier: 4,
        prerequisiteIds: ['ranger_t3_primal_fury', 'ranger_t3_wilderness_mastery', 'ranger_t3_keen_senses'],
        effect: { type: 'percentage_bonus', target: 'loot_chance', value: 20 },
        requiredLevel: 12,
      },
    ],
  },
}
