export type LandmarkType = 'town' | 'dungeon' | 'shrine' | 'ruins' | 'waypoint'

export interface LandmarkTemplate {
  id: string
  name: string
  type: LandmarkType
  description: string
  icon: string
  hasShop: boolean
  encounterPrompt: string
  isSecret?: boolean
}

export const LANDMARK_TEMPLATES: Record<string, LandmarkTemplate[]> = {
  hearthwood: [
    {
      id: 'sv_notice_board',
      name: 'Notice Board',
      type: 'waypoint',
      description: 'A weathered board covered in job postings and missing-person notices.',
      icon: '📋',
      hasShop: false,
      encounterPrompt: 'A crowded notice board in the village square. Adventurers and locals gather to read postings about work, missing persons, and local news.',
    },
    {
      id: 'sv_tavern',
      name: 'The Rusty Flagon',
      type: 'town',
      description: 'A lively tavern where weary travelers gather to trade tales and resupply.',
      icon: '🍺',
      hasShop: true,
      encounterPrompt: 'A warm, bustling tavern filled with the smell of roasted meat and spilled ale. The barkeep is friendly and the locals are chatty.',
    },
    {
      id: 'sv_temple',
      name: 'Village Temple',
      type: 'shrine',
      description: 'A modest stone temple offering blessings to departing adventurers.',
      icon: '⛪',
      hasShop: false,
      encounterPrompt: 'A small but well-kept stone temple. A robed priest offers blessings and the scent of incense fills the air.',
    },
    {
      id: 'sv_blacksmith',
      name: "Garron's Forge",
      type: 'town',
      description: 'A busy smithy where the clanging of hammers rings from dawn to dusk.',
      icon: '⚒️',
      hasShop: true,
      encounterPrompt: "A hot smithy where sparks fly and the smell of molten iron fills the air. The blacksmith Garron is gruff but fair, selling quality wares.",
    },
    {
      id: 'sv_well',
      name: 'The Old Well',
      type: 'ruins',
      description: 'An ancient well said to grant visions to those who drink from it.',
      icon: '🪣',
      hasShop: false,
      encounterPrompt: 'An ancient moss-covered well at the edge of the village. Locals whisper that it sometimes shows visions of the future in its depths.',
    },
  ],

  green_meadows: [
    {
      id: 'gm_mill',
      name: 'The Old Mill',
      type: 'ruins',
      description: 'A crumbling watermill whose wheel still turns, grinding something unseen.',
      icon: '🏚️',
      hasShop: false,
      encounterPrompt: 'A crumbling watermill stands beside a slow stream. The wheel still turns despite the rot, and odd sounds come from inside.',
    },
    {
      id: 'gm_hamlet',
      name: 'Willowbrook',
      type: 'town',
      description: 'A small farming hamlet where traders stop on their way to the city.',
      icon: '🏘️',
      hasShop: true,
      encounterPrompt: 'A small farming hamlet with smoke rising from chimneys. Farmers and traveling merchants mingle at the market stalls.',
    },
    {
      id: 'gm_shrine',
      name: 'Nature Shrine',
      type: 'shrine',
      description: 'An ancient shrine draped in vines, tended by an old druid.',
      icon: '🌿',
      hasShop: false,
      encounterPrompt: 'An ancient shrine draped in living vines and wildflowers. A weathered druid tends the offerings left by passing travelers.',
    },
    {
      id: 'gm_ford',
      name: "Pebble Ford",
      type: 'waypoint',
      description: 'A shallow crossing where the old road meets the river.',
      icon: '🪧',
      hasShop: false,
      encounterPrompt: 'A well-worn crossing point over a babbling river. The stones are smooth and the water is clear, but something feels like it is watching from the rushes.',
    },
  ],

  dark_forest: [
    {
      id: 'df_waystone',
      name: 'Cracked Waystone',
      type: 'waypoint',
      description: 'A cracked stone marker barely visible through the underbrush.',
      icon: '🪨',
      hasShop: false,
      encounterPrompt: 'A cracked stone waymarker half-swallowed by roots. Strange runes are carved into its surface and the air around it feels thick.',
    },
    {
      id: 'df_cabin',
      name: "Woodcutter's Rest",
      type: 'town',
      description: 'A fortified cabin where bold merchants trade with forest folk.',
      icon: '🏕️',
      hasShop: true,
      encounterPrompt: "A stout log cabin with iron-reinforced shutters. A cautious merchant trades supplies here, relying on the forest folk for protection.",
    },
    {
      id: 'df_altar',
      name: 'Shadow Altar',
      type: 'shrine',
      description: 'A dark altar covered in strange offerings and flickering candles.',
      icon: '🕯️',
      hasShop: false,
      encounterPrompt: 'A low stone altar covered in melted candles, feathers, and strange trinkets. The shadows here seem deeper than they should be.',
    },
    {
      id: 'df_ruins',
      name: 'Overgrown Keep',
      type: 'ruins',
      description: 'The moss-choked remains of a keep swallowed by the forest centuries ago.',
      icon: '🏯',
      hasShop: false,
      encounterPrompt: 'The crumbling walls of an old keep rise from the undergrowth. Trees have forced their roots through the stone and the halls echo strangely.',
    },
  ],

  sunken_ruins: [
    {
      id: 'sr_pier',
      name: 'Drowned Pier',
      type: 'ruins',
      description: 'The rotting remains of a dock jutting from a flooded plaza.',
      icon: '🚢',
      hasShop: false,
      encounterPrompt: 'Rotting wooden piers stretch over dark, still water. Something large moves beneath the surface, and the air smells of brine and decay.',
    },
    {
      id: 'sr_market',
      name: 'Smuggler\'s Cove',
      type: 'town',
      description: 'A hidden market where salvagers trade waterlogged relics.',
      icon: '⚓',
      hasShop: true,
      encounterPrompt: 'A hidden cove beneath a partially submerged arch. Salvagers and traders barter over damp relics and ancient artifacts dredged from the ruins.',
    },
    {
      id: 'sr_shrine',
      name: 'Tidal Shrine',
      type: 'shrine',
      description: 'A half-flooded shrine to ancient sea gods, still receiving offerings.',
      icon: '🐚',
      hasShop: false,
      encounterPrompt: 'A partially submerged shrine with offerings piled on a dry ledge above the waterline. The carved faces of sea gods stare from the walls.',
    },
    {
      id: 'sr_vault',
      name: 'Sealed Vault',
      type: 'dungeon',
      description: 'A massive bronze door, still sealed after centuries, hinting at untold treasure within.',
      icon: '🔒',
      hasShop: false,
      encounterPrompt: 'A colossal bronze door embedded in a wall, covered in barnacles but still sealed tight. Ancient lock mechanisms line the edges.',
    },
  ],

  feywild_grove: [
    {
      id: 'fg_ring',
      name: 'Faerie Ring',
      type: 'shrine',
      description: 'A perfect circle of glowing mushrooms where fey magic is strongest.',
      icon: '🍄',
      hasShop: false,
      encounterPrompt: 'A perfect circle of luminous mushrooms pulses with soft light. Stepping inside might grant a boon — or attract the attention of mischievous fey.',
    },
    {
      id: 'fg_market',
      name: "Puck's Bazaar",
      type: 'town',
      description: 'A floating market run by fey merchants who deal in favors as much as coin.',
      icon: '🎪',
      hasShop: true,
      encounterPrompt: "A bizarre floating market where fey merchants sell wares that shift form moment to moment. Prices are strange and often paid in memories or promises.",
    },
    {
      id: 'fg_gate',
      name: 'Moonlit Arch',
      type: 'waypoint',
      description: 'A shimmering archway said to move around the grove on its own.',
      icon: '🌙',
      hasShop: false,
      encounterPrompt: 'A shimmering stone arch that seems to be in a slightly different position each time you look away. Travelers report strange visions while passing through.',
    },
    {
      id: 'fg_ruins',
      name: 'Mossy Court',
      type: 'ruins',
      description: 'The collapsed remains of an ancient fey court, now grown over with enchanted flora.',
      icon: '🌺',
      hasShop: false,
      encounterPrompt: 'Crumbled columns and broken flagstones are covered in glowing moss and impossible flowers. A sense of ancient revelry lingers in the still air.',
    },
  ],

  crystal_caves: [
    {
      id: 'cc_camp',
      name: 'Miner\'s Camp',
      type: 'town',
      description: 'A roughshod camp where crystal miners trade raw gems for supplies.',
      icon: '⛏️',
      hasShop: true,
      encounterPrompt: 'A lamp-lit camp of miners deep in the caves. They trade raw crystals for food and equipment and know every tunnel in this section.',
    },
    {
      id: 'cc_font',
      name: 'Crystal Font',
      type: 'shrine',
      description: 'A naturally occurring pool surrounded by resonating crystals.',
      icon: '💎',
      hasShop: false,
      encounterPrompt: 'A underground pool surrounded by enormous crystals that hum with arcane energy. The water glows faintly and appears to have restorative properties.',
    },
    {
      id: 'cc_bridge',
      name: 'Stone Bridge',
      type: 'waypoint',
      description: 'A natural stone bridge over a chasm, its handrails carved by ancient hands.',
      icon: '🌉',
      hasShop: false,
      encounterPrompt: 'A narrow natural bridge over a deep chasm. Carved handrails suggest it was once a main thoroughfare for an ancient civilization that lived below.',
    },
    {
      id: 'cc_sanctum',
      name: 'Resonance Sanctum',
      type: 'dungeon',
      description: 'A chamber where crystals vibrate in patterns that form ancient music.',
      icon: '🔮',
      hasShop: false,
      encounterPrompt: 'A domed chamber where countless crystals vibrate in harmonic patterns. The sound is both beautiful and unsettling, and the air crackles with arcane energy.',
    },
  ],

  bone_wastes: [
    {
      id: 'bw_outpost',
      name: 'Bone Outpost',
      type: 'town',
      description: 'A grim outpost built from giant rib bones, trading supplies for souls.',
      icon: '🏴‍☠️',
      hasShop: true,
      encounterPrompt: 'A fortified outpost built from the bones of titanic creatures. The merchants here are hardened survivors who trade in cursed relics and survival supplies.',
    },
    {
      id: 'bw_crypt',
      name: 'Wanderer\'s Crypt',
      type: 'dungeon',
      description: 'An unmarked tomb where the brave seek relics of the fallen.',
      icon: '⚰️',
      hasShop: false,
      encounterPrompt: 'An unmarked tomb whose door stands permanently ajar. The sound of something shuffling inside is constant, and old weapons are stacked by the entrance.',
    },
    {
      id: 'bw_altar',
      name: 'Spirit Altar',
      type: 'shrine',
      description: 'An obsidian altar where necromantic energies pulse day and night.',
      icon: '💀',
      hasShop: false,
      encounterPrompt: 'A black obsidian altar that pulses with a cold green light. The spirits of ancient warriors appear to be bound here, circling endlessly.',
    },
    {
      id: 'bw_ossuary',
      name: 'The Grand Ossuary',
      type: 'ruins',
      description: 'Towering walls of arranged bones — a monument to some ancient battle.',
      icon: '🦴',
      hasShop: false,
      encounterPrompt: 'An enormous structure built entirely from arranged bones, reaching dozens of feet high. Inscriptions in a dead language line the base.',
    },
  ],

  scorched_wastes: [
    {
      id: 'sw_oasis',
      name: 'Mirestone Oasis',
      type: 'town',
      description: 'A precious watering hole surrounded by desperate travelers and opportunistic traders.',
      icon: '🌴',
      hasShop: true,
      encounterPrompt: 'A precious oasis in the burning desert. Merchants charge outrageous prices for water and shade, knowing travelers have no choice but to pay.',
    },
    {
      id: 'sw_ruin',
      name: 'Scorched Temple',
      type: 'ruins',
      description: 'The blackened husk of a temple that burned so long ago even the stone looks charred.',
      icon: '🏛️',
      hasShop: false,
      encounterPrompt: 'A temple so thoroughly burned that even the stone has blackened and cracked. Strange fire elementals seem drawn to the site, treating it as holy ground.',
    },
    {
      id: 'sw_shrine',
      name: 'Ember Shrine',
      type: 'shrine',
      description: 'A flame that never goes out, tended by a fire cult.',
      icon: '🔥',
      hasShop: false,
      encounterPrompt: 'An eternal flame burning atop a stone plinth in the middle of the desert. A silent cult of fire worshippers maintains a respectful vigil around it.',
    },
    {
      id: 'sw_waypost',
      name: 'Desert Waypost',
      type: 'waypoint',
      description: 'A sun-bleached post marking the edge of surveyed territory.',
      icon: '🪧',
      hasShop: false,
      encounterPrompt: 'A bleached wooden post half-buried in the sand. Old carvings mark distances to places that may no longer exist, and sun-dried bones lie at its base.',
    },
  ],

  frozen_peaks: [
    {
      id: 'fp_lodge',
      name: 'Storm Lodge',
      type: 'town',
      description: 'A stone lodge carved into the mountainside, refuge against deadly blizzards.',
      icon: '🏔️',
      hasShop: true,
      encounterPrompt: 'A squat stone lodge dug into the mountainside, its chimney belching smoke against the howling wind. Frostbitten travelers trade furs and survival gear inside.',
    },
    {
      id: 'fp_shrine',
      name: 'Ice Shrine',
      type: 'shrine',
      description: 'A shrine made of ice that never melts, glowing with inner blue light.',
      icon: '❄️',
      hasShop: false,
      encounterPrompt: 'A shrine carved from a single enormous block of ice that never melts despite the proximity of fires. Blue light emanates from within and prayers left here freeze mid-air.',
    },
    {
      id: 'fp_wreck',
      name: 'Frozen Wreck',
      type: 'ruins',
      description: 'A merchant caravan frozen solid in the ice, abandoned mid-journey.',
      icon: '🛷',
      hasShop: false,
      encounterPrompt: 'An entire merchant caravan frozen solid in the glacial ice, wagons and horses and drivers all perfectly preserved. Their cargo is visible through the ice.',
    },
    {
      id: 'fp_cairn',
      name: 'Summit Cairn',
      type: 'waypoint',
      description: 'A towering stack of stones marking the highest safe passage point.',
      icon: '🗿',
      hasShop: false,
      encounterPrompt: 'A massive cairn built over centuries by passing travelers. Each stone represents someone who survived the crossing. A small leather journal is wedged into a crack.',
    },
  ],

  volcanic_forge: [
    {
      id: 'vf_forge',
      name: "Ironblood Forge",
      type: 'town',
      description: 'A legendary dwarven forge still operational, run by a lone craftsman.',
      icon: '🔨',
      hasShop: true,
      encounterPrompt: "An ancient dwarven forge still blazing with volcanic heat. A lone craftsman of unknown age tends it, selling masterwork items at prices that seem almost too fair.",
    },
    {
      id: 'vf_shrine',
      name: 'Magma Shrine',
      type: 'shrine',
      description: 'A shrine to the dwarven forge-god, built into the caldera wall itself.',
      icon: '⚡',
      hasShop: false,
      encounterPrompt: 'A shrine carved directly into the caldera wall with lava flowing past it on both sides. Offerings of metal and gems have melted into the stone altar.',
    },
    {
      id: 'vf_ruin',
      name: 'Collapsed Workshop',
      type: 'ruins',
      description: 'The ruins of a workshop where experimental weapons were once tested.',
      icon: '💥',
      hasShop: false,
      encounterPrompt: 'A collapsed workshop surrounded by the remains of experimental constructs and half-finished weapons. Something inside the ruins is still moving.',
    },
    {
      id: 'vf_vent',
      name: 'Geyser Watch',
      type: 'waypoint',
      description: 'A platform built over a predictable geyser used as a signal point.',
      icon: '♨️',
      hasShop: false,
      encounterPrompt: 'A stone platform built over a regularly erupting geyser. Ancient dwarven inscriptions describe its eruption schedule, and it is used as a timing reference.',
    },
  ],

  dragons_spine: [
    {
      id: 'ds_hoard',
      name: "Dragon's Antechamber",
      type: 'dungeon',
      description: 'The outer chamber of a dragon lair, littered with bones and coins.',
      icon: '🐉',
      hasShop: false,
      encounterPrompt: "The outermost chamber of a dragon's lair. Bones of previous visitors crunch underfoot and scattered coins suggest the main hoard lies deeper within.",
    },
    {
      id: 'ds_cache',
      name: 'Dragonkin Camp',
      type: 'town',
      description: 'A fortified camp where dragonkin traders exchange draconic lore for supplies.',
      icon: '🏴',
      hasShop: true,
      encounterPrompt: 'A fortified camp of dragonkin who have made a truce with travelers. They trade in draconic artifacts, scales, and lore in exchange for food and metal goods.',
    },
    {
      id: 'ds_shrine',
      name: 'Draconic Altar',
      type: 'shrine',
      description: 'An ancient altar where dragonkin make offerings to their dragon overlords.',
      icon: '🔴',
      hasShop: false,
      encounterPrompt: 'A massive stone altar covered in dried blood and dragon scales. Draconic runes of power are etched across its surface, and the air hums with ancient magic.',
    },
    {
      id: 'ds_spire',
      name: 'Wyrm Watch',
      type: 'waypoint',
      description: 'A lookout spire used to spot flying wyrms before they spot you.',
      icon: '🗼',
      hasShop: false,
      encounterPrompt: 'A high stone spire with a small lookout platform at the top. It provides an excellent view of the ridge and any dragons currently hunting in the area.',
    },
  ],

  shadow_realm: [
    {
      id: 'shr_anchor',
      name: 'Reality Anchor',
      type: 'shrine',
      description: 'A beacon of light that keeps a small area stable in the shifting realm.',
      icon: '💡',
      hasShop: false,
      encounterPrompt: 'A pulsing beacon of warm light in the shifting darkness. Standing near it keeps the ground solid and the shadows at bay, but something in the dark is drawn to it.',
    },
    {
      id: 'shr_market',
      name: 'Void Market',
      type: 'town',
      description: 'A shimmering market staffed by shadow merchants who sell cursed but powerful wares.',
      icon: '🌑',
      hasShop: true,
      encounterPrompt: 'A surreal market that flickers in and out of reality. Shadow merchants sell items that cast no reflection, speaking in whispers about prices paid in memories.',
    },
    {
      id: 'shr_portal',
      name: 'Broken Portal',
      type: 'ruins',
      description: 'A portal frame whose destination is unknown — and perhaps unknowable.',
      icon: '🌀',
      hasShop: false,
      encounterPrompt: 'A massive stone portal frame that crackles with unstable dimensional energy. Where it leads, if anywhere, is unclear, and figures can sometimes be seen on the other side.',
    },
    {
      id: 'shr_spire',
      name: 'Obsidian Spire',
      type: 'dungeon',
      description: 'A tower of black glass that seems to absorb light and sound alike.',
      icon: '🖤',
      hasShop: false,
      encounterPrompt: 'A smooth black tower that absorbs all light and sound. No echoes emanate from it and the door opens inward to total darkness.',
    },
  ],

  sky_citadel: [
    {
      id: 'sc_outpost',
      name: 'Cloud Outpost',
      type: 'town',
      description: 'A trading outpost built on a floating cloud platform.',
      icon: '☁️',
      hasShop: true,
      encounterPrompt: 'A trading post built atop a magically solid cloud. Sky merchants trade in rare aerial components and the view from here is breathtaking — and terrifying.',
    },
    {
      id: 'sc_shrine',
      name: 'Wind Altar',
      type: 'shrine',
      description: 'An altar where the wind is said to carry prayers directly to the gods.',
      icon: '🌬️',
      hasShop: false,
      encounterPrompt: 'An open-air altar battered by constant wind. The offerings left here are simple — feathers, ribbons, whispers — things light enough to be carried skyward.',
    },
    {
      id: 'sc_ruin',
      name: 'Fallen Battlement',
      type: 'ruins',
      description: 'A section of the old citadel that has partially crumbled away, teetering on the edge.',
      icon: '🏛️',
      hasShop: false,
      encounterPrompt: 'A section of ancient battlement that juts over open sky, held in place by nothing obvious. Ancient war machines are still mounted on it, surprisingly intact.',
    },
    {
      id: 'sc_waypoint',
      name: 'Navigation Beacon',
      type: 'waypoint',
      description: 'A magical beacon used by sky-farers to navigate the floating fortress.',
      icon: '🔦',
      hasShop: false,
      encounterPrompt: 'A rotating magical beacon that projects a beam of light visible for miles. Its patterns encode navigation information for those who know how to read them.',
    },
  ],

  abyssal_depths: [
    {
      id: 'ad_station',
      name: 'Pressure Station',
      type: 'town',
      description: 'An ancient deep-sea station maintained by mysterious scholars.',
      icon: '🔭',
      hasShop: true,
      encounterPrompt: 'A watertight station of unknown origin staffed by robed scholars who seem unaffected by the crushing pressure. They trade knowledge and strange artifacts.',
    },
    {
      id: 'ad_biolumen',
      name: 'Bioluminescent Grotto',
      type: 'shrine',
      description: 'A grotto lit by living light — sea creatures that form patterns of prophecy.',
      icon: '🦑',
      hasShop: false,
      encounterPrompt: 'A grotto filled with bioluminescent creatures that arrange themselves into patterns. Those with prophetic sensitivity can read omens in their shifting formations.',
    },
    {
      id: 'ad_fortress',
      name: 'Sunken Fortress',
      type: 'dungeon',
      description: 'An ancient fortress that sank fully intact, preserving its terrible guardians.',
      icon: '🏰',
      hasShop: false,
      encounterPrompt: 'An enormous fortress resting perfectly upright on the ocean floor. Every room is flooded but the structure is intact, and its original guardians still patrol the halls.',
    },
    {
      id: 'ad_vent',
      name: 'Hydrothermal Shrine',
      type: 'shrine',
      description: 'Massive thermal vents surrounded by adapted life forms that glow in the dark.',
      icon: '🌊',
      hasShop: false,
      encounterPrompt: 'Thermal vents surrounded by strange life adapted to the extreme depths. Creatures here are blind but highly attuned to other senses, and seem aware of your presence.',
    },
  ],

  celestial_throne: [
    {
      id: 'ct_spire',
      name: 'Celestial Wayspire',
      type: 'waypoint',
      description: 'A spire of crystallized divine energy marking the path through the realm.',
      icon: '✨',
      hasShop: false,
      encounterPrompt: 'A towering spire of crystallized divine energy. Its light is so pure it feels like a physical pressure, and divine beings give it a wide berth.',
    },
    {
      id: 'ct_court',
      name: "Fallen Court",
      type: 'ruins',
      description: 'The ruins of a divine court where gods once held council.',
      icon: '👑',
      hasShop: false,
      encounterPrompt: 'Crumbled thrones and shattered pillars hint at a council chamber of immense power. The lingering divine energy makes the air buzz and static spark from fingertips.',
    },
    {
      id: 'ct_reliquary',
      name: 'Divine Reliquary',
      type: 'town',
      description: 'A celestial market tended by minor divinities who trade in blessings.',
      icon: '🌟',
      hasShop: true,
      encounterPrompt: 'A market tended by minor divine beings who trade in blessings, sacred relics, and divine contracts. The prices are steep but the goods are unlike anything found below.',
    },
    {
      id: 'ct_altar',
      name: 'Ascension Altar',
      type: 'shrine',
      description: 'The altar where mortals who achieved apotheosis were transformed.',
      icon: '🌠',
      hasShop: false,
      encounterPrompt: 'A massive white altar stained with the radiance of ascended mortals. The names of those who transcended mortality are etched into its base in languages no longer spoken.',
    },
    {
      id: 'ct_vault',
      name: 'Forbidden Vault',
      type: 'dungeon',
      description: 'A sealed vault containing things the gods decided mortals must never see.',
      icon: '🔐',
      hasShop: false,
      encounterPrompt: 'A sealed vault covered in divine warnings in a thousand languages. The seals glow red-hot and the door itself seems to breathe, as if something inside pushes against it.',
    },
  ],
}

const GENERIC_LANDMARKS: LandmarkTemplate[] = [
  {
    id: 'generic-waypoint',
    name: 'Lonely Waypost',
    type: 'waypoint',
    description: 'A weathered signpost marks a crossroads.',
    icon: '🪧',
    hasShop: false,
    encounterPrompt: 'An old waypost in the wilderness. Carved directions point to places long since abandoned, and travelers have added their own marks over the centuries.',
  },
  {
    id: 'generic-shrine',
    name: 'Roadside Shrine',
    type: 'shrine',
    description: 'A small shrine to forgotten gods.',
    icon: '⛩️',
    hasShop: false,
    encounterPrompt: 'A crumbling shrine with faded offerings and half-legible prayers etched into the stone. Whatever god was worshipped here, their name has been worn away by time.',
  },
  {
    id: 'generic-camp',
    name: 'Merchant Camp',
    type: 'town',
    description: 'A traveling merchant has set up camp.',
    icon: '🏕️',
    hasShop: true,
    encounterPrompt: 'A well-stocked merchant camp on the roadside. The merchant is friendly but wary, keeping a hand near a hidden weapon while making small talk.',
  },
]

export function getTemplatesForRegion(regionId: string): LandmarkTemplate[] {
  return LANDMARK_TEMPLATES[regionId] ?? GENERIC_LANDMARKS
}

export const SECRET_LANDMARK_TEMPLATES: Record<string, LandmarkTemplate[]> = {
  hearthwood: [
    { id: 'sv_hidden_cellar', name: 'Hidden Cellar', type: 'dungeon', description: 'A concealed entrance beneath the cobblestones leads to a forgotten cellar.', icon: '🕳️', hasShop: false, encounterPrompt: 'A damp cellar filled with old crates and cobwebs. Something glints in the darkness.', isSecret: true },
  ],
  green_meadows: [
    { id: 'gm_fairy_ring', name: 'Fairy Ring', type: 'shrine', description: 'A circle of glowing mushrooms hidden in a meadow hollow.', icon: '🍄', hasShop: false, encounterPrompt: 'A ring of luminescent mushrooms pulses with fey energy. Tiny lights dance above the circle.', isSecret: true },
  ],
  dark_forest: [
    { id: 'df_shadow_grotto', name: 'Shadow Grotto', type: 'dungeon', description: 'A cave entrance concealed by twisted roots and perpetual shadow.', icon: '🕸️', hasShop: false, encounterPrompt: 'A grotto shrouded in unnatural darkness. Strange whispers echo from within.', isSecret: true },
  ],
  crystal_caves: [
    { id: 'cc_resonance_chamber', name: 'Resonance Chamber', type: 'shrine', description: 'A hidden chamber where crystals sing in perfect harmony.', icon: '🔮', hasShop: false, encounterPrompt: 'A vast chamber where crystals of every color resonate with harmonic energy. The air hums.', isSecret: true },
  ],
  sunken_ruins: [
    { id: 'sr_drowned_vault', name: 'Drowned Vault', type: 'dungeon', description: 'A sealed vault deep beneath the flooded ruins.', icon: '🗝️', hasShop: false, encounterPrompt: 'An ancient vault sealed by water pressure. Inside, preserved treasures await.', isSecret: true },
  ],
  scorched_wastes: [
    { id: 'sw_ember_sanctum', name: 'Ember Sanctum', type: 'shrine', description: 'A hidden temple where eternal flames guard ancient secrets.', icon: '🕯️', hasShop: false, encounterPrompt: 'A sanctum of eternal flames. Fire spirits dance between the pillars.', isSecret: true },
  ],
  frozen_peaks: [
    { id: 'fp_ice_throne', name: 'Ice Throne', type: 'ruins', description: 'A frozen throne room sealed beneath the glacial ice.', icon: '🧊', hasShop: false, encounterPrompt: 'A throne of pure ice sits in a frozen chamber. An ancient power lingers here.', isSecret: true },
  ],
  feywild_grove: [
    { id: 'fg_dream_pool', name: 'Dream Pool', type: 'shrine', description: 'A pool of liquid starlight hidden among the fey trees.', icon: '✨', hasShop: false, encounterPrompt: 'A pool of shimmering liquid starlight. Looking into it shows visions of other worlds.', isSecret: true },
  ],
  bone_wastes: [
    { id: 'bw_ossuary', name: 'The Ossuary', type: 'dungeon', description: 'A hidden chamber of carefully arranged bones and dark rituals.', icon: '💀', hasShop: false, encounterPrompt: 'A chamber where bones are arranged in intricate patterns. Necromantic energy pulses.', isSecret: true },
  ],
  volcanic_forge: [
    { id: 'vf_heart_of_fire', name: 'Heart of Fire', type: 'shrine', description: 'The molten core of the volcano, where the original forge still burns.', icon: '❤️‍🔥', hasShop: false, encounterPrompt: 'The primordial forge at the heart of the volcano. Ancient weapons and armor glow white-hot.', isSecret: true },
  ],
  shadow_realm: [
    { id: 'shr_void_nexus', name: 'Void Nexus', type: 'ruins', description: 'A tear in reality where shadow and void converge.', icon: '🌀', hasShop: false, encounterPrompt: 'A nexus of swirling void energy. Reality bends and shifts around you.', isSecret: true },
  ],
  dragons_spine: [
    { id: 'ds_elder_hoard', name: "Elder Dragon's Hoard", type: 'dungeon', description: 'A legendary treasure vault guarded by the eldest dragon.', icon: '🐲', hasShop: false, encounterPrompt: "Mountains of gold and artifacts fill this vast cavern. The elder dragon's presence is overwhelming.", isSecret: true },
  ],
  sky_citadel: [
    { id: 'sc_astral_library', name: 'Astral Library', type: 'shrine', description: 'A library containing knowledge from across the planes.', icon: '📚', hasShop: false, encounterPrompt: 'Books float in the air, pages turning on their own. The collected knowledge of the cosmos awaits.', isSecret: true },
  ],
  abyssal_depths: [
    { id: 'ad_leviathan_lair', name: "Leviathan's Lair", type: 'dungeon', description: 'The resting place of an ancient sea god.', icon: '🐙', hasShop: false, encounterPrompt: 'A massive underwater cavern where something impossibly large sleeps. Ancient power radiates from the depths.', isSecret: true },
  ],
  celestial_throne: [
    { id: 'ct_genesis_chamber', name: 'Genesis Chamber', type: 'shrine', description: 'The chamber where gods shaped the world.', icon: '⚡', hasShop: false, encounterPrompt: 'A chamber of pure light where creation itself began. Divine energy is overwhelming.', isSecret: true },
  ],
}

export function getSecretTemplatesForRegion(regionId: string): LandmarkTemplate[] {
  return SECRET_LANDMARK_TEMPLATES[regionId] ?? []
}
