import { SpellElement } from '@/app/tap-tap-adventure/models/spell'

export type RegionDifficulty = 'easy' | 'medium' | 'hard' | 'very_hard' | 'extreme'

export interface Region {
  id: string
  name: string
  description: string
  difficulty: RegionDifficulty
  difficultyMultiplier: number
  theme: string
  enemyTypes: string[]
  element: SpellElement
  connectedRegions: string[]
  minLevel: number
  icon: string
  startingCombatDistance?: 'close' | 'mid' | 'far'
  /** Parent region in the world tree (undefined for root or convergence hubs) */
  parentRegion?: string
  /** Child regions branching from this node */
  childRegions?: string[]
  bounds?: { width: number; height: number }
  isDeadEnd?: boolean
}

export const REGIONS: Record<string, Region> = {
  green_meadows: {
    id: 'green_meadows',
    name: 'Green Meadows',
    description: 'Rolling hills dotted with wildflowers and gentle streams. A good place for new adventurers.',
    difficulty: 'easy',
    difficultyMultiplier: 0.8,
    theme: 'rolling green hills, wildflower meadows, gentle streams, and scattered farmsteads',
    enemyTypes: ['wolves', 'bandits', 'wild boars'],
    element: 'nature',
    connectedRegions: ['dark_forest', 'sunken_ruins'],
    minLevel: 0,
    icon: '\u{1F33F}',
    startingCombatDistance: 'far',
    childRegions: ['dark_forest', 'sunken_ruins'],
    bounds: { width: 500, height: 500 },
  },
  dark_forest: {
    id: 'dark_forest',
    name: 'Dark Forest',
    description: 'Dense, ancient woods where sunlight barely reaches the floor. Strange creatures lurk in the shadows.',
    difficulty: 'medium',
    difficultyMultiplier: 1.0,
    theme: 'dense dark woods, twisted trees, thick fog, and eerie silence',
    enemyTypes: ['shadow beasts', 'giant spiders', 'corrupted treants'],
    element: 'shadow',
    connectedRegions: ['green_meadows', 'feywild_grove', 'abandoned_mine'],
    minLevel: 1,
    icon: '\u{1F332}',
    startingCombatDistance: 'close',
    parentRegion: 'green_meadows',
    childRegions: ['feywild_grove', 'abandoned_mine'],
    bounds: { width: 500, height: 500 },
  },
  crystal_caves: {
    id: 'crystal_caves',
    name: 'Crystal Caves',
    description: 'A vast underground network of glittering caverns filled with magical crystals and ancient secrets.',
    difficulty: 'medium',
    difficultyMultiplier: 1.1,
    theme: 'underground caverns, glowing crystals, echoing tunnels, and underground rivers',
    enemyTypes: ['crystal golems', 'cave bats', 'gem serpents'],
    element: 'arcane',
    connectedRegions: ['sunken_ruins', 'bone_wastes', 'forgotten_temple'],
    minLevel: 3,
    icon: '\u{1F48E}',
    startingCombatDistance: 'close',
    parentRegion: 'sunken_ruins',
    childRegions: ['bone_wastes', 'forgotten_temple'],
    bounds: { width: 500, height: 500 },
  },
  scorched_wastes: {
    id: 'scorched_wastes',
    name: 'Scorched Wastes',
    description: 'A barren desert of cracked earth and ancient ruins, baked under a merciless sun.',
    difficulty: 'hard',
    difficultyMultiplier: 1.5,
    theme: 'scorching desert, ancient ruins, sand dunes, and volcanic vents',
    enemyTypes: ['fire elementals', 'sand wyrms', 'scorpion warriors'],
    element: 'fire',
    connectedRegions: ['bone_wastes', 'volcanic_forge'],
    minLevel: 5,
    icon: '\u{1F525}',
    startingCombatDistance: 'far',
    parentRegion: 'bone_wastes',
    childRegions: ['volcanic_forge'],
    bounds: { width: 500, height: 500 },
  },
  frozen_peaks: {
    id: 'frozen_peaks',
    name: 'Frozen Peaks',
    description: 'Towering snow-capped mountains battered by howling blizzards. Only the hardiest survive.',
    difficulty: 'hard',
    difficultyMultiplier: 1.5,
    theme: 'snow-capped mountains, howling blizzards, frozen lakes, and ice caverns',
    enemyTypes: ['ice wraiths', 'frost giants', 'snow wolves'],
    element: 'ice',
    connectedRegions: ['bone_wastes', 'shadow_realm'],
    minLevel: 5,
    icon: '\u{2744}\u{FE0F}',
    startingCombatDistance: 'far',
    parentRegion: 'bone_wastes',
    childRegions: ['shadow_realm'],
    bounds: { width: 500, height: 500 },
  },
  shadow_realm: {
    id: 'shadow_realm',
    name: 'Shadow Realm',
    description: 'A dark dimension where reality warps and nightmares walk. Only the bravest dare enter.',
    difficulty: 'very_hard',
    difficultyMultiplier: 1.9,
    theme: 'dark otherworldly dimension, floating islands of shadow, warped reality, and nightmare landscapes',
    enemyTypes: ['demons', 'undead knights', 'shadow dragons'],
    element: 'shadow',
    connectedRegions: ['frozen_peaks', 'dragons_spine'],
    minLevel: 6,
    icon: '\u{1F311}',
    startingCombatDistance: 'close',
    parentRegion: 'frozen_peaks',
    childRegions: ['dragons_spine'],
    bounds: { width: 500, height: 500 },
  },
  sky_citadel: {
    id: 'sky_citadel',
    name: 'Sky Citadel',
    description: 'A massive floating fortress high above the clouds. The ultimate challenge for legendary adventurers.',
    difficulty: 'very_hard',
    difficultyMultiplier: 2.2,
    theme: 'floating fortress in the sky, ancient arcane machinery, cloud platforms, and celestial architecture',
    enemyTypes: ['sky knights', 'ancient dragons', 'arcane sentinels'],
    element: 'arcane',
    connectedRegions: ['dragons_spine', 'abyssal_depths'],
    minLevel: 8,
    icon: '\u{26C5}',
    startingCombatDistance: 'mid',
    parentRegion: 'dragons_spine',
    childRegions: ['abyssal_depths'],
    bounds: { width: 500, height: 500 },
  },
  abyssal_depths: {
    id: 'abyssal_depths',
    name: 'Abyssal Depths',
    description: 'A crushing ocean abyss where bioluminescent nightmares dwell in ancient sunken fortresses. Few who descend ever return.',
    difficulty: 'very_hard',
    difficultyMultiplier: 2.4,
    theme: 'crushing ocean abyss, bioluminescent nightmares, ancient sunken fortresses, and tentacled void creatures',
    enemyTypes: ['abyssal horrors', 'drowned titans', 'void krakens'],
    element: 'shadow',
    connectedRegions: ['sky_citadel', 'celestial_throne'],
    minLevel: 10,
    icon: '\u{1F30A}',
    startingCombatDistance: 'mid',
    parentRegion: 'sky_citadel',
    childRegions: ['celestial_throne'],
    bounds: { width: 500, height: 500 },
  },
  celestial_throne: {
    id: 'celestial_throne',
    name: 'Celestial Throne',
    description: 'The realm of the gods itself — blinding white spires and floating celestial islands where divine beings of immense power hold dominion.',
    difficulty: 'extreme',
    difficultyMultiplier: 2.8,
    theme: 'realm of the gods, blinding white spires, floating celestial islands, and divine beings of immense power',
    enemyTypes: ['divine sentinels', 'celestial wyrms', 'corrupted archangels'],
    element: 'arcane',
    connectedRegions: ['abyssal_depths'],
    minLevel: 12,
    icon: '\u2728',
    startingCombatDistance: 'far',
    parentRegion: 'abyssal_depths',
    bounds: { width: 500, height: 500 },
  },
  sunken_ruins: {
    id: 'sunken_ruins',
    name: 'Sunken Ruins',
    description: 'Half-submerged ancient temples where coral-encrusted pillars rise from the depths. Bioluminescent creatures light the flooded halls.',
    difficulty: 'medium',
    difficultyMultiplier: 1.0,
    theme: 'half-submerged ancient temples, coral-encrusted pillars, underwater currents, and bioluminescent sea creatures',
    enemyTypes: ['sea serpents', 'drowned pirates', 'coral golems'],
    element: 'ice',
    connectedRegions: ['green_meadows', 'crystal_caves', 'pirates_cove'],
    minLevel: 2,
    icon: '\u{1F3DB}\u{FE0F}',
    startingCombatDistance: 'mid',
    parentRegion: 'green_meadows',
    childRegions: ['crystal_caves', 'pirates_cove'],
    bounds: { width: 500, height: 500 },
  },
  volcanic_forge: {
    id: 'volcanic_forge',
    name: 'Volcanic Forge',
    description: 'An active volcanic caldera housing ancient dwarven forges. Rivers of lava flow between obsidian spires and geysers of molten rock.',
    difficulty: 'hard',
    difficultyMultiplier: 1.7,
    theme: 'active volcanic caldera with rivers of lava, ancient dwarven forges, obsidian spires, and geysers of molten rock',
    enemyTypes: ['lava elementals', 'forge golems', 'magma serpents'],
    element: 'fire',
    connectedRegions: ['scorched_wastes', 'dragons_spine'],
    minLevel: 6,
    icon: '\u{1F30B}',
    startingCombatDistance: 'close',
    parentRegion: 'scorched_wastes',
    childRegions: ['dragons_spine'],
    bounds: { width: 500, height: 500 },
  },
  feywild_grove: {
    id: 'feywild_grove',
    name: 'Feywild Grove',
    description: 'An enchanted forest where reality bends. Giant mushrooms glow with fairy light, time flows strangely, and mischievous fey creatures play tricks.',
    difficulty: 'medium',
    difficultyMultiplier: 1.2,
    theme: 'enchanted forest where reality bends, giant mushrooms glow with fairy light, time flows strangely, and mischievous fey creatures play tricks',
    enemyTypes: ['fey tricksters', 'enchanted treants', 'pixie swarms'],
    element: 'nature',
    connectedRegions: ['dark_forest', 'bone_wastes', 'witchs_hollow'],
    minLevel: 3,
    icon: '\u{1F344}',
    startingCombatDistance: 'mid',
    parentRegion: 'dark_forest',
    childRegions: ['bone_wastes', 'witchs_hollow'],
    bounds: { width: 500, height: 500 },
  },
  bone_wastes: {
    id: 'bone_wastes',
    name: 'Bone Wastes',
    description: 'A desolate graveyard of ancient leviathans. Bleached bones tower like buildings while restless spirits wander and necromantic energy pulses through the ground.',
    difficulty: 'hard',
    difficultyMultiplier: 1.3,
    theme: 'desolate graveyard of ancient leviathans, bleached bones tower like buildings, restless spirits wander, and necromantic energy pulses through the ground',
    enemyTypes: ['skeleton warriors', 'bone dragons', 'wraith lords'],
    element: 'shadow',
    connectedRegions: ['feywild_grove', 'crystal_caves', 'scorched_wastes', 'frozen_peaks'],
    minLevel: 4,
    icon: '\u{1F480}',
    startingCombatDistance: 'mid',
    childRegions: ['scorched_wastes', 'frozen_peaks'],
    bounds: { width: 500, height: 500 },
  },
  dragons_spine: {
    id: 'dragons_spine',
    name: "Dragon's Spine",
    description: 'A jagged mountain ridge carved by dragon claws, filled with ancient dragon lairs, treasure hoards, volcanic vents, and the bones of fallen heroes.',
    difficulty: 'very_hard',
    difficultyMultiplier: 2.0,
    theme: 'jagged mountain ridge carved by dragon claws, ancient dragon lairs filled with treasure hoards, volcanic vents, and the bones of fallen heroes',
    enemyTypes: ['young dragons', 'dragonkin warriors', 'wyverns'],
    element: 'fire',
    connectedRegions: ['volcanic_forge', 'shadow_realm', 'sky_citadel'],
    minLevel: 7,
    icon: '\u{1F409}',
    startingCombatDistance: 'far',
    childRegions: ['sky_citadel'],
    bounds: { width: 500, height: 500 },
  },
  abandoned_mine: {
    id: 'abandoned_mine',
    name: 'Abandoned Mine',
    description: 'A collapsed mine filled with forgotten treasures and cave-dwelling creatures. There is no way forward — only back.',
    difficulty: 'medium',
    difficultyMultiplier: 1.2,
    theme: 'collapsed mine tunnels, glittering ore veins, abandoned mining equipment, cave-dwelling creatures guarding forgotten treasures',
    enemyTypes: ['cave spiders', 'rock golems', 'mine wraiths'],
    element: 'nature',
    connectedRegions: ['dark_forest'],
    minLevel: 2,
    icon: '⛏️',
    parentRegion: 'dark_forest',
    isDeadEnd: true,
    bounds: { width: 300, height: 300 },
  },
  witchs_hollow: {
    id: 'witchs_hollow',
    name: "Witch's Hollow",
    description: 'A hidden glade where a powerful witch once practiced forbidden magic. Rare spell components litter the ground. No path leads onward.',
    difficulty: 'hard',
    difficultyMultiplier: 1.4,
    theme: 'enchanted hollow with bubbling cauldrons, spell circles etched in stone, rare magical herbs, and lingering arcane energy',
    enemyTypes: ['hex beasts', 'animated scarecrows', 'potion slimes'],
    element: 'arcane',
    connectedRegions: ['feywild_grove'],
    minLevel: 4,
    icon: '🧙',
    parentRegion: 'feywild_grove',
    isDeadEnd: true,
    bounds: { width: 300, height: 300 },
  },
  forgotten_temple: {
    id: 'forgotten_temple',
    name: 'Forgotten Temple',
    description: 'An ancient temple buried beneath crystal formations. Sacred relics and dangerous guardians await. The only exit is the way you came.',
    difficulty: 'hard',
    difficultyMultiplier: 1.3,
    theme: 'crystal-encrusted temple ruins with sacred altars, puzzle mechanisms, divine relics, and ancient guardians',
    enemyTypes: ['temple guardians', 'crystal sentinels', 'divine wraiths'],
    element: 'nature',
    connectedRegions: ['crystal_caves'],
    minLevel: 4,
    icon: '🏛️',
    parentRegion: 'crystal_caves',
    isDeadEnd: true,
    bounds: { width: 300, height: 300 },
  },
  pirates_cove: {
    id: 'pirates_cove',
    name: "Pirate's Cove",
    description: 'A hidden coastal cave where pirates once stashed their plunder. Treasure chests and booby traps abound. The tide blocks any forward passage.',
    difficulty: 'medium',
    difficultyMultiplier: 1.1,
    theme: 'hidden coastal cave with treasure chests, old pirate ships, booby traps, seagulls, and the sound of crashing waves',
    enemyTypes: ['ghost pirates', 'giant crabs', 'sea serpents'],
    element: 'ice',
    connectedRegions: ['sunken_ruins'],
    minLevel: 3,
    icon: '🏴‍☠️',
    parentRegion: 'sunken_ruins',
    isDeadEnd: true,
    bounds: { width: 300, height: 300 },
  },
}

export function getRegion(regionId: string): Region {
  return REGIONS[regionId] ?? REGIONS.green_meadows
}

export function getConnectedRegions(regionId: string): Region[] {
  const region = getRegion(regionId)
  return region.connectedRegions.map(id => getRegion(id))
}

export function canEnterRegion(region: Region, characterLevel: number): boolean {
  return characterLevel >= region.minLevel
}

export const CROSSROADS_INTERVAL = 75
