import { Skill } from '@/app/tap-tap-adventure/models/skill'

export const SKILLS: Skill[] = [
  // ===== Combat Skills =====
  {
    id: 'iron_fist',
    name: 'Iron Fist',
    description: '+2 attack power',
    icon: '\u{1F44A}',
    category: 'combat',
    effect: { type: 'flat_bonus', target: 'attack', value: 2 },
    requirement: { type: 'combats_won', value: 10 },
  },
  {
    id: 'thick_skin',
    name: 'Thick Skin',
    description: '+10% max HP',
    icon: '\u{1F6E1}\u{FE0F}',
    category: 'combat',
    effect: { type: 'percentage_bonus', target: 'maxHp', value: 10 },
    requirement: { type: 'achievement', value: 'special_survivor' },
  },
  {
    id: 'quick_reflexes',
    name: 'Quick Reflexes',
    description: '+10% flee chance',
    icon: '\u{1F4A8}',
    category: 'combat',
    effect: { type: 'percentage_bonus', target: 'flee_chance', value: 10 },
    requirement: { type: 'achievement', value: 'combat_untouchable' },
  },
  {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Combo builds 25% faster',
    icon: '\u{26A1}',
    category: 'combat',
    effect: { type: 'special', target: 'combo_rate', value: 0.05 },
    requirement: { type: 'combats_won', value: 5 },
  },
  {
    id: 'spell_affinity',
    name: 'Spell Affinity',
    description: '-15% spell mana cost',
    icon: '\u{2728}',
    category: 'combat',
    effect: { type: 'percentage_bonus', target: 'spell_cost', value: 15 },
    requirement: { type: 'achievement', value: 'collection_spell_scholar' },
  },

  // ===== Survival Skills =====
  {
    id: 'regeneration',
    name: 'Regeneration',
    description: 'Heal 1 extra HP per heal tick',
    icon: '\u{1F49A}',
    category: 'survival',
    effect: { type: 'flat_bonus', target: 'heal_rate', value: 1 },
    requirement: { type: 'distance', value: 500 },
  },
  {
    id: 'mana_well',
    name: 'Mana Well',
    description: '+20% max mana',
    icon: '\u{1F48E}',
    category: 'survival',
    effect: { type: 'percentage_bonus', target: 'maxMana', value: 20 },
    requirement: { type: 'level', value: 3 },
  },
  {
    id: 'last_stand',
    name: 'Last Stand',
    description: '+50% damage when HP below 25%',
    icon: '\u{1F525}',
    category: 'survival',
    effect: { type: 'special', target: 'damage_low_hp', value: 50 },
    requirement: { type: 'achievement', value: 'special_death_defier' },
  },
  {
    id: 'poison_resist',
    name: 'Poison Resist',
    description: '50% chance to resist poison',
    icon: '\u{1F9EA}',
    category: 'survival',
    effect: { type: 'special', target: 'poison_resist', value: 50 },
    requirement: { type: 'combats_won', value: 15 },
  },

  // ===== Utility Skills =====
  {
    id: 'haggler',
    name: 'Haggler',
    description: '15% shop discount',
    icon: '\u{1F4B0}',
    category: 'utility',
    effect: { type: 'percentage_bonus', target: 'shop_discount', value: 15 },
    requirement: { type: 'achievement', value: 'special_shopkeeper_friend' },
  },
  {
    id: 'scavenger',
    name: 'Scavenger',
    description: '+20% loot drop chance',
    icon: '\u{1F392}',
    category: 'utility',
    effect: { type: 'percentage_bonus', target: 'loot_chance', value: 20 },
    requirement: { type: 'achievement', value: 'collection_collector' },
  },
  {
    id: 'gold_finder',
    name: 'Gold Finder',
    description: '+25% gold from combat',
    icon: '\u{1FA99}',
    category: 'utility',
    effect: { type: 'percentage_bonus', target: 'gold_bonus', value: 25 },
    requirement: { type: 'achievement', value: 'progression_rich' },
  },

  // ===== Exploration Skills =====
  {
    id: 'pathfinder',
    name: 'Pathfinder',
    description: '+50% auto-walk speed',
    icon: '\u{1F5FA}\u{FE0F}',
    category: 'exploration',
    effect: { type: 'percentage_bonus', target: 'auto_walk_speed', value: 50 },
    requirement: { type: 'distance', value: 1000 },
  },
  {
    id: 'lucky_traveler',
    name: 'Lucky Traveler',
    description: '+1 luck',
    icon: '\u{1F340}',
    category: 'exploration',
    effect: { type: 'flat_bonus', target: 'luck', value: 1 },
    requirement: { type: 'level', value: 5 },
  },
  {
    id: 'veteran',
    name: 'Veteran',
    description: '+1 to all stats',
    icon: '\u{2B50}',
    category: 'exploration',
    effect: { type: 'flat_bonus', target: 'all_stats', value: 1 },
    requirement: { type: 'level', value: 10 },
  },
]
