export type JokerEffectType = 'additiveMult' | 'additiveChips' | 'multiplicativeMult' | 'retrigger' | 'economy' | 'utility'

export const JOKER_EFFECT_TYPES: Partial<Record<string, JokerEffectType>> = {
  // Additive Mult (+M)
  jokerJoker: 'additiveMult',
  greedyJoker: 'additiveMult',
  jollyJoker: 'additiveMult',
  gluttonousJoker: 'additiveMult',
  wrathfulJoker: 'additiveMult',
  madJoker: 'additiveMult',
  crazyJoker: 'additiveMult',
  drollJoker: 'additiveMult',
  lustyJoker: 'additiveMult',
  zanyJoker: 'additiveMult',
  halfJoker: 'additiveMult',
  bootstrapsJoker: 'additiveMult',
  spareTrousersJoker: 'additiveMult',
  erosionJoker: 'additiveMult',
  shootTheMoonJoker: 'additiveMult',
  fortuneTellerJoker: 'additiveMult',
  supernovaJoker: 'additiveMult',
  abstractJokerJoker: 'additiveMult',
  smileyFaceJoker: 'additiveMult',
  evenStevenJoker: 'additiveMult',
  fibonacci: 'additiveMult',
  misprint: 'additiveMult',
  raisedFist: 'additiveMult',
  greenJoker: 'additiveMult',
  redCard: 'additiveMult',
  popcorn: 'additiveMult',
  rideTheBus: 'additiveMult',
  ceremonialDagger: 'additiveMult',
  swashbucklerJoker: 'additiveMult',
  walkieTalkieJoker: 'additiveMult',
  onyxAgateJoker: 'additiveMult',
  mysticSummit: 'additiveMult',
  scholarJoker: 'additiveMult',

  // Additive Chips (+C)
  wilyJoker: 'additiveChips',
  cleverJoker: 'additiveChips',
  deviousJoker: 'additiveChips',
  craftyJoker: 'additiveChips',
  slyJoker: 'additiveChips',
  bullJoker: 'additiveChips',
  arrowheadJoker: 'additiveChips',
  blueJokerJoker: 'additiveChips',
  oddToddJoker: 'additiveChips',
  scaryFaceJoker: 'additiveChips',
  banner: 'additiveChips',
  runner: 'additiveChips',
  squareJoker: 'additiveChips',
  iceCream: 'additiveChips',
  castle: 'additiveChips',
  stoneJokerJoker: 'additiveChips',
  stuntmanJoker: 'additiveChips',
  weeJokerJoker: 'additiveChips',

  // Multiplicative Mult (xM)
  acrobatJoker: 'multiplicativeMult',
  theTrioJoker: 'multiplicativeMult',
  theDuoJoker: 'multiplicativeMult',
  theOrderJoker: 'multiplicativeMult',
  theTribeJoker: 'multiplicativeMult',
  theFamilyJoker: 'multiplicativeMult',
  baseballCardJoker: 'multiplicativeMult',
  steelJokerJoker: 'multiplicativeMult',
  baronJoker: 'multiplicativeMult',
  seeingDoubleJoker: 'multiplicativeMult',
  flowerPotJoker: 'multiplicativeMult',
  blackboard: 'multiplicativeMult',
  cavendish: 'multiplicativeMult',
  photograph: 'multiplicativeMult',
  madness: 'multiplicativeMult',
  cardSharp: 'multiplicativeMult',
  loyaltyCard: 'multiplicativeMult',
  ramen: 'multiplicativeMult',
  bloodstone: 'multiplicativeMult',
  throwback: 'multiplicativeMult',
  constellation: 'multiplicativeMult',
  vampire: 'multiplicativeMult',
  hitTheRoad: 'multiplicativeMult',
  ancientJoker: 'multiplicativeMult',
  driversLicense: 'multiplicativeMult',
  campfire: 'multiplicativeMult',
  obelisk: 'multiplicativeMult',
  triboulet: 'multiplicativeMult',
  yorick: 'multiplicativeMult',
  canio: 'multiplicativeMult',
  glassJoker: 'multiplicativeMult',
  jokerStencil: 'multiplicativeMult',
  luckyCat: 'multiplicativeMult',
  hologram: 'multiplicativeMult',
  theIdol: 'multiplicativeMult',

  // Retrigger
  hangingChad: 'retrigger',
  hack: 'retrigger',
  seltzer: 'retrigger',
  dusk: 'retrigger',
  sockAndBuskin: 'retrigger',
  mime: 'retrigger',
  burntJoker: 'retrigger',

  // Economy ($) — no badge
  cloud9Joker: 'economy',
  goldenJokerJoker: 'economy',
  roughGemJoker: 'economy',
  egg: 'economy',
  facelessJoker: 'economy',
  satellite: 'economy',
  giftCard: 'economy',
  vagabond: 'economy',
  matador: 'economy',
  toDoList: 'economy',
  tradingCard: 'economy',
  mailInRebate: 'economy',
}
