import { HexagramDefinition } from './types'

export const possibleHexagrams: HexagramDefinition[] = [
  {
    number: 1,
    name: '乾',
    description: 'The Creative',
    hexagram: [true, true, true, true, true, true],
  },
  {
    number: 2,
    name: '坤',
    description: 'The Receptive',
    hexagram: [false, false, false, false, false, false],
  },
  {
    number: 3,
    name: '屯',
    description: 'Difficulty at the Beginning',
    hexagram: [true, false, false, false, false, true],
  },
  {
    number: 4,
    name: '蒙',
    description: 'Youthful Folly',
    hexagram: [false, true, false, false, false, true],
  },
  {
    number: 5,
    name: '需',
    description: 'Waiting',
    hexagram: [true, true, true, false, true, false],
  },
  {
    number: 6,
    name: '訟',
    description: 'Conflict',
    hexagram: [false, true, false, true, true, true],
  },
  {
    number: 7,
    name: '師',
    description: 'The Army',
    hexagram: [false, true, false, false, false, false],
  },
  {
    number: 8,
    name: '比',
    description: 'Holding Together',
    hexagram: [false, false, false, false, true, false],
  },
  {
    number: 9,
    name: '小畜',
    description: 'Small Taming',
    hexagram: [true, true, true, false, true, true],
  },
  {
    number: 10,
    name: '履',
    description: 'Treading',
    hexagram: [true, true, false, true, true, true],
  },
  {
    number: 11,
    name: '泰',
    description: 'Peace',
    hexagram: [true, true, true, false, false, false],
  },
  {
    number: 12,
    name: '否',
    description: 'Standstill',
    hexagram: [false, false, false, true, true, true],
  },
  {
    number: 13,
    name: '同人',
    description: 'Fellowship',
    hexagram: [true, false, true, true, true, true],
  },
  {
    number: 14,
    name: '大有',
    description: 'Great Possession',
    hexagram: [true, true, true, true, false, true],
  },
  {
    number: 15,
    name: '謙',
    description: 'Modesty',
    hexagram: [false, false, true, false, false, false],
  },
  {
    number: 16,
    name: '豫',
    description: 'Enthusiasm',
    hexagram: [false, false, false, true, false, false],
  },
  {
    number: 17,
    name: '隨',
    description: 'Following',
    hexagram: [true, false, false, true, true, false],
  },
  {
    number: 18,
    name: '蠱',
    description: 'Work on the Decayed',
    hexagram: [false, true, true, false, false, true],
  },
  {
    number: 19,
    name: '臨',
    description: 'Approach',
    hexagram: [true, true, false, false, false, false],
  },
  {
    number: 20,
    name: '觀',
    description: 'Contemplation',
    hexagram: [false, false, false, false, true, true],
  },
  {
    number: 21,
    name: '噬嗑',
    description: 'Biting Through',
    hexagram: [true, false, false, true, false, true],
  },
  {
    number: 22,
    name: '賁',
    description: 'Grace',
    hexagram: [true, false, true, false, false, true],
  },
  {
    number: 23,
    name: '剝',
    description: 'Splitting Apart',
    hexagram: [false, false, false, false, false, true],
  },
  {
    number: 24,
    name: '復',
    description: 'Return',
    hexagram: [true, false, false, false, false, false],
  },
  {
    number: 25,
    name: '無妄',
    description: 'Innocence',
    hexagram: [true, false, false, true, true, true],
  },
  {
    number: 26,
    name: '大畜',
    description: 'Great Taming',
    hexagram: [true, true, true, false, false, true],
  },
  {
    number: 27,
    name: '頤',
    description: 'Nourishment',
    hexagram: [true, false, false, false, false, true],
  },
  {
    number: 28,
    name: '大過',
    description: 'Great Exceeding',
    hexagram: [false, true, true, true, true, false],
  },
  {
    number: 29,
    name: '坎',
    description: 'The Abysmal Water',
    hexagram: [false, true, false, false, true, false],
  },
  {
    number: 30,
    name: '離',
    description: 'The Clinging Fire',
    hexagram: [true, false, true, true, false, true],
  },
  {
    number: 31,
    name: '咸',
    description: 'Influence',
    hexagram: [false, false, true, true, true, false],
  },
  {
    number: 32,
    name: '恆',
    description: 'Duration',
    hexagram: [false, true, true, true, false, false],
  },
  {
    number: 33,
    name: '遯',
    description: 'Retreat',
    hexagram: [false, false, true, true, true, true],
  },
  {
    number: 34,
    name: '大壯',
    description: 'Great Power',
    hexagram: [true, true, true, true, false, false],
  },
  {
    number: 35,
    name: '晉',
    description: 'Progress',
    hexagram: [false, false, false, true, false, true],
  },
  {
    number: 36,
    name: '明夷',
    description: 'Darkening of the Light',
    hexagram: [true, false, true, false, false, false],
  },
  {
    number: 37,
    name: '家人',
    description: 'The Family',
    hexagram: [true, true, false, true, false, true],
  },
  {
    number: 38,
    name: '睽',
    description: 'Opposition',
    hexagram: [true, false, true, true, false, true],
  },
  {
    number: 39,
    name: '蹇',
    description: 'Obstruction',
    hexagram: [false, false, true, false, true, false],
  },
  {
    number: 40,
    name: '解',
    description: 'Deliverance',
    hexagram: [false, true, false, true, false, false],
  },
  {
    number: 41,
    name: '損',
    description: 'Decrease',
    hexagram: [true, true, false, false, false, true],
  },
  {
    number: 42,
    name: '益',
    description: 'Increase',
    hexagram: [true, false, false, false, true, true],
  },
  {
    number: 43,
    name: '夬',
    description: 'Breakthrough',
    hexagram: [true, true, true, true, true, false],
  },
  {
    number: 44,
    name: '姤',
    description: 'Coming to Meet',
    hexagram: [false, true, true, true, true, true],
  },
  {
    number: 45,
    name: '萃',
    description: 'Gathering Together',
    hexagram: [false, false, false, true, true, false],
  },
  {
    number: 46,
    name: '升',
    description: 'Pushing Upward',
    hexagram: [false, true, true, false, false, false],
  },
  {
    number: 47,
    name: '困',
    description: 'Oppression',
    hexagram: [false, true, false, true, true, false],
  },
  {
    number: 48,
    name: '井',
    description: 'The Well',
    hexagram: [false, true, true, false, true, false],
  },
  {
    number: 49,
    name: '革',
    description: 'Revolution',
    hexagram: [true, false, true, true, true, false],
  },
  {
    number: 50,
    name: '鼎',
    description: 'The Cauldron',
    hexagram: [false, true, true, true, false, true],
  },
  {
    number: 51,
    name: '震',
    description: 'The Arousing Thunder',
    hexagram: [true, false, false, true, false, false],
  },
  {
    number: 52,
    name: '艮',
    description: 'Keeping Still Mountain',
    hexagram: [false, false, true, false, false, true],
  },
  {
    number: 53,
    name: '漸',
    description: 'Development',
    hexagram: [false, false, true, false, true, true],
  },
  {
    number: 54,
    name: '歸妹',
    description: 'The Marrying Maiden',
    hexagram: [true, true, false, true, false, false],
  },
  {
    number: 55,
    name: '豐',
    description: 'Abundance',
    hexagram: [true, false, true, true, false, false],
  },
  {
    number: 56,
    name: '旅',
    description: 'The Wanderer',
    hexagram: [false, false, true, true, false, true],
  },
  {
    number: 57,
    name: '巽',
    description: 'The Gentle Wind',
    hexagram: [false, true, true, false, true, true],
  },
  {
    number: 58,
    name: '兌',
    description: 'The Joyous Lake',
    hexagram: [true, true, false, true, true, false],
  },
  {
    number: 59,
    name: '渙',
    description: 'Dispersion',
    hexagram: [false, true, false, false, true, true],
  },
  {
    number: 60,
    name: '節',
    description: 'Limitation',
    hexagram: [true, true, false, false, true, false],
  },
  {
    number: 61,
    name: '中孚',
    description: 'Inner Truth',
    hexagram: [true, true, false, false, true, true],
  },
  {
    number: 62,
    name: '小過',
    description: 'Small Exceeding',
    hexagram: [false, false, true, true, false, false],
  },
  {
    number: 63,
    name: '既濟',
    description: 'After Completion',
    hexagram: [true, false, true, false, true, false],
  },
  {
    number: 64,
    name: '未濟',
    description: 'Before Completion',
    hexagram: [false, true, false, true, false, true],
  },
]
