import { getDefaultCard } from '@/app/daily-card-game/domain/playing-card/playing-cards'
import { PlayingCardDefinition } from '@/app/daily-card-game/domain/playing-card/types'

import { DeckDefinition } from './types'

export const checkeredDeckDefinition: PlayingCardDefinition[] = [
  getDefaultCard('2', 'spades'),
  getDefaultCard('2', 'hearts'),
  getDefaultCard('2', 'spades'),
  getDefaultCard('2', 'hearts'),
  getDefaultCard('3', 'spades'),
  getDefaultCard('3', 'hearts'),
  getDefaultCard('3', 'spades'),
  getDefaultCard('3', 'hearts'),
  getDefaultCard('4', 'spades'),
  getDefaultCard('4', 'hearts'),
  getDefaultCard('4', 'spades'),
  getDefaultCard('4', 'hearts'),
  getDefaultCard('5', 'spades'),
  getDefaultCard('5', 'hearts'),
  getDefaultCard('5', 'spades'),
  getDefaultCard('5', 'hearts'),
  getDefaultCard('6', 'spades'),
  getDefaultCard('6', 'hearts'),
  getDefaultCard('6', 'spades'),
  getDefaultCard('6', 'hearts'),
  getDefaultCard('7', 'spades'),
  getDefaultCard('7', 'hearts'),
  getDefaultCard('7', 'spades'),
  getDefaultCard('7', 'hearts'),
  getDefaultCard('8', 'spades'),
  getDefaultCard('8', 'hearts'),
  getDefaultCard('8', 'spades'),
  getDefaultCard('8', 'hearts'),
  getDefaultCard('9', 'spades'),
  getDefaultCard('9', 'hearts'),
  getDefaultCard('9', 'spades'),
  getDefaultCard('9', 'hearts'),
  getDefaultCard('10', 'spades'),
  getDefaultCard('10', 'hearts'),
  getDefaultCard('10', 'spades'),
  getDefaultCard('10', 'hearts'),
  getDefaultCard('J', 'spades'),
  getDefaultCard('J', 'hearts'),
  getDefaultCard('J', 'spades'),
  getDefaultCard('J', 'hearts'),
  getDefaultCard('Q', 'spades'),
  getDefaultCard('Q', 'hearts'),
  getDefaultCard('Q', 'spades'),
  getDefaultCard('Q', 'hearts'),
  getDefaultCard('K', 'spades'),
  getDefaultCard('K', 'hearts'),
  getDefaultCard('K', 'spades'),
  getDefaultCard('K', 'hearts'),
  getDefaultCard('A', 'spades'),
  getDefaultCard('A', 'hearts'),
  getDefaultCard('A', 'spades'),
  getDefaultCard('A', 'hearts'),
]

export const checkeredDeck: DeckDefinition = {
  id: 'checkeredDeck',
  name: 'Checkered Deck',
  description: 'A deck of 52 cards using only Spades and Hearts — each rank appears twice in each suit',
  cards: checkeredDeckDefinition,
  modifiers: {},
}
