import { CelestialCardDefinition } from './types'

export const celestialCards: Record<CelestialCardDefinition['handId'], CelestialCardDefinition> = {
  highCard: {
    type: 'celestialCard',
    handId: 'highCard',
    name: 'High Card',
    description: 'Increases the level of High Card by 1',
    effects: [],
  },
  pair: {
    type: 'celestialCard',
    handId: 'pair',
    name: 'Pair',
    description: 'Increases the level of Pair by 1',
    effects: [],
  },
  twoPair: {
    type: 'celestialCard',
    handId: 'twoPair',
    name: 'Two Pair',
    description: 'Increases the level of Two Pair by 1',
    effects: [],
  },
  threeOfAKind: {
    type: 'celestialCard',
    handId: 'threeOfAKind',
    name: 'Three of a Kind',
    description: 'Increases the level of Three of a Kind by 1',
    effects: [],
  },
  straight: {
    type: 'celestialCard',
    handId: 'straight',
    name: 'Straight',
    description: 'Increases the level of Straight by 1',
    effects: [],
  },
  flush: {
    type: 'celestialCard',
    handId: 'flush',
    name: 'Flush',
    description: 'Increases the level of Flush by 1',
    effects: [],
  },
  fullHouse: {
    type: 'celestialCard',
    handId: 'fullHouse',
    name: 'Full House',
    description: 'Increases the level of Full House by 1',
    effects: [],
  },
  fourOfAKind: {
    type: 'celestialCard',
    handId: 'fourOfAKind',
    name: 'Four of a Kind',
    description: 'Increases the level of Four of a Kind by 1',
    effects: [],
  },
  straightFlush: {
    type: 'celestialCard',
    handId: 'straightFlush',
    name: 'Straight Flush',
    description: 'Increases the level of Straight Flush by 1',
    effects: [],
  },
  royalFlush: {
    type: 'celestialCard',
    handId: 'royalFlush',
    name: 'Royal Flush',
    description: 'Increases the level of Royal Flush by 1',
    effects: [],
  },
  flushHouse: {
    type: 'celestialCard',
    handId: 'flushHouse',
    name: 'Flush House',
    description: 'Increases the level of Flush House by 1',
    effects: [],
  },
  fiveOfAKind: {
    type: 'celestialCard',
    handId: 'fiveOfAKind',
    name: 'Five of a Kind',
    description: 'Increases the level of Five of a Kind by 1',
    effects: [],
  },
  flushFive: {
    type: 'celestialCard',
    handId: 'flushFive',
    name: 'Flush Five',
    description: 'Increases the level of Flush Five by 1',
    effects: [],
  },
}
