#!/usr/bin/env tsx
/**
 * Retire questions generated by the pre-Anthropic (gpt-4o) pipeline.
 *
 * For every aiQuestions doc that lacks the `models` provenance field,
 * stamp it with the legacy gpt-4o pipeline metadata and flip its
 * `status` to 'legacy'. The sampler and warm-pool only consider
 * status='active' docs, so this single change both (a) removes the
 * legacy questions from circulation and (b) keeps the warm-pool count
 * accurate.
 *
 * Stamped fields:
 *   - models = { facts: 'gpt-4o-mini', question: 'gpt-4o', review: 'gpt-4o-mini' }
 *     (matches the previous pipeline; `repair` is omitted because we
 *     can't tell per-doc whether it ran)
 *   - appVersion = 'pre-tracking'
 *   - status = 'legacy' (was 'active', 'flagged', or 'removed' — we
 *     preserve 'removed' since admin removals are a separate signal,
 *     and we leave 'flagged' alone too in case the manual review queue
 *     wants to keep working through them)
 *
 * Idempotent — re-runnable. Docs that already have `models` set are
 * skipped. Docs whose status is already 'legacy', 'removed', or
 * 'flagged' are NOT flipped, only stamped with the metadata if missing.
 *
 * Usage:
 *   yarn backfill-legacy-trivia
 *   (which runs `tsx --env-file=.env.local scripts/backfill-legacy-models.ts`)
 *
 * Required env vars (same as the app), normally loaded from .env.local:
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_CLIENT_EMAIL
 *   FIREBASE_PRIVATE_KEY
 */

import { cert, getApps, initializeApp } from 'firebase-admin/app'
import { FieldValue, getFirestore, type WriteBatch } from 'firebase-admin/firestore'

const BATCH_SIZE = 400 // Firestore max is 500; stay well under

const LEGACY_MODELS = {
  facts: 'gpt-4o-mini',
  question: 'gpt-4o',
  review: 'gpt-4o-mini',
} as const

const LEGACY_APP_VERSION = 'pre-tracking'

function ensureApp() {
  if (getApps().length > 0) return
  const projectId = process.env.FIREBASE_PROJECT_ID
  const clientEmail = process.env.FIREBASE_CLIENT_EMAIL
  const privateKey = process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n')
  if (!projectId || !clientEmail || !privateKey) {
    console.error(
      'ERROR: Missing Firebase env vars. Set FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY.'
    )
    process.exit(1)
  }
  initializeApp({ credential: cert({ projectId, clientEmail, privateKey }) })
}

async function main() {
  ensureApp()
  const db = getFirestore()

  console.log('Fetching all aiQuestions documents...')
  const snap = await db.collection('aiQuestions').get()
  console.log(`Found ${snap.size} document(s).`)

  let batch: WriteBatch = db.batch()
  let batchCount = 0
  let stampedTotal = 0
  let flippedTotal = 0
  let skippedTotal = 0

  for (const doc of snap.docs) {
    const data = doc.data()
    const update: { [key: string]: FieldValue | Partial<unknown> | undefined } = {}

    if (!data.models) {
      update.models = LEGACY_MODELS
    }
    if (!data.appVersion) {
      update.appVersion = LEGACY_APP_VERSION
    }
    // Only flip currently-active docs to legacy. Preserve 'removed' and
    // 'flagged' so existing admin signals stay intact.
    if (data.status === 'active' && !data.models) {
      update.status = 'legacy'
      flippedTotal++
    }

    if (Object.keys(update).length === 0) {
      skippedTotal++
      continue
    }

    batch.update(doc.ref, update)
    batchCount++
    stampedTotal++

    if (batchCount >= BATCH_SIZE) {
      process.stdout.write(`Committing batch of ${batchCount}...`)
      await batch.commit()
      console.log(' done.')
      batch = db.batch()
      batchCount = 0
    }
  }

  if (batchCount > 0) {
    process.stdout.write(`Committing final batch of ${batchCount}...`)
    await batch.commit()
    console.log(' done.')
  }

  console.log('─'.repeat(60))
  console.log(`Stamped: ${stampedTotal} (of which ${flippedTotal} flipped active→legacy)`)
  console.log(`Skipped (already had models + appVersion): ${skippedTotal}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
