import { HexagramDefinition } from '@/app/oracle/types'

export const hexagramDescriptions_25_32: Record<HexagramDefinition['number'], string> = {
  [25]: `Innocence (Wu Wang) represents spontaneous, natural action free from ulterior motives. The hexagram symbolizes the primal power of truth and authenticity, where Heaven moves within the Thunder, suggesting dynamic energy aligned with cosmic order. This is the state of genuine simplicity, where actions arise from inner truth rather than calculation or artifice. The traditional judgment emphasizes that unexpected misfortune is not caused by wrongdoing when one acts with innocence. If one is not as they should be, misfortune follows, and no undertaking will succeed. This hexagram teaches that innocence means acting in harmony with the Tao, without forcing outcomes or manipulating circumstances. True innocence is not naive ignorance but a profound alignment with natural law. In divination, this hexagram suggests acting from your authentic nature without scheming or second-guessing. What feels spontaneous and natural is likely correct. However, guard against recklessness disguised as spontaneity. The innocent mind perceives clearly and acts decisively without attachment to results.`,
  [26]: `Great Taming (Da Chu) represents the accumulation and restraint of power. The image shows the mountain (keeping still) restraining heaven (the creative), suggesting that great forces are being held in check and concentrated. This hexagram teaches the value of patient accumulation - gathering strength, knowledge, and resources rather than immediately spending them. Like a dam holding back tremendous water, or a student absorbing years of learning before practicing, Great Taming speaks to the power of containment and preservation. The judgment promises that it furthers one to cross the great water, but only after this period of taming and accumulation. The hexagram also emphasizes nourishment of what is worthy - supporting great people and cultivating excellence. In divination, Great Taming suggests a time to build your reserves rather than act. Study, save resources, develop skills, and strengthen your foundation. Restraining your impulse to act immediately creates the power for truly significant achievement later. This is favorable for long-term planning and substantial undertakings.`,
  [27]: `Nourishment (Yi) addresses both the act of nourishing and being nourished. The image of the mountain over thunder suggests stillness that nurtures the seeds of action. The hexagram depicts the mouth, showing both what we take in and what we express outwardly. The judgment counsels paying attention to what you provide as nourishment and seeking your own nourishment from proper sources. This applies to physical food, mental input, spiritual sustenance, and the words we speak. Traditional interpretation emphasizes the importance of nourishing worthy people and being careful about whom we nourish with our resources and attention. Observing what a person nourishes reveals their character, as does observing what they seek for nourishment. In divination, this hexagram directs your attention to questions of sustenance and care. Are you nourishing yourself properly? Are you careful about what you consume - whether food, information, or relationships? Are you using your resources to support what is worthy? Consider both sides of nourishment: what you take in shapes you, and what you provide reveals your values.`,
  [28]: `Great Exceeding (Da Guo) represents a critical situation where the burden is too heavy for the structure to bear. The image shows the lake rising above the trees, suggesting that water threatens to overwhelm the wood that should contain it. The ridgepole sags dangerously under excessive weight. This hexagram depicts those extraordinary times that demand extraordinary measures. The judgment promises success despite the difficult circumstances, and counsels that it furthers one to have somewhere to go - action is required. Great Exceeding often appears when normal approaches will not suffice, when the situation has become critical, and when bold or unconventional action becomes necessary. However, the action must be undertaken with full awareness of the exceptional nature of the circumstances. In divination, this hexagram indicates that you face an extraordinary situation requiring exceptional response. The conventional approach will not work; you must be willing to take risks or make unusual choices. The situation is unstable and cannot remain as it is. Act with courage but also with clear awareness of the gravity of circumstances.`,
  [29]: `The Abysmal Water (Kan) represents danger, repeated challenges, and the depths. The image shows water upon water - danger doubled, pit upon pit. Yet the judgment teaches that if you remain sincere and maintain inner truth, your heart will penetrate and your actions bring success. Water always flows onward, filling every depression before moving forward, never losing its essential nature despite obstacles. This hexagram teaches that some situations require us to move through danger rather than around it, maintaining our integrity and direction even as we navigate treacherous passages. The water pit symbolizes unavoidable danger that must be faced with courage and sincerity. In divination, The Abysmal indicates that you face genuine danger or difficulty that cannot be avoided. Do not minimize the seriousness of the situation, but do not be paralyzed by it either. Like water, flow steadily through the difficulty, maintaining your inner truth and essential nature. Success comes not from avoiding the danger but from moving through it with consistency and courage. Stay true to your principles even in the depths.`,
  [30]: `The Clinging Fire (Li) represents clarity, illumination, and dependence. The image shows fire upon fire, doubling the quality of light and awareness. Fire, unlike water, must cling to what it burns; it has no independent existence but depends on fuel. This hexagram teaches about conscious dependence on what is correct - clinging to truth, beauty, and justice as fire clings to its fuel. The judgment promises success through perseverance and care in what we choose to depend upon. Li brings illumination and clarity, revealing things as they are. It represents consciousness, awareness, and the light of understanding. In divination, The Clinging Fire suggests that clarity and conscious awareness are essential now. Examine what you depend on and ensure it is worthy. Illuminate your situation through careful attention and conscious thought. Your success depends on clarity of vision and choosing the right things to attach yourself to. This hexagram favors intellectual work, bringing light to dark situations, and maintaining conscious awareness in all actions.`,
  [31]: `Influence (Xian) represents attraction, mutual influence, and the beginning of relationship. The image shows the lake above the mountain - receptiveness above, stillness below - creating the conditions for genuine influence. This hexagram specifically represents the attraction between young man and maiden, but extends to all forms of mutual influence and beginning connection. The judgment promises success through constancy and warns about taking a maiden in marriage - suggesting that influence should lead to lasting commitment. Influence works through receptivity rather than force; it is the power of attraction that draws things together naturally. The hexagram teaches that true influence comes from inner emptiness and receptiveness, not from pushing or grasping. In divination, Influence indicates mutual attraction and the beginning of significant relationships or partnerships. Success comes through remaining open, receptive, and genuine. This is a favorable time for beginning new connections, but the hexagram counsels that initial attraction should mature into lasting commitment. Influence flows naturally when you remain humble and receptive.`,
  [32]: `Duration (Heng) represents endurance, consistency, and the power of what lasts. The image shows thunder above wind - two forces that, though powerful, work together in lasting complementarity. This hexagram teaches that true duration comes not from rigidity but from consistent renewal within a stable framework, like a marriage that endures through constancy of commitment while adapting to change. The judgment promises success through perseverance and counsels that it furthers one to have somewhere to go - duration requires direction and purpose. What endures does so because it remains true to its essential nature while being flexible in non-essentials. Duration represents the middle path between stagnation and aimless change. In divination, this hexagram indicates that lasting success comes through consistency, patience, and maintaining your direction over time. This is favorable for long-term commitments, enduring relationships, and persistent effort toward distant goals. The key is finding the right path and staying on it with steadfast purpose while remaining inwardly flexible. True duration comes from constancy of principle, not rigidity of form.`,
}

// Changing line descriptions for hexagrams 25-32
// Each hexagram has 6 lines (bottom to top: line1 through line6)
export const changingLineDescriptions_25_32: Record<HexagramDefinition['number'], string[]> = {
  [25]: [
    `Line 1: Innocent Proceeding - Moving forward with pure intentions brings good fortune. Your natural impulse is correct; trust your spontaneous response without overthinking. This is a time when simple, authentic action aligned with your true nature creates the best outcomes. Do not complicate matters with calculation or strategy.`,
    `Line 2: Reaping Without Plowing - Benefits come unexpectedly, not through deliberate planning. This line teaches that when you act with innocence, results may arrive in surprising ways or at unexpected times. Do not count on specific outcomes; simply maintain your natural integrity and allow circumstances to unfold. What comes to you now is a natural consequence of your authentic being.`,
    `Line 3: Undeserved Misfortune - Despite acting correctly, you may face unexpected difficulties. This is the cow tethered by a passerby and taken by another - blameless involvement in unfortunate circumstances. The teaching here is that innocence does not guarantee immunity from all misfortune, but your lack of wrongdoing means the difficulty will pass without lasting harm. Maintain your integrity through the challenge.`,
    `Line 4: Persevering in Integrity - Holding to your true nature brings success even when others doubt. This line emphasizes that innocence must sometimes stand firm against pressure to compromise. What is genuinely yours cannot be lost, and what aligns with natural law will prevail. Trust your inner guidance even when external circumstances seem to contradict it.`,
    `Line 5: Illness Without Remedy - Some difficulties resolve themselves without intervention. Like an illness that disappears on its own, certain problems should not be forced toward solution. Your innocent nature attracts natural healing and resolution. The medicine is to maintain your authentic state and allow natural processes to restore balance without anxious interference.`,
    `Line 6: Innocent Action Gone Astray - This is not the time for action, even innocent action. The line warns that timing matters as much as intention. When circumstances are fundamentally unfavorable, even sincere efforts meet with obstacles. Recognize when the time is not ripe and practice innocent non-action, waiting for conditions to shift before proceeding.`,
  ],
  [26]: [
    `Line 1: Danger Ahead - You recognize that advancing would be hazardous and wisely restrain yourself. This line represents the beginning of accumulation through recognizing what not to do. Your ability to perceive danger and hold back demonstrates the wisdom that will allow you to build great reserves. Restraint now is not weakness but intelligent preservation of energy for when the time is right.`,
    `Line 2: The Wagon Loses Its Axle - External forces compel you to stop and wait. This enforced pause, though frustrating, serves the greater purpose of accumulation. Like a wagon that cannot move forward until repaired, you must use this time to strengthen your foundation and gather resources. What seems like an obstacle is actually an opportunity to build capacity for future endeavors.`,
    `Line 3: Practicing for the Journey - You are developing skills and resources in preparation for significant undertaking. This line shows active accumulation through training and practice. Like a person learning to drive before attempting a long journey, you are wisely building competence. Continue this dedicated preparation; it furthers one to persevere in self-development. The time to cross great waters approaches but has not yet arrived.`,
    `Line 4: Restraining the Young Bull - Preventing problems before they develop brings supreme good fortune. This line teaches preventive wisdom - placing a board on the horns of a young bull before it learns to use them for harm. By restraining potentially destructive forces early, you avoid greater difficulties later. This is the art of taming through gentle but firm guidance applied at the right moment.`,
    `Line 5: The Tusks of a Gelded Boar - Addressing the root cause rather than the symptoms. Like removing the aggression of a boar by gelding rather than just filing its tusks, you find the fundamental solution. This line represents the ability to tame great forces not through direct confrontation but through addressing their source. Great good fortune comes from this deeper understanding and skillful intervention.`,
    `Line 6: Attaining Heaven's Way - Your accumulation is complete, and now you can accomplish great things. This line represents the fulfillment of Great Taming - you have built sufficient resources, wisdom, and power to successfully undertake major endeavors. The way lies open before you. This is the time to cross the great water, to pursue your most significant goals with confidence born of thorough preparation.`,
  ],
  [27]: [
    `Line 1: Envying the Magic Tortoise - You observe others receiving nourishment while neglecting your own proper sources. The magic tortoise can subsist on air, but you cannot. This line warns against looking to others' paths for nourishment that must come from your own efforts. Letting your own nourishment fall away while envying others brings misfortune. Attend to your actual needs rather than being distracted by what sustains others.`,
    `Line 2: Seeking Nourishment on the Heights - You turn from proper sources to improper ones, seeking sustenance from what cannot truly nourish you. This line shows the folly of abandoning solid foundations to pursue what glitters but does not satisfy. Turning to the hilltop for nourishment contradicts the natural way. Undertakings based on inadequate or inappropriate sources of support bring misfortune.`,
    `Line 3: Turning Away from Nourishment - You reject proper sustenance and indulge in what harms you. This line represents a fundamental violation of the principle of nourishment - seeking pleasure instead of genuine sustenance. Like someone who eats poison because it tastes sweet, you pursue what brings temporary satisfaction but lasting harm. Ten years of effort cannot overcome the damage from persistently nourishing yourself from wrong sources.`,
    `Line 4: Seeking Nourishment from Above - You look to sources higher than yourself for sustenance and have the capacity to receive it. Like a tiger surveying from a height, seeking those it can nourish and those who can nourish it, you are positioned to connect superior resources with genuine need. This brings good fortune when done with proper intention - using your position to channel nourishment to worthy recipients.`,
    `Line 5: Providing Nourishment - You recognize your own limitations and wisely remain in place while channeling nourishment to others. This line teaches that not everyone should undertake great crossings; some fulfill their purpose by maintaining a stable position from which they support those who do venture forth. Knowing your proper sphere and nourishing what is worthy from that position brings success and good fortune.`,
    `Line 6: Source of Nourishment - You have become a wellspring from which others draw sustenance. This position of being the source carries both danger and great good fortune. The danger lies in the weight of responsibility; the good fortune comes from fulfilling this crucial role. It furthers one to cross great waters from this position, as you carry nourishment that benefits all. Act with full awareness of the significance of your role.`,
  ],
  [28]: [
    `Line 1: Careful Foundation - In this critical situation, you take care even with small things, placing soft materials beneath the heavy burden. This line teaches that when facing Great Exceeding, meticulous attention to foundations matters. Using soft materials to cushion weight shows adaptability and care. Even this humble approach succeeds when circumstances are extraordinary.`,
    `Line 2: The Withered Willow Sprouts - Something thought exhausted shows unexpected vitality. An old willow produces fresh shoots; an older man takes a young wife. This line represents renewal and surprising fertility in unlikely circumstances. What seemed past its prime demonstrates new life. While unconventional, this brings no blame when Great Exceeding demands extraordinary responses. The situation contains unexpected possibilities.`,
    `Line 3: The Ridgepole Sags - The burden becomes too great and the structure begins to fail. This line represents the critical point where extraordinary pressure overwhelms even strong foundations. Misfortune comes when you persist beyond the limits of what can be sustained. This is a warning that some situations have exceeded safe boundaries and require immediate action to prevent collapse. Do not continue as if normal measures suffice.`,
    `Line 4: The Ridgepole Holds - Despite strain, the structure maintains integrity and even shows strength. This line teaches that in Great Exceeding, success comes through finding the proper support and reinforcement. There is good fortune when you address the critical situation with adequate resources and appropriate measures. What seems on the verge of failure can be sustained with correct action. However, any hint of ulterior motives (symbolized by improper relationship) brings humiliation.`,
    `Line 5: The Withered Willow Blooms - Like an old willow producing flowers rather than seeds, there is beauty but no fruit. An older woman marries a young man - the relationship brings no descendants but no blame. This line represents situations where the form is present but ultimate fulfillment cannot follow. In Great Exceeding, sometimes the best outcome is to create beauty and connection even without lasting results. There is neither praise nor blame in doing what is possible within impossible circumstances.`,
    `Line 6: Exceeding in Crossing - You attempt to wade through waters that are too deep, and the situation overwhelms you. This line warns against going too far even when extraordinary measures are necessary. There is misfortune in exceeding your actual capacity, even when facing circumstances that demand exceptional response. Yet this misfortune carries no lasting blame if your intentions were correct. Sometimes even the brave drown, and this does not diminish their courage. Know your limits even in crisis.`,
  ],
  [29]: [
    `Line 1: Double Danger - You face repeated challenges, entering a pit within a pit. This line teaches that when in danger, adding more danger through rash action makes things worse. Like falling into a hole while trying to escape a hole, errors compound when you lose your center in difficult circumstances. The teaching is to maintain composure and navigate carefully rather than thrashing about. Even in the abyss, keep your heart true and your actions measured.`,
    `Line 2: The Abyss is Dangerous - You are deep in difficulty and can only manage small advances. This line counsels accepting that in certain dangerous situations, grand solutions are not available. Make what small progress you can, be grateful for even modest gains, and do not expect to resolve everything at once. Like someone in a deep pit who can only climb a few feet at a time, persistent small efforts eventually lead to escape. There is no shame in incremental progress through danger.`,
    `Line 3: Surrounded by Danger - Every direction presents obstacles, whether forward into deep waters or back into sharp precipices. This line represents the worst position in danger - no obvious path to safety. The teaching is that in such circumstances, attempting action only makes things worse. Come to a standstill, preserve your energy, and wait without acting. Do not use dangerous moments for undertakings. Simply endure with inner truth maintained until circumstances shift.`,
    `Line 4: Simple Sincerity - In dangerous times, complex strategies fail. This line teaches that sincerity expressed simply succeeds where cleverness does not. Offer what is genuine even if it seems inadequate - a jug of wine, a simple bowl of rice, earthenware vessels. What matters in the abyss is authentic communication and basic human connection. Elaborate presentations cannot help; simple truth creates the opening. No blame comes from this humble approach.`,
    `Line 5: Not Overflowing - The danger is not at its worst; like a gorge not yet filled to overflowing, there is still space. This line teaches that when in danger, you must accurately assess how much danger actually exists. This is not the deepest point of the abyss. By maintaining level-headedness and not exaggerating the situation, you find that the path forward exists. Already you are on level ground even if you do not yet recognize it. Trust that danger has limits.`,
    `Line 6: Bound by Restrictions - You are trapped and constrained, like a prisoner bound in a thorny hedge. This line represents being caught so thoroughly in difficulty that freedom seems impossible. The warning is severe: three years without relief. When you reach this point through your own choices, the consequences are inescapable for a time. This teaches that there are dangers from which extrication takes years. Let this be a warning to avoid the actions that lead to such thorough entanglement.`,
  ],
  [30]: [
    `Line 1: The Footsteps Cross - Your movement shows confusion and hesitation, steps going in different directions. This line teaches that at the beginning of clarity, one must sort out confused impulses. By recognizing this early confusion and being respectful in your approach, you avoid blame. The key is to notice when you lack clear direction and to proceed carefully until true clarity emerges. Reverence and careful attention at this stage prevent later errors.`,
    `Line 2: Yellow Light - You embody balanced, centered clarity - neither too dim nor too bright, neither too yin nor too yang. Yellow represents the center, the balanced position. This line teaches that supreme good fortune comes from maintaining the middle path in your clarity. You see clearly but without harshness, illuminate but without blinding, depend on correct principles but with flexibility. This balanced approach to consciousness brings lasting success.`,
    `Line 3: The Setting Sun - In the declining light of day, people either lament the passing of brightness or accept it with equanimity. This line teaches about clinging to clarity when circumstances naturally bring darkness. The elderly person singing with contentment accepts life's natural cycles; the same person beating a drum and lamenting fights against what cannot be changed. Misfortune comes from refusing to accept that even light has its time of fading. Accept natural transitions with grace.`,
    `Line 4: Sudden Arrival - Change comes abruptly, like flames bursting forth. This line depicts sudden clarity or sudden passion that arrives without warning - it burns, blazes up, dies down, and is cast away. The teaching is about the nature of unsustained intensity. Some fire burns brilliantly but briefly because it lacks proper fuel. While there is no lasting harm, there is also no lasting achievement. This line counsels against putting faith in sudden enthusiasms that lack foundation.`,
    `Line 5: Tears and Lamentation - Even in positions of clarity and connection, there can be sorrow. This line teaches that consciousness brings awareness of loss and limitation as well as of beauty and truth. Your tears flow, you lament and sigh, yet this brings good fortune. The ability to feel deeply, to mourn what must be mourned while maintaining your clarity and connection, represents mature consciousness. Do not suppress genuine feeling in the name of staying positive.`,
    `Line 6: The King Hunts the West - You use your clarity and power to eliminate what is harmful rather than to conquer the innocent. This line distinguishes between necessary severity and excessive harshness. The king goes forth to hunt, pursuing those who have chosen rebellion, but does not capture the innocent who were merely present. This represents using the illuminating power of consciousness to address genuine problems while showing mercy to those who deserve it. Great good fortune comes from this discriminating use of clarity and power.`,
  ],
  [31]: [
    `Line 1: Influence in the Big Toe - The first stirring of attraction is felt in the lowest place, the extremity. This line teaches that influence often begins subtly, as a small sensation or impulse. At this stage, the influence is so slight it can be ignored or redirected. The big toe moves, but the body need not follow. Remain aware of what attracts you but do not feel compelled to act on every small impulse. No blame comes from simply feeling the initial movement of influence without pursuing it.`,
    `Line 2: Influence in the Calves - The urge to move toward the object of attraction grows stronger, felt in the muscles that propel movement. This line warns that acting on this impulse prematurely brings misfortune. The calves want to walk toward what attracts them, but this is not yet the time. If you wait and remain where you are, even though the pull is strong, good fortune follows. This teaches the discipline of feeling attraction without immediately pursuing it. Staying brings good fortune.`,
    `Line 3: Influence in the Thighs - The attraction becomes strong enough to pull you along, and you follow every impulse. This line represents being led by desire rather than maintaining your center. The thighs follow the body wherever it goes, having no independence. When you cling to and follow every attraction this way, humiliation follows. You lose your autonomy and dignity by being unable to resist influence. The teaching is to maintain self-possession even in the presence of strong attraction.`,
    `Line 4: Persevering Brings Good Fortune - When influence is mutual and genuine, persevering in that connection succeeds. This line teaches that at the level of the heart (moving beyond physical attraction to genuine care), remorse disappears. When friends truly respond to your thoughts and feelings, this creates lasting connection. However, the line counsels careful attention to where your thoughts go - anxiety and scattered thinking disturb the influence. Keep your heart steady and your intentions clear.`,
    `Line 5: Influence in the Neck - You feel the attraction in your upper spine, in the part that holds your head upright. This line teaches that influence at the level of bearing and dignity brings no remorse. This is attraction based on respect and recognition of virtue rather than on lower impulses. While you feel the influence strongly (in the back of the neck), you maintain your upright bearing. This represents mature attraction where both parties maintain their integrity.`,
    `Line 6: Influence in Jaws and Tongue - Attraction expressed only through words without genuine feeling behind them. This line warns that influence that remains at the level of speech without engaging the heart is superficial and ineffective. Talking about connection, describing attraction, or declaring intentions without authentic inner movement creates no real influence. The tongue moves in the mouth, creating sounds, but if the heart is not engaged, these are empty words that influence nothing.`,
  ],
  [32]: [
    `Line 1: Seeking Duration Too Quickly - You grasp for permanence before the foundation is established. This line warns that attempting to force duration at the beginning brings misfortune. Nothing furthers such premature grasping. True duration must grow from proper beginnings; it cannot be imposed. Like trying to make a relationship permanent on the first day or demanding loyalty before it is earned, this approach undermines the very duration you seek. Allow things to develop naturally before expecting them to last.`,
    `Line 2: Remorse Disappears - You have found the middle path where excess is eliminated and duration can establish itself. This line teaches that lasting success comes from avoiding extremes. Like someone who can maintain their position because they make no excessive demands and chase no unrealistic goals, you create the conditions for things to endure. By staying centered and not overreaching, you allow natural duration to emerge. This balanced approach brings good fortune.`,
    `Line 3: Not Constant in Virtue - You lack the inner consistency necessary for outer duration. This line represents the person who receives humiliation because their character is not constant. Without inner duration, external duration cannot be maintained. If your own nature shifts with every wind, if you have no constant principles or steady commitment, you create a foundation too unstable to support lasting achievements. This brings lasting shame. The teaching is that duration begins within.`,
    `Line 4: No Game in the Field - You hunt where there is nothing to catch because you have not adapted to the actual situation. This line teaches that duration requires being in the right place at the right time. Hunting in a field with no game, maintaining efforts in an area that holds no possibility - this represents a failure to adjust to reality. Duration is not stubbornness; it requires flexible alignment with actual conditions. Persisting in the wrong place or wrong approach brings no results.`,
    `Line 5: Constancy in Character - You maintain your essential nature through changing circumstances, and this brings good fortune. This line distinguishes between the man who maintains constant virtue through consistency of character and the woman who maintains constant virtue through constancy of position. Both are forms of duration, but they work differently. For those who lead or act, duration comes through unchanging character even as actions adapt. This consistency of inner nature while remaining flexible in outer form represents the perfection of duration.`,
    `Line 6: Restlessness - The person who demands immediate results and cannot maintain steady effort. This line warns that excessive restlessness destroys duration. Like someone who constantly shakes a tree to see if fruit will fall rather than allowing it to ripen, you undermine what you hope to sustain. Persistent agitation, constant demands for visible progress, inability to maintain steady long-term effort - these bring misfortune. True duration requires the ability to persevere without constant validation or immediate results.`,
  ],
}
