import { HexagramDefinition } from '@/app/oracle/types'

// Hexagram descriptions for hexagrams 17-24
export const hexagramDescriptions_17_24: Record<HexagramDefinition['number'], string> = {
  [17]: `Following (Sui) represents the principle of adaptation and willing acceptance. The hexagram symbolizes Lake over Thunder - joy following movement in a natural rhythm. The Judgment teaches that great success comes through perseverance and adaptability, knowing when to lead and when to follow. In traditional interpretation, this hexagram emphasizes the importance of being receptive to the flow of events and following natural laws rather than forcing one\'s will. When you receive this hexagram, it suggests a time to align yourself with capable leadership or natural rhythms, to be flexible while maintaining your principles, and to recognize that sometimes the wisest course is to adapt rather than resist.`,
  [18]: `Work on What Has Been Spoiled (Gu) represents repair, renewal, and correcting past mistakes. The image is of Wind below Mountain - stagnation that must be addressed through deliberate effort. The Judgment promises supreme success through correction of errors that have accumulated over time, whether through negligence or the corruption of good traditions. This hexagram often appears when there are inherited problems or deteriorating situations that require attention. It counsels careful examination of what has gone wrong and systematic work to restore proper order. The message is one of hope: decay can be reversed through diligent effort. This is a time for taking responsibility, making repairs, and clearing away what has become toxic or stagnant.`,
  [19]: `Approach (Lin) signifies the gradual advance of positive forces and the promise of growth and expansion. The hexagram shows Earth over Lake, representing spring\'s advance and increasing light. The Judgment indicates supreme success through perseverance, though it warns that the eighth month brings misfortune - suggesting that favorable conditions are not permanent. This hexagram appears when opportunities are approaching and when your influence is naturally growing. It counsels active engagement and forward movement while remaining mindful that all cycles eventually turn. Traditional wisdom associates this hexagram with leadership that is both kind and watchful, advancing while staying alert to changing circumstances. Now is the time to be present, to approach others with openness, and to make the most of favorable conditions while they last.`,
  [20]: `Contemplation (Guan) represents observation, reflection, and the power of example. Wind over Earth suggests pervasive influence through presence rather than action. The image is of an ancient tower from which the ruler observes the land, or of worshippers looking up to the sacred. The Judgment teaches that while ablution has been made, the offering has not yet been presented - emphasizing sincere preparation and the gravity of the contemplative moment. This hexagram appears when it\'s time to step back from action and observe, to reflect deeply on the nature of things, and to recognize how your presence affects others. Traditional interpretation emphasizes that those who are truly contemplative become models for others naturally. In divination, this suggests a period for meditation, study, and understanding the larger patterns at work rather than rushing into action.`,
  [21]: `Biting Through (Shi Ho) represents the need for decisive action to remove obstacles and restore order. Fire over Thunder suggests a powerful combination of clarity and shock, like a legal judgment being executed. The image is of something caught between the teeth that must be bitten through - an obstruction that prevents proper union. The Judgment indicates success through firmness and the use of penalties when necessary. This hexagram often appears in situations requiring justice, where wrongdoing must be addressed clearly and directly. Traditional wisdom teaches that obstacles sometimes require forceful removal, and that appropriate severity serves the greater good. When you receive this hexagram, it signals a time to confront problems directly, to cut through complications with clarity, and to ensure that justice is served even when uncomfortable.`,
  [22]: `Grace (Bi) represents elegance, beauty, and the harmonious adornment of form. Mountain over Fire suggests light illuminating the slopes, revealing natural beauty in its proper setting. The Judgment indicates success in small matters, while cautioning that grace should enhance substance rather than replace it. This hexagram teaches the importance of form, culture, and aesthetic refinement in human affairs, while warning against excessive ornamentation. Traditional interpretation emphasizes that true grace arises from inner worth expressed outwardly with appropriate style. In legal and social matters, it favors diplomatic and cultured approaches. When this hexagram appears, it suggests attending to presentation and manner, cultivating refinement, and recognizing that how something is done matters almost as much as what is done. However, remember that grace should serve truth, not obscure it.`,
  [23]: `Splitting Apart (Bo) represents decay, dissolution, and the natural process of breaking down. Mountain over Earth suggests the mountain being gradually eroded, its base undermined. The Judgment advises that it does not further one to undertake anything - this is a time of yielding rather than action. This hexagram appears during periods of decline when inferior forces are ascendant and what was solid begins to fragment. Traditional wisdom teaches that such times require patience and withdrawal, preserving one\'s integrity while waiting for the cycle to turn. The image shows five yin lines overwhelming one yang line at the top, illustrating how negative forces can dominate. When you receive this hexagram, it counsels acceptance of natural dissolution, avoiding futile resistance, and maintaining inner truth while outer forms crumble.`,
  [24]: `Return (Fu) represents the turning point, renewal, and the return of light after darkness. Thunder beneath Earth symbolizes the stirring of new energy underground at the winter solstice. The Judgment promises success, as the natural way returns and energy begins to flow again after a period of dormancy. This hexagram follows Splitting Apart, showing that after complete decline comes natural regeneration. Traditional interpretation associates it with the seventh day after the solstice, when yang energy begins to return. When this hexagram appears, it signals a time of recovery and fresh beginnings, though gentle nurturing is needed. The return is natural and gradual - forcing growth would be harmful. This is a time to welcome renewal, to align with natural cycles, and to trust that what seemed lost is coming back to life.`,
}

// Changing line descriptions for hexagrams 17-24
export const changingLineDescriptions_17_24: Record<HexagramDefinition['number'], string[]> = {
  [17]: [
    `Line 1: The standard is changing. Perseverance brings good fortune. Going out of the door in company produces deeds. At the beginning of Following, be willing to change your standards and adapt to new circumstances. When you venture forth with others and remain open to their influence, meaningful accomplishments result. This line teaches that following begins with releasing rigid expectations and embracing flexibility. By adjusting your approach and working cooperatively, you establish the foundation for mutual benefit.`,
    `Line 2: If one clings to the little boy, one loses the strong man. In Following, you must discern what is worth following and what leads you astray. Attachment to what is immature, trivial, or merely comfortable causes you to miss connection with what is truly substantial and valuable. This line warns against settling for lesser influences when something of greater worth is available. Choose your guides wisely.`,
    `Line 3: If one clings to the strong man, one loses the little boy. Through following, one finds what one seeks. It furthers one to remain persevere. By committing to what is strong, mature, and valuable, you naturally release attachment to the superficial. Following worthy leadership or principles brings you what you truly need. This line emphasizes the importance of making clear choices about whom or what you follow. Dedication to the substantial brings fulfillment.`,
    `Line 4: Following creates success. Perseverance brings misfortune. To go one\'s way with sincerity brings clarity. How could there be blame in this? From a position of influence, following blindly leads to problems. Instead, maintain your integrity and authentic vision while remaining responsive to circumstances. This line teaches that Following does not mean abandoning your own truth. Sincere adherence to principle, even while adapting to conditions, prevents error and brings clarity.`,
    `Line 5: Sincere in the good. Good fortune. From a position of leadership, your genuine commitment to what is beneficial creates fortunate outcomes. When those in authority follow what is truly good rather than what is merely expedient or popular, everyone benefits. This line represents the ideal of Following - aligning with what is right and excellent, thereby inspiring others to do the same.`,
    `Line 6: The king presents him to the Western Mountain. Following reaches its completion when one is held in such high regard that others seek to follow them. This line depicts being honored and recognized as worthy of devotion. The Western Mountain symbolizes the sacred realm where the ancestors dwell, suggesting that true Following ultimately connects us to what is timeless and transcendent. This is the culmination of a life lived in harmony with natural and spiritual law.`,
  ],
  [18]: [
    `Line 1: Setting right what has been spoiled by the father. If there is a son, no blame rests upon the departed father. The work goes on. At the beginning of correction, you inherit problems created by previous generations or earlier versions of yourself. By taking responsibility for setting things right, you honor what came before while improving upon it. This line teaches that we can repair past mistakes without blaming those who made them. The work of renewal continues across generations.`,
    `Line 2: Setting right what has been spoiled by the mother. One must not be too persevering. When correcting errors rooted in nurturing, care, or emotional patterns, gentleness is essential. Too harsh an approach damages what remains valuable. This line counsels finding the middle way between allowing decay to continue and being so severe in correction that you destroy the good along with the bad. Repair requires sensitivity.`,
    `Line 3: Setting right what has been spoiled by the father. There will be a little remorse. No great blame. In eagerly correcting inherited problems, you may act with excess zeal or make minor mistakes. While there may be small regrets, your fundamental intention to restore order is sound. This line acknowledges that the work of repair is imperfect and that some missteps are natural. What matters is the overall direction toward restoration.`,
    `Line 4: Tolerating what has been spoiled by the father. In continuing, one sees humiliation. This line warns against complacency or accepting decay rather than addressing it. If you allow corruption to persist, either through laziness, fear, or misguided tolerance, shame will follow. Sometimes the most difficult aspect of correction is simply beginning the work. Avoiding necessary repairs leads to greater deterioration and eventual disgrace.`,
    `Line 5: Setting right what has been spoiled by the father. One meets with praise. From a position of authority, successfully addressing inherited problems brings recognition and honor. This line represents competent leadership that takes responsibility for repairing what previous administrations neglected or corrupted. Through careful, thorough work, you restore order and earn genuine respect for having tackled difficult but necessary tasks.`,
    `Line 6: One does not serve kings and princes. One sets himself higher goals. At the completion of Work on What Has Been Spoiled, you may choose to withdraw from worldly affairs to pursue spiritual or philosophical aims. Having done the work of restoration, you move beyond social obligations to contemplate higher truths. This line suggests that the ultimate correction is inner transformation rather than external reform.`,
  ],
  [19]: [
    `Line 1: Joint approach. Perseverance brings good fortune. At the beginning of Approach, advance together with others who share your intentions. Collective movement creates positive momentum and mutual support. This line emphasizes that the advancing forces are multiple, not solitary. When you approach opportunities in alliance with like-minded people, success becomes more certain through shared commitment.`,
    `Line 2: Joint approach. Good fortune. Everything furthers. In a supportive position, your participation in collective advancement brings excellent results. When you align with positive forces and contribute your energy to forward movement, everything flows favorably. This line indicates a time of easy progress where circumstances naturally support your efforts and cooperation yields abundant benefit.`,
    `Line 3: Comfortable approach. Nothing that would further. If one is induced to grieve over it, one becomes free of blame. As Approach continues, there is danger of becoming too comfortable or complacent. Easy progress can lead to carelessness or presumption. This line warns that thoughtless advancement brings no real benefit. However, if you recognize this tendency and feel appropriate concern, you can correct your attitude and avoid error. Mindfulness restores proper approach.`,
    `Line 4: Complete approach. No blame. From a position of responsibility, fully commit to forward movement without reservation or half-measures. Complete engagement in approaching opportunities or challenges brings success without error. This line represents wholehearted participation in the advancing energy of the times. Your full investment of attention and effort is appropriate and beneficial.`,
    `Line 5: Wise approach. This is right for a great prince. Good fortune. From the highest position, approach with wisdom and discernment. The leader who advances carefully, choosing appropriate advisors and maintaining clear judgment, creates fortunate outcomes for all. This line depicts ideal leadership during times of approach - combining forward movement with thoughtful consideration, welcoming growth while maintaining guidance and oversight.`,
    `Line 6: Greathearted approach. Good fortune. No blame. At the culmination of Approach, advance with magnanimity and generous spirit. Your broad-minded, inclusive attitude creates the best possible outcome. This line suggests that the greatest approach is one characterized by openness, compassion, and the absence of narrow self-interest. When you approach opportunities or people with genuine goodwill, you create lasting positive connections.`,
  ],
  [20]: [
    `Line 1: Boyish contemplation. For an inferior person, no blame. For a superior person, humiliation. At the beginning of Contemplation, superficial observation may be excusable for the inexperienced but inadequate for those who should know better. This line distinguishes between the naive glance of the immature and the shallow perception of those who should have developed depth. If you are capable of genuine contemplation but settle for surface understanding, this brings shame. Strive for deeper perception appropriate to your capacity.`,
    `Line 2: Contemplation through the crack of the door. Furthering for the perseverance of a woman. Your view is limited, seeing only a narrow slice of reality. While this restricted perspective has its place - like the traditional woman who managed her household sphere - it is inadequate for broader understanding. This line suggests that you currently lack comprehensive vision. Recognize the limitations of your viewpoint rather than assuming you see the whole picture.`,
    `Line 3: Contemplation of my life decides the choice between advance and retreat. This line marks the crucial moment of self-examination. By honestly observing the patterns of your life, you gain clarity about whether to move forward or pull back. Contemplation here becomes deeply personal and practical - understanding yourself guides your decisions. This is the turning point where observation translates into wisdom about action.`,
    `Line 4: Contemplation of the light of the kingdom. It furthers one to act as the guest of a king. From a position of insight, you perceive how the whole society or system functions. This comprehensive understanding makes you valuable as an advisor to leadership. This line represents the contemplative person whose deep observation qualifies them to guide those in power. Your clarity of vision becomes a resource for the community.`,
    `Line 5: Contemplation of my life. The superior person is without blame. From the position of leadership, continuously examine your own conduct and its effects. The leader who maintains self-awareness and reflects on their impact remains blameless. This line emphasizes that those who influence others must be especially vigilant in self-contemplation, ensuring their example is worthy of emulation.`,
    `Line 6: Contemplation of his life. The superior person is without blame. At the completion of Contemplation, you observe not just yourself but your entire life pattern and legacy. This highest form of contemplation sees oneself as others see you, understanding your life's meaning and impact. For the person of character who has lived with integrity, this final contemplation brings no regret - only the clarity of a life well-observed and well-lived.`,
  ],
  [21]: [
    `Line 1: His feet are fastened in the stocks, so that his toes disappear. No blame. At the beginning of Biting Through, minor punishment or restraint prevents worse offenses. The stock that imprisons the feet is a warning that stops wrongdoing before it escalates. This line teaches that early intervention and measured correction prevent serious harm. Small penalties applied at the right time serve justice without cruelty.`,
    `Line 2: Bites through tender meat, so that the nose disappears. No blame. The offense is not severe, and cutting through it is relatively easy, though there may be some embarrassment (the nose symbolizes pride). This line indicates that dealing with the problem, while perhaps causing minor humiliation, is straightforward and brings no real harm. The obstruction yields readily to decisive action.`,
    `Line 3: Bites on old dried meat and strikes on something poisonous. Slight humiliation. No blame. Here the problem is tougher and more toxic than expected. Attempting to bite through, you encounter difficulty and perhaps a bitter reaction. This line acknowledges that some obstructions resist easy removal and may cause temporary setback. However, the attempt to address the problem is still correct, even if challenging.`,
    `Line 4: Bites on dried gristly meat. Receives metal arrows. It furthers one to be mindful of difficulties and to be persevering. Good fortune. From a position of responsibility, you face significant resistance when trying to remove obstacles. The dried gristly meat is tough, and you need strong tools (metal arrows) to penetrate it. This line counsels awareness of the difficulty and persistent, well-armed effort. Through acknowledging challenges and maintaining determination, you eventually succeed.`,
    `Line 5: Bites on dried lean meat. Receives yellow gold. To be mindful of danger. No blame. From the position of authority, you must make difficult decisions that carry risk. The yellow gold represents clarity and correctness of judgment. This line indicates that when you act from a place of conscious awareness of danger, making hard choices that are nevertheless right, you remain without blame. Just authority requires both strength and careful consideration.`,
    `Line 6: His neck is fastened in the wooden cangue, so that his ears disappear. Misfortune. At the extreme of Biting Through, punishment becomes excessive. The criminal who refuses to listen (ears disappearing) faces severe consequences. This line warns against both being the one who ignores repeated warnings and being the one who applies punishment so harshly it becomes unjust. Extremes of either obstinacy or severity bring misfortune.`,
  ],
  [22]: [
    `Line 1: One graces one\'s toes, leaves the carriage, and walks. At the beginning of Grace, prefer simplicity and genuine movement over mere appearance. Rather than riding in style, walk with authentic purpose. This line teaches that true grace begins with substance, not surface. When you choose genuine action over impressive display, you establish a foundation of real value that can later be properly adorned.`,
    `Line 2: Lends grace to the beard on his chin. Your grace is natural and becoming, like a beard that suits the face. This line indicates appropriateness and harmony in your presentation. What you choose to emphasize or adorn fits your character and situation. There is no straining for effect, just suitable expression of your nature through form.`,
    `Line 3: Graceful and moist. Constant perseverance brings good fortune. Grace reaches its ideal when it has the quality of fresh vitality, like something well-nourished and alive. This line suggests that true refinement is not dry formality but vibrant, appealing expression that attracts and nourishes. By maintaining this quality consistently, you create lasting positive impressions and relationships.`,
    `Line 4: Grace or simplicity? A white horse comes as if on wings. One is not a robber, one will woo at the right time. Here you face the question: elaborate grace or simple directness? The white horse approaching swiftly represents sincere intention arriving with urgency. This line teaches that when your purposes are pure and your timing is right, straightforward approach may be better than elaborate courtesy. Know when grace serves connection and when simplicity does.`,
    `Line 5: Grace in the hills and gardens. The roll of silk is meager and small. Humiliation. But in the end, good fortune. From a position of influence, you may lack the resources for impressive display. Your offering seems inadequate compared to what is expected. This line acknowledges the embarrassment of having more position than means. However, it promises that sincere effort, even with limited resources, ultimately brings good results. Inner worth eventually reveals itself beyond surface limitations.`,
    `Line 6: Simple grace. No blame. At the completion of Grace, return to simplicity. The highest refinement is that which has transcended ornamentation to arrive at essential elegance. This line teaches that the purpose of cultivating grace is not to accumulate more elaborate display but to arrive at simplicity that expresses truth perfectly. Pure, unadorned presence becomes the ultimate grace.`,
  ],
  [23]: [
    `Line 1: The leg of the bed is split. Those who persevere are destroyed. Misfortune. At the beginning of Splitting Apart, the foundation begins to give way. If you try to preserve what is crumbling through stubborn perseverance, you will be caught in the collapse. This line warns that when decay is in its early stages, resistance only causes harm. Recognize the process of dissolution and adjust accordingly rather than clinging to what cannot be maintained.`,
    `Line 2: The bed is split at the edge. Those who persevere are destroyed. Misfortune. The decay spreads from the foundation to the structure itself. Continuing to rely on what is disintegrating brings increasing danger. This line emphasizes that Splitting Apart is a progressive process - what begins at the foundation eventually affects all that rests upon it. Withdraw from dependence on failing structures before they take you down with them.`,
    `Line 3: One splits with them. No blame. At the midpoint of dissolution, you recognize the need to separate yourself from what or whom is falling apart. This is not betrayal but necessary self-preservation. This line teaches that there are times when splitting away from the collective fate is the only wise course. By distinguishing yourself from the general decline, you preserve your integrity and ability to rebuild later.`,
    `Line 4: The bed is split up to the skin. Misfortune. From a position of responsibility, the decay has reached critical levels, touching you personally and inescapably. You can no longer avoid being affected. This line acknowledges that sometimes Splitting Apart involves you directly, and you must endure the misfortune that comes from being part of what is disintegrating. All you can do is maintain inner truth while outer circumstances crumble.`,
    `Line 5: A shoal of fishes. Favor comes through the court ladies. Everything acts to further. Unexpectedly, in the midst of decay, new life and favor appear. Like fish swimming together, people who have maintained their principles attract attention and support. This line represents the turning point when those who held firm during difficult times begin to be recognized and receive help. The tide begins to turn in favor of what is good.`,
    `Line 6: There is a large fruit still uneaten. The superior person obtains a carriage. The house of the inferior person is split apart. At the completion of Splitting Apart, there is differentiation: those of character receive reward and support, while those lacking substance face complete dissolution. This line promises that what is fundamentally sound survives and even flourishes after the period of general decay. The splitting apart ultimately separates the valuable from the worthless, the enduring from the temporary.`,
  ],
  [24]: [
    `Line 1: Return from a short distance. No need for remorse. Supreme good fortune. At the beginning of Return, you have strayed only slightly from the path and quickly recognize your error. Immediate course correction prevents serious consequences. This line teaches that the ability to recognize mistakes early and return to the right way is a mark of wisdom. The shorter the deviation, the easier the return and the greater the fortune.`,
    `Line 2: Quiet return. Good fortune. You return to the proper path calmly and without drama. This humble, composed correction of direction brings good results. This line emphasizes that Return need not be dramatic or accompanied by great show. The quiet recognition of what is right and gentle realignment with it creates the conditions for renewed growth. Peaceful return is deeply fortunate.`,
    `Line 3: Repeated return. Danger. No blame. You find yourself falling into the same errors repeatedly, returning again and again to correct course. While this pattern contains danger, if you continue to recognize your mistakes and return to principle each time, you remain without fundamental blame. This line acknowledges that some people's path involves multiple returns before fully establishing themselves in the right way. Keep returning.`,
    `Line 4: Walking in the midst of others, one returns alone. From a position of responsibility, you recognize the right path even when those around you do not. Your solitary return requires courage and conviction. This line teaches that sometimes Return means going against the prevailing current, trusting your own recognition of what is correct. Though you walk alone in returning, your example may later guide others.`,
    `Line 5: Noble-hearted return. No remorse. From the highest position, you return to principle with generosity and without self-reproach. This represents mature correction, where you acknowledge the need to return without dwelling on past errors. This line depicts the ideal of Return - graceful realignment with what is right, motivated by genuine understanding rather than shame or compulsion.`,
    `Line 6: Missing the return. Misfortune. Disaster from within and without. Using armies, one will in the end suffer a great defeat. For ten years, it will not be possible to attack. Calamity. At the extreme, you miss the opportunity to return and face severe consequences. When the moment for renewal passes unused, both internal and external disasters follow. This line warns that Return has its season - there comes a point when the window closes and the cost of having failed to return becomes catastrophic. Do not let this moment pass.`,
  ],
}
