import { HexagramDefinition } from '@/app/oracle/types'

export const hexagramDescriptions_57_64: Record<HexagramDefinition['number'], string> = {
  [57]: `Sun, The Gentle Wind, embodies the power of subtle, persistent influence. Like the wind that gradually shapes mountains or the roots that penetrate deep into earth, this hexagram teaches the virtue of gentle penetration over forceful action. The image is of wind doubled, moving continuously without resistance, suggesting that patience and consistency achieve what force cannot. The Judgment declares supreme success through small things, emphasizing the importance of direction and gentle persistence. In divination, this hexagram counsels working steadily toward your goals through subtle influence rather than direct confrontation. Adaptability is key—like the wind that finds its way around obstacles rather than battering against them. This is a time for diplomacy, tact, and patient effort. The ancient wisdom here speaks to the power of gentleness: what appears weak and yielding can penetrate the hardest substance when applied with constancy and clear intention.`,
  [58]: `Tui, The Joyous Lake, represents pure joy, delight, and harmonious exchange. The image is of two lakes joined together, reflecting and enriching each other, symbolizing the joy that comes from genuine connection and mutual encouragement. The Judgment promises success through inner cheerfulness and strength, suggesting that true joy springs from a firm foundation rather than superficial pleasure. This hexagram distinguishes between authentic joy—which inspires and uplifts—and mere excitement or indulgence. In divination, this indicates a time of harmonious relationships, productive discussions, and the power of encouragement. However, the lake has boundaries; joy must be balanced with wisdom and not lead to excess. This is an auspicious time for teaching, learning, and cooperative endeavors where people inspire each other to excellence. The hexagram reminds us that genuine joy is contagious and creates ripples that extend far beyond their source, but such joy must be rooted in sincerity and inner strength.`,
  [59]: `Huan, Dispersion, represents the scattering of obstacles and the dissolution of divisions that have kept people or energies apart. The image is of wind moving over water, dispersing mists and barriers, clearing the way for reunion and fresh perspective. The Judgment declares success through religious devotion and crossing great waters, suggesting that dissolving rigid patterns requires both spiritual insight and willingness to venture into the unknown. In traditional interpretation, this hexagram often refers to dispersing egotism, selfishness, or hardened attitudes that prevent unity. In divination, this signals a time to break up stagnation, overcome isolation, and dissolve barriers between people. Ancient kings made offerings to temples under this sign, recognizing that dispersion of obstacles requires dedication to something greater than self-interest. This is favorable for bringing scattered elements together, healing divisions, or breaking free from limiting circumstances. The hexagram teaches that what seems like dissolution is often preparation for new integration at a higher level.`,
  [60]: `Chieh, Limitation, teaches the wisdom of boundaries, moderation, and accepting necessary constraints. The image is of water above the lake—the lake contains water within defined shores, preventing both excess and depletion. The Judgment warns that limitation can be carried too far; even necessary restrictions must not become harsh or oppressive. This hexagram embodies the principle that appropriate limits create freedom rather than restrict it, just as musical scales create the structure for infinite melodies. In divination, this indicates a time to establish clear boundaries, practice moderation, and work within given constraints rather than fighting against them. However, the hexagram cautions against excessive limitation that becomes bitter or life-denying. The ancient wisdom here distinguishes between limitations that serve life and those that diminish it. This is favorable for creating sustainable systems, establishing healthy routines, and practicing wise economy. The teaching emphasizes that accepting natural limits with good humor allows energies to be focused and used effectively rather than dispersed wastefully.`,
  [61]: `Chung Fu, Inner Truth, represents the power of sincerity, genuine understanding that bridges all divisions. The image is of wind over the lake—the wind moves the water, suggesting how inner truth moves hearts and minds. The Judgment promises success with even difficult people or situations, declaring that sincerity makes it possible to cross great waters. This hexagram points to truth that comes from the heart rather than merely from the intellect, creating understanding that transcends words. In traditional interpretation, Inner Truth has the power to influence even pigs and fish—representing the most difficult to reach—because it operates at a deeper level than persuasion or argument. In divination, this is highly favorable for important communications, negotiations, and situations requiring trust. The hexagram counsels that genuine sincerity and inner truthfulness create almost magical influence, opening doors that force cannot budge. However, this truth must be authentic; any hint of manipulation or dishonesty breaks the connection. This is a time when speaking from the heart, acting with integrity, and trusting your genuine perceptions will prove most effective.`,
  [62]: `Hsiao Kuo, Small Exceeding, indicates a time when small things take precedence and modest actions yield better results than grand gestures. The image is of thunder on the mountain—impressive sound in the heights but little impact below, suggesting that circumstances favor humility and attention to detail over ambitious display. The Judgment advises success in small matters while cautioning against undertaking great things. This hexagram teaches that there are times when exceeding in small ways—being extra careful, more modest, more thorough than usual—is the appropriate response to conditions. In divination, this counsels focusing on immediate, practical matters rather than large-scale plans. Pay exceptional attention to details, be more respectful than required, be more cautious than seems necessary. This is not the time for major undertakings or grand initiatives, but rather for perfecting small things and attending to duties that might usually seem minor. The ancient wisdom suggests that flying low when conditions favor it is not weakness but wisdom—the bird that flies too high in wrong conditions meets with misfortune.`,
  [63]: `Chi Chi, After Completion, represents the moment just after success has been achieved, when all elements are in their proper places. The image shows water above fire, each in its correct position, symbolizing perfect balance and order. The Judgment promises initial success but warns of disorder in the end, teaching that completion contains the seeds of new beginning. This hexagram reminds us that when everything is accomplished and in place, the natural tendency is toward entropy and decline. Success requires continued vigilance and maintenance. The wise person remains alert at the moment of completion, knowing that complacency leads to deterioration. When all is in order, small matters still require attention to preserve what has been achieved.\n\nIn divination, After Completion indicates that you have achieved your immediate goals or that a situation has reached fruition. This is a favorable hexagram, but it counsels against relaxing your efforts or assuming that success will maintain itself. The completion of one phase naturally leads to the beginning of another. Guard against overconfidence and continue to attend to details. This is an excellent time for consolidation, preservation, and careful management of what you have accomplished. Remember that the height of achievement is also the moment of greatest vulnerability to decline. Maintain your principles, stay alert to small changes, and be prepared to adapt as new cycles begin.`,
  [64]: `Wei Chi, Before Completion, represents the moment just before success, when the goal is nearly in sight but not yet attained. The image shows fire above water, each element striving toward the other but not yet in proper relationship. The Judgment promises success but warns that one must be careful like a young fox crossing ice—confident enough to proceed but cautious enough to avoid breaking through. This hexagram teaches that the final stages of any endeavor require particular care and attention. Premature celebration or relaxed effort at this stage can snatch defeat from the jaws of victory.\n\nIn divination, Before Completion indicates that you are very close to your goal but must not let up in your efforts. This is not the time to become careless or to assume success is inevitable. The transition from incomplete to complete requires the same discipline and care that brought you this far. Like the young fox testing each step on the frozen river, proceed with confidence but maintain vigilance. All the elements are present for success, but they have not yet come together in final form. Continue your careful work, stay focused on your objective, and do not be distracted by the nearness of completion. This hexagram actually represents great potential—with proper attention and sustained effort, success is highly likely. The key is to finish strong rather than stumbling at the threshold.`,
}

// Changing line descriptions for hexagrams 57-64
// Each hexagram has 6 lines (bottom to top: line1 through line6)
export const changingLineDescriptions_57_64: Record<HexagramDefinition['number'], string[]> = {
  [57]: [
    `Line 1: Advancing and retreating like the wind brings confusion. The military discipline of a warrior is needed. At the beginning of gentle penetration, you may waver in your approach, alternating between moving forward and pulling back. This inconsistency weakens your influence. The line counsels finding clear direction and maintaining it with disciplined consistency. Like a soldier following orders, commit to your chosen path and follow through with determination. Indecision at this stage undermines the power of gentle persistence that this hexagram represents.`,
    `Line 2: Penetration under the bed, with priests and magicians in great number. Good fortune, no blame. This line suggests that gentle influence must reach even the hidden and unconscious levels. You may need to employ various methods and seek help from those with special skills or insight. The line indicates success through thoroughness and willingness to use unconventional approaches. Don't just work on the surface—penetrate to the deep, hidden roots of the matter. This thoroughness, though it may seem excessive, brings good results.`,
    `Line 3: Repeated penetration brings humiliation. When gentle persistence becomes obsessive repetition, it loses its power and dignity. This line warns against pushing too hard even with gentle methods. If your approach is not working despite sustained effort, continuing the same pattern brings embarrassment and failure. Recognize when gentle persistence has crossed into ineffective nagging or manipulation. Sometimes wisdom lies in changing your approach or accepting that this particular path is not working.`,
    `Line 4: Remorse vanishes. One bags three kinds of game. When gentle penetration is properly timed and directed, it brings abundant success. This line indicates a turning point where previous doubts or difficulties dissolve, replaced by clear achievement. Your patient, subtle approach now yields concrete results, possibly in multiple areas or forms. The metaphor of hunting successfully suggests that your careful, strategic method has borne fruit. Regrets about taking the gentle path are eliminated by obvious success.`,
    `Line 5: Perseverance brings good fortune, remorse vanishes. Nothing that does not further. Undertakings bring success. At this position of authority, gentle penetration combined with inner firmness creates ideal conditions. This line promises success through steadfast application of subtle influence from a position of responsibility. Initial uncertainties give way to confidence as your approach proves effective. Whatever you undertake with this combination of gentleness and persistence will succeed. This is an extremely favorable position for leadership that guides through influence rather than force.`,
    `Line 6: Penetration under the bed causes loss of property and weapons. Perseverance brings misfortune. At the extreme of gentle penetration, you have gone too far, probing into areas that should remain private or losing your ground by being too yielding. This line warns that excessive gentleness becomes weakness, and too much penetration becomes violation. You may have given up your own position and resources through over-accommodation. The counsel is to recognize when gentle influence has become self-defeating and to reestablish proper boundaries and firmness.`,
  ],
  [58]: [
    `Line 1: Contented joyousness brings good fortune. This line represents joy that is self-contained and independent, arising from inner harmony rather than external circumstances. When your joy comes from within and needs no validation or stimulation from outside, it provides a stable foundation for action. This authentic, quiet joy brings natural good fortune because it does not depend on conditions that might change. Cultivate this inner contentment, and it will support all your endeavors.`,
    `Line 2: Sincere joyousness brings good fortune, remorse vanishes. True joy based on sincerity and authenticity dissolves doubts and previous difficulties. This line counsels that your joy should come from genuine feeling rather than forced cheerfulness or social obligation. When your delight is authentic, it naturally attracts good fortune and causes regrets to disappear. Do not fake enthusiasm or pretend to joy you don't feel—seek and express genuine pleasure and encouragement.`,
    `Line 3: Coming joyousness brings misfortune. This line warns against seeking joy from external sources or through approaches that are coming toward you from outside. When you depend on others or circumstances to provide your happiness, or when you pursue pleasure for its own sake, misfortune results. Joy that must be constantly stimulated or that comes from questionable sources leads away from true contentment. The warning is against shallow pleasure-seeking and dependence on external validation for your emotional state.`,
    `Line 4: Joyousness that is weighed brings restlessness. Good fortune lies ahead. When you are calculating about your joy, weighing options and considering which path will bring more pleasure, you lose spontaneity and create inner tension. This line suggests you are in a position where you must choose between different sources of satisfaction. The disquiet comes from divided attention and consideration of lesser versus greater goods. The promise is that if you choose correctly—opting for higher joy over lower pleasure—good fortune follows. Trust in what brings genuine, sustainable joy.`,
    `Line 5: Sincerity toward disintegrating things is dangerous. This line warns about placing your trust and joy in things that are deteriorating or in relationships and situations that are falling apart. From a position of influence, you must recognize when to withdraw your confidence and encouragement from what cannot be sustained. Remaining cheerful and supportive toward disintegrating situations exposes you to danger. Discernment is required—know when to maintain joy and encouragement and when to acknowledge decline and protect yourself.`,
    `Line 6: Seductive joyousness. At the extreme of this hexagram, joy becomes mere seduction, manipulation through pleasure, or addiction to stimulation. This line represents joy that has lost its moorings in sincerity and truth, becoming instead a tool for influence or an end in itself. While not specifically promising misfortune, this line suggests emptiness and lack of real substance. The warning is against using joy manipulatively or pursuing pleasure divorced from meaning and authenticity.`,
  ],
  [59]: [
    `Line 1: Rescue comes through the strength of a horse. Good fortune. At the first stage of dispersion, swift action and strong assistance prevent hardening or separation from becoming entrenched. Like a horse that can carry you quickly away from danger, immediate and forceful response to early signs of isolation or rigidity brings good fortune. Don't delay when you first notice barriers forming or divisions beginning. Address them promptly with strength and decisive action.`,
    `Line 2: At the dissolution, he hurries to his support. Remorse vanishes. When you recognize dispersion or separation occurring, the correct response is to quickly return to your foundation, your support, your center. This might mean reconnecting with core values, returning to trusted relationships, or reestablishing connection with what grounds you. This swift return to support causes regret and difficulty to dissolve. Don't wait or hesitate when you feel barriers forming—immediately reconnect with your sources of strength and stability.`,
    `Line 3: He dissolves his self. No remorse. This line teaches the profound wisdom of dissolving ego to overcome separation. When you let go of self-centered concerns, rigid positions, and personal pride, barriers naturally fall away. This is not loss but liberation—by releasing identification with narrow self-interest, you become free to connect with larger realities and communities. There is no cause for regret in this dissolution of ego boundaries; it is the gateway to genuine unity and broader perspective.`,
    `Line 4: He dissolves his bond with his group. Supreme good fortune. Dissolution indeed! Something that an ordinary person would not think of. From a position of responsibility, you may need to break with group thinking, partisan positions, or factional loyalties to serve a higher good. This line indicates the courage to transcend limited associations for the sake of broader unity or higher principles. While this might seem like betrayal from a conventional view, it actually represents supreme good fortune and wisdom. Sometimes dispersion of narrow bonds is necessary to create more authentic and comprehensive connections.`,
    `Line 5: Dissolving sweat like great crying out. Dissolution—a king abides without blame. This line describes a leader who disperses accumulations and releases resources like sweat pouring out or a great proclamation ringing forth. A person in authority must sometimes break up concentrations of wealth, power, or rigid structures to create flow and renewal. This dissolution from a position of leadership brings no blame when done for the right reasons—to prevent stagnation, to share abundance, or to break down barriers that prevent unity. The leader who can do this serves the greater good.`,
    `Line 6: He dissolves his blood. Going and staying away, keeping at a distance brings no blame. At the ultimate point of dispersion, you must distance yourself from injury, conflict, or situations that would wound you. "Dissolving blood" suggests ending situations that have become harmful or dangerous. The counsel is clear: in some circumstances, the wisest response is to remove yourself, stay away, and maintain distance. This is not failure but wisdom—knowing when dispersion means simply getting out of harm's way.`,
  ],
  [60]: [
    `Line 1: Not going out of the gate and the courtyard is without blame. At the beginning, accepting natural limits and not overextending brings no trouble. Like staying within familiar boundaries until you understand the territory, this line counsels working within known limits rather than immediately testing or expanding them. There is wisdom in restraint and in respecting existing boundaries as you begin to understand what limitations are appropriate. Premature expansion or testing of limits would bring difficulty; accepting initial constraints brings security.`,
    `Line 2: Not going out of the gate and the courtyard brings misfortune. Here the same action that was wise in line one becomes problematic. When the time requires action and engagement, remaining too constrained by limits brings bad results. There is a season for accepting boundaries and a season for extending beyond them. This line indicates that the time has come to move beyond the courtyard—continued restriction now prevents necessary development and engagement with the wider world. Limitation has become excessive constraint.`,
    `Line 3: He who knows no limitation will have cause to lament. Nothing brings blame. This line warns that failing to accept appropriate limits leads to sorrow. If you do not impose necessary discipline and boundaries, natural consequences will teach the lesson through hardship. However, there is "no blame" because this is how we learn—through experiencing the results of unlimited behavior. The message is clear: either choose appropriate limitations consciously, or learn their necessity through painful experience. Wisdom lies in accepting limits before you are forced to learn their value.`,
    `Line 4: Contented limitation brings success. When you accept limitations with good humor and work productively within them, success naturally follows. This line represents the positive aspect of limitation—the focus and effectiveness that come from accepting constraints rather than chafing against them. Like an artist working within the limitations of their medium to create something beautiful, you find that boundaries provide structure for achievement rather than obstacles to it. Peaceful acceptance of necessary limits brings accomplishment.`,
    `Line 5: Sweet limitation brings good fortune. Going brings esteem. From a position of authority, you establish limitations that are firm but not harsh, clear but not oppressive. These "sweet limitations"—boundaries that serve life and growth rather than merely restricting it—bring good fortune. When you must carry out or enforce these limits, you are respected for your wisdom and fairness. This line represents ideal limitation: clear, necessary, and accepted because its value is recognized. Leadership that can create such boundaries is esteemed.`,
    `Line 6: Galling limitation brings misfortune. Perseverance brings remorse. At the extreme, limitation becomes bitter, harsh, and counterproductive. When boundaries are too tight, discipline too severe, or restrictions maintained past their usefulness, they create misfortune. Persisting in excessive limitation only creates regret. This line counsels recognizing when limits have become oppressive and easing restrictions that have turned bitter. Rigid adherence to excessive limitation defeats the purpose of healthy boundaries and must be corrected.`,
  ],
  [61]: [
    `Line 1: Being prepared brings good fortune. If there are ulterior designs, there is disquiet. Inner truth begins with preparation and purity of motive. When you prepare yourself inwardly—clarifying your intentions, calming your mind, establishing sincere presence—you create the foundation for genuine connection and influence. However, if you harbor hidden agendas or ulterior motives, this creates inner disturbance that undermines truth. The line counsels careful preparation combined with absolute sincerity of purpose. Mixed motives destroy the power of inner truth.`,
    `Line 2: A crane calling in the shade, its young answers it. I have a good goblet; I will share it with you. This beautiful image shows how inner truth creates natural resonance and response. When you speak from genuine feeling and truth, those who share your nature respond spontaneously, like young birds answering their parent's call. The willingness to share what is valuable—represented by the goblet—demonstrates the open-handed quality of true sincerity. Inner truth is not hoarded but naturally shared, and this generosity creates connection and mutual response. Your genuine expression will find its echo in others.`,
    `Line 3: He finds a companion. Now he beats the drum, now he stops. Now he sobs, now he sings. When you find a true connection based on inner truth, the relationship has natural fluctuations—moments of celebration and sadness, activity and rest, joy and sorrow. This line suggests you have found or will find a genuine companion, but warns that even true relationships involve emotional variation. Don't expect constant harmony; the authenticity of connection shows itself in the ability to share the full range of human experience. This vulnerability and variation is part of deep truth between people.`,
    `Line 4: The moon nears the full. The horse goes astray. No blame. When inner truth approaches completion or fullness, there may be a natural separation or divergence from former companions or ways. Like horses that wander different paths, or the moon that waxes toward fullness in solitary splendor, this phase of inner truth may involve a drawing away. This brings no blame—it is a natural part of development. As your inner truth deepens and clarifies, some connections may fall away while new ones form. Trust this process of natural selection in relationships and associations.`,
    `Line 5: He possesses truth which links together. No blame. From a position of authority, your inner truth has the power to create bonds and unity among others. This is truth that doesn't just exist within yourself but connects diverse elements into harmony. A leader whose sincerity is evident creates trust and cohesion naturally. This line promises that such unifying truth brings no blame—it is recognized and valued by all. Your authentic presence and sincere intention serve to link people and purposes together in beneficial ways.`,
    `Line 6: Penetrating cries rise to heaven. Perseverance brings misfortune. At the extreme, what began as inner truth can become excessive emotionality or forcing of sincerity. When attempts at genuine expression become dramatic displays or when you try too hard to prove your sincerity, the truth is lost. This line warns against performative truth—sincerity that calls attention to itself defeats its own purpose. If you must persistently proclaim your truthfulness or constantly demonstrate your sincerity, something is wrong. Real inner truth is quiet and self-evident, not proclaimed loudly or proven through persevering effort. Excessive display undermines authentic presence.`,
  ],
  [62]: [
    `Line 1: The bird meets with misfortune in flight. This line warns that trying to soar too high or move too boldly at the beginning brings trouble. When the hexagram counsels small exceeding—extraordinary care and modesty—attempting anything grand or ambitious meets with misfortune. Like a bird flying into danger, premature boldness brings harm. The counsel is clear: start very small, be exceptionally modest, and resist any temptation to grand action or display. The conditions demand humility and caution beyond what might usually be necessary.`,
    `Line 2: Passing by one's ancestor and meeting one's ancestress. Not reaching the prince but meeting the official. No blame. This line suggests that in circumstances requiring small exceeding, you may not reach the highest levels of authority or most ambitious goals, but you can accomplish something of value at a more modest level. Missing the ultimate target but achieving a lesser goal is appropriate now. Don't insist on going all the way to the top or achieving maximum success—accept what can be reasonably accomplished through modest effort. Meeting the official rather than the prince, connecting with the ancestress rather than the ancestor, represents appropriate adjustment of ambition to circumstances.`,
    `Line 3: If one is not extremely careful, somebody may come up from behind and strike him. Misfortune. This line issues a serious warning: the situation demands exceptional caution and watchfulness. If you do not exceed normal carefulness—if you are only ordinarily careful—you leave yourself vulnerable to unexpected attack or harm. The circumstances require you to be more watchful, more protective, more defensive than usual. Don't assume normal vigilance is sufficient. Guard your back, anticipate threats, and be extraordinarily careful in all dealings. Failure to exceed normal caution brings real misfortune.`,
    `Line 4: No blame. Without passing him, one meets him. Going brings danger. One must be on guard. Do not act. Persevere. This line counsels absolute restraint and exceptional defensiveness. Rather than seeking to advance or pass beyond current position, you should simply hold your ground and maintain careful watch. Any attempt to move forward or take action brings danger. What is required is exceeding in caution, defensiveness, and stillness. Do not mistake this for permanent passivity—it is an appropriate response to current conditions that demand extraordinary care. Persist in watchful waiting rather than any form of advance.`,
    `Line 5: Dense clouds, no rain from our western region. The prince shoots and hits what is in the cave. From a position of authority, you can achieve precise, limited objectives through careful, targeted action. The image suggests that grand results (rain over the whole region) are not possible, but specific, well-aimed efforts succeed. Like an archer shooting into a cave—a very precise and limited target—you can accomplish particular goals through exact, modest action. This line offers hope: while great sweeping success is not available, focused effort on small objectives can succeed. Be like the prince whose shot is accurate and specific rather than attempting broad achievements.`,
    `Line 6: Passing him by, not meeting him. The flying bird leaves him. Misfortune. Calamity and injury. At the extreme of small exceeding, you may go beyond appropriate modesty into excessive withdrawal or avoidance. Failing to make necessary contact or connection, retreating too far, or being so modest that you miss important opportunities brings misfortune. Like a bird that flies away entirely, you may have separated yourself too completely from what matters. This line warns that exceeding can go too far even in the direction of caution and modesty—there are times when some engagement is necessary despite the general counsel toward restraint. Balance is required even in practicing small exceeding.`,
  ],
  [63]: [
    `Line 1: He brakes his wheels. Gets his tail in the water. No blame. At the beginning of After Completion, immediately apply restraint to prevent overextension. Like a chariot driver who brakes at the start of the journey, or a fox whose tail gets wet while crossing the stream carefully, this line counsels immediate caution despite having achieved completion. While there is minor difficulty (the wet tail), there is no blame because you are properly cautious. Don't let the completion of one phase lead to careless rushing into the next. Restraint right from the beginning of the new cycle prevents larger problems.`,
    `Line 2: The woman loses the curtain of her carriage. Do not pursue it; on the seventh day you will get it. This line teaches patience and trust when small losses occur after completion. The lost curtain represents a minor setback or the loss of some protective covering. The counsel is not to chase after it anxiously or try to immediately recover what was lost. If you remain calm and continue your proper course, what was lost will return naturally in due time (symbolized by the seventh day). This line reminds us that small disturbances after achievement are normal and self-correcting; don't make them worse through anxious overreaction.`,
    `Line 3: The Illustrious Ancestor attacks the devil's country. Three years are required to conquer it. Inferior people must not be employed. Even after completion, there may be remaining pockets of disorder or negative influences that require extended effort to fully overcome. This line suggests a long campaign against lingering problems, requiring sustained effort over a lengthy period (three years symbolizing a substantial duration). However, it warns against using questionable people or methods in this campaign—maintain high standards even when dealing with low matters. Complete success requires time and should not be rushed or compromised by employing inferior means. Patience and proper methods will eventually prevail.`,
    `Line 4: The finest clothes turn to rags. Be on guard all day. From a position of stability after completion, remain constantly vigilant because decline can begin subtly. Even fine garments can become rags through wear and time; even solid achievements can deteriorate through neglect. This line counsels unceasing watchfulness and maintenance of what has been achieved. Don't relax into complacency. The "guard" here is not military defense but careful attention to preservation and maintenance. Like someone constantly aware that their fine clothes might tear or become soiled, stay alert to the early signs of deterioration.`,
    `Line 5: The neighbor in the east who slaughters an ox receives less blessing than the neighbor in the west with his small offering at his time of sincerity. From a high position after completion, genuine sincerity in small matters brings more blessing than grand gestures without true feeling. The neighbor who makes an elaborate sacrifice (slaughtering an ox) receives less spiritual benefit than the one who makes a simple, sincere offering at the proper moment. This line teaches that after achievement, what matters is authenticity and proper timing rather than the scale of action. A leader who maintains simple sincerity is more blessed than one who makes grand shows. Quality of presence matters more than quantity of display.`,
    `Line 6: He gets his head in the water. Danger. At the extreme of After Completion, carelessness or overconfidence leads to serious trouble. Unlike line one where only the tail got wet due to proper caution, here the head goes under—representing complete immersion in danger. This is the warning that completion ultimately gives way to its opposite if vigilance is abandoned. Having crossed successfully and completed your goal, you may become so confident that you take foolish risks or stop paying attention. The danger is real and serious. This line marks the transition point where After Completion begins to turn into Before Completion once again—the eternal cycle of change.`,
  ],
  [64]: [
    `Line 1: He gets his tail in the water. Humiliation. At the beginning of Before Completion, being too eager and careless brings embarrassment. Like a young fox whose tail gets wet at the start of crossing the frozen stream, this shows premature confidence or insufficient care at the outset. While not disastrous, it is humiliating and suggests you have not properly assessed the situation. The lesson is to be more careful at the beginning—the crossing is not yet made, so extra caution is required even in the first steps. Don't let eagerness for completion override necessary prudence at the start.`,
    `Line 2: He brakes his wheels. Perseverance brings good fortune. In the second stage before completion, deliberate restraint and patience bring positive results. Like a chariot driver who applies the brakes to maintain control, you must consciously slow yourself and proceed with steady care. The promise is that this perseverance in careful, measured progress brings good fortune. Don't rush toward the completion you can see ahead. Maintain discipline and restraint as you move forward, and success will come through this sustained carefulness. The temptation to speed up must be resisted.`,
    `Line 3: Before completion, attack brings misfortune. It furthers one to cross the great water. This line presents a paradox: premature aggressive action brings misfortune, yet undertaking great endeavors is favored. The resolution lies in understanding that "attack" represents forcing completion through aggressive push, while "crossing great water" represents accepting the significant challenge while remaining properly cautious. You can and should undertake the major task before you, but not by trying to force premature completion. Take on the challenge with proper respect for its magnitude rather than attempting to shortcut or force your way to the finish. Great undertakings are favored; impatient forcing is not.`,
    `Line 4: Perseverance brings good fortune. Remorse vanishes. Shock, to discipline the devil's country. For three years, great realms are awarded. Before completion, from a position of influence, sustained effort against disorder eventually brings great rewards. This line promises that persistent, properly directed effort overcomes resistance and brings significant achievement (great realms). However, it requires extended time (three years, symbolizing substantial duration) and involves shock or forceful action against negative elements. Previous doubts and difficulties vanish as sustained effort proves successful. This is an encouraging line, suggesting that though completion has not yet occurred, the path forward is clear and the rewards for persistence will be substantial.`,
    `Line 5: Perseverance brings good fortune. No remorse. The light of the superior person is true. Good fortune. From the highest position before completion, steadfast adherence to truth and principle brings certain success without regret. This line represents the ideal approach to the final phase before completion: remain true to your light, maintain your standards, persist in right action. The "light of the superior person" refers to clarity of vision and integrity of character. When these are maintained through the final approach to completion, good fortune is assured and there is no cause for remorse. This is an extremely favorable position—success is virtually certain if you maintain your principles and persist with sincerity.`,
    `Line 6: One has confidence to drink wine. No blame. One wets his head. One loses confidence through drinking. At the ultimate point before completion, you can celebrate with confidence—take some refreshment and enjoyment in anticipation of success. But the line immediately warns: excessive celebration or letting down your guard completely (wetting the head, becoming drunk) causes you to lose the confidence that brought you this far. A little celebration is blameless, but losing yourself in it before completion is actually achieved brings failure at the threshold. This is the final warning: you are not quite there yet. Moderate celebration is appropriate, but maintain enough discipline and focus to actually complete what you have almost finished. Don't fail at the last moment through premature revelry.`,
  ],
}
