import { HexagramDefinition } from '@/app/oracle/types'

// Main hexagram descriptions for hexagrams 49-56
export const hexagramDescriptions_49_56: Record<HexagramDefinition['number'], string> = {
  [49]: `Revolution (Ko) represents radical transformation and renewal. This hexagram symbolizes fire beneath the lake, suggesting fundamental change that comes when the old order has exhausted itself. The Judgment proclaims that revolution brings supreme success when undertaken at the proper time with sincerity and clarity of purpose. Like the changing of seasons, there are moments when sweeping transformation becomes not only necessary but inevitable. However, revolution must be approached with careful preparation and genuine need, not merely for the sake of change itself. This is a time when outdated structures, relationships, or ways of thinking must be shed to make way for the new. The image suggests that successful transformation requires both the passion of fire and the adaptability of water, combining conviction with flexibility.

When Revolution appears in divination, it signals that you are at a critical juncture where significant change is either imminent or necessary. This may involve ending old patterns, reforming existing structures, or completely reimagining your approach to a situation. The hexagram counsels that while revolution can be disruptive and uncomfortable, it becomes essential when circumstances have reached their natural conclusion. The key is timing and authenticity - ensure that change is genuinely required and that you have laid proper groundwork. This is not about impulsive destruction but conscious transformation. Trust that when the moment for change arrives, it will be recognized by all involved, and resistance will naturally diminish.`,
  [50]: `The Cauldron (Ting) represents nourishment, transformation, and the vessel of culture. This hexagram symbolizes the sacrificial vessel used in ancient rituals, suggesting the refinement of raw materials into something of higher value. The Judgment indicates supreme good fortune and success, as the cauldron transforms basic ingredients into nourishment for all. Just as the cauldron sits over fire to cook and transform, this hexagram speaks to the alchemical process of turning ordinary experiences into wisdom, raw talent into skill, and individual efforts into collective benefit. The cauldron also represents tradition, culture, and the passing down of knowledge from one generation to the next. It suggests stability combined with transformation, as the vessel itself remains constant while its contents undergo change.

In divination, The Cauldron indicates a time of spiritual and material nourishment, when your efforts contribute to something greater than yourself. This hexagram often appears when you are in a position to transform resources, knowledge, or experiences into something valuable for your community or when you benefit from the wisdom of tradition. It counsels patience in the transformative process - just as food must simmer and cook properly to nourish, your current endeavors require time and proper attention to reach their full potential. The Cauldron also suggests that you may serve as a vessel for higher purposes, channeling energy or knowledge in ways that benefit others. Pay attention to how you are being nourished and how you nourish others.`,
  [51]: `The Arousing (Chen) represents shock, thunder, and sudden awakening. This hexagram shows thunder doubled, suggesting powerful movement that shakes things up and breaks through inertia. The Judgment teaches that shock brings success through awareness - when thunder rolls, the wise remain composed and alert, using the jolt of awakening to become more conscious. The first shock may cause fear, but it is followed by laughter and relief as understanding dawns. Thunder represents both the terror and exhilaration of sudden change, the moments that shake us from complacency and force us to pay attention. In ancient times, sacrificial offerings would continue even as thunder roared, symbolizing the ability to maintain composure and purpose despite shocking circumstances. The hexagram suggests that disturbance can be beneficial when it awakens dormant potential or reveals what has been hidden.

When The Arousing appears in divination, expect unexpected events that shake your usual patterns and demand immediate attention. This may manifest as sudden news, surprising opportunities, or circumstances that jolt you out of routine thinking. The hexagram counsels that your response to shock matters more than the shock itself - meet unexpected events with presence of mind rather than panic. These disturbances, while potentially unsettling, serve to awaken you to new possibilities and clearer perception. The thunder may herald the beginning of a period of increased activity and movement in your life. Use this energizing force to break through stagnation, but remain centered amid the turbulence.`,
  [52]: `Keeping Still (Gen) represents stillness, meditation, and the mountain. This hexagram shows mountain upon mountain, doubling the quality of immovability and quiet strength. The Judgment emphasizes keeping the back still so that you no longer perceive your body, walking through the courtyard without seeing the people - a description of deep meditation and inner stillness. This is not paralysis or stubbornness, but rather the conscious choice to pause, reflect, and cease unnecessary movement. Like a mountain that stands unmoved by winds and storms, this hexagram teaches the power of knowing when to stop. There is a time for action and a time for stillness, and wisdom lies in recognizing when striving becomes counterproductive. The mountain also represents boundaries, limits, and the ability to say "thus far and no further." Through stillness, you gain perspective that is impossible to achieve in constant motion.

In divination, Keeping Still counsels that this is a time to pause rather than push forward. You may be reaching the natural limits of a current endeavor, or you may need to stop and reflect before proceeding. This hexagram often appears when you have been overextending yourself or when restless activity is preventing clarity. It suggests meditation, contemplation, and the practice of being fully present in each moment without striving for what comes next. By keeping still, you conserve energy, gain insight, and allow situations to resolve naturally without forced intervention. This is not passive resignation but active cultivation of inner peace and clear boundaries. Know when to stop, when to say no, and when to simply be.`,
  [53]: `Development (Jian) represents gradual progress and advancement. This hexagram symbolizes a wild goose flying progressively higher, ascending the mountain in stages - from shore to cliff, from cliff to plateau, always advancing but never rushing. The Judgment speaks of the maiden being given in marriage as auspicious, suggesting proper sequence, social order, and the gradual building of lasting relationships. Development teaches that genuine achievement comes through patient, steady progress rather than sudden leaps. Like a tree growing slowly but surely, each phase of development must be completed before the next can begin. This hexagram emphasizes natural timing and organic growth, where each stage provides the foundation for what follows. Rushing leads to instability, while patient progression creates lasting results.

In divination, Development indicates that your current situation will unfold gradually and naturally, achieving success through steady advancement rather than dramatic breakthroughs. This hexagram counsels patience and trust in natural processes - understand that worthwhile achievements take time to develop properly. You may be building something that will prove lasting and significant, but it requires methodical progress through each necessary stage. This is favorable for long-term projects, relationships that deepen over time, and endeavors that benefit from careful cultivation. Do not force premature conclusions or skip necessary steps in your eagerness to arrive at results. Like the wild goose ascending, maintain your direction and keep progressing steadily upward, trusting that each phase of development prepares you for the next.`,
  [54]: `The Marrying Maiden (Gui Mei) represents improper positioning and relationships built on weak foundations. This hexagram depicts the younger sister following the elder into marriage as a concubine - a position of subordination without proper standing. The Judgment warns that undertakings bring misfortune and nothing furthers, as this situation lacks the solid foundation necessary for lasting success. The Marrying Maiden speaks to relationships, arrangements, or endeavors entered into from desire rather than proper circumstances, where passion or impulse override wisdom and timing. While the feelings may be genuine, the positioning is incorrect, leading to disappointment and difficulty. This hexagram teaches that good intentions alone cannot overcome structural problems in how relationships or situations are configured.

In divination, The Marrying Maiden warns that current arrangements may be fundamentally flawed, regardless of how much you wish them to succeed. You may find yourself in a subordinate position that lacks proper recognition, or you may be pursuing something from an inappropriate angle. This hexagram counsels careful examination of your true position and realistic assessment of what can be achieved from where you stand. If you are entering into new commitments, ensure they are based on mutual respect and proper foundations rather than mere desire or convenience. Sometimes the answer is to accept limitations with grace, while other times it may be necessary to withdraw entirely and seek better circumstances. Distinguish between what you wish were true and what actually is.`,
  [55]: `Abundance (Feng) represents fullness, prosperity, and the zenith of success. This hexagram shows thunder and lightning coming together, symbolizing the peak moment when power and clarity unite in magnificent display. The Judgment declares abundance brings success, encouraging you to be like the sun at midday - reaching your fullest potential without worry. However, this hexagram also carries a subtle warning: just as the sun begins to descend after reaching its noon position, abundance naturally gives way to decrease. This is the nature of cycles - what reaches fullness must eventually wane. The wise ruler maintains inner depth even during times of outer prosperity, understanding that the height of success is also the moment to prepare for changes ahead. Abundance suggests the importance of using times of plenty wisely, not becoming complacent or wasteful.

In divination, Abundance indicates you are entering or currently experiencing a time of peak achievement, prosperity, and success. This is a favorable hexagram suggesting that your efforts are bearing maximum fruit and conditions are optimal. However, it also counsels awareness of impermanence - use this time of plenty to consolidate gains, share generously, and prepare for natural cycles of change. Do not mistake temporary abundance for permanent status or become arrogant in success. The greatest wisdom during abundant times is to remain humble, maintain perspective, and remember that all things transform. Enjoy the fullness of the present moment while keeping your inner reserves strong. This is an excellent time for ambitious undertakings, as conditions support bold action.`,
  [56]: `The Wanderer (Lu) represents the stranger, the traveler, and those without permanent dwelling. This hexagram shows fire on the mountain - a passing phenomenon that does not take root, illuminating briefly before moving on. The Judgment offers modest success to the wanderer who remains correct and humble in temporary circumstances. The Wanderer teaches about impermanence, adaptability, and the wisdom of traveling light through life. When you are not on your own ground, different rules apply - you must be more careful, more humble, more adaptable than when secure in familiar territory. This hexagram speaks to the dignity of maintaining inner integrity while navigating foreign circumstances, keeping your values even when external security is absent. It counsels gracious behavior, modest ambitions, and avoiding conflicts when you lack a firm base of operations.

In divination, The Wanderer suggests you are in a transitional phase, perhaps feeling like an outsider or moving through unfamiliar territory. This may be literal travel or metaphorical journey through changing life circumstances. The hexagram counsels modesty and careful behavior - this is not the time for bold assertions or major conflicts, as you lack the solid ground needed for such stances. Focus on what you can carry with you, maintain your inner values despite outer uncertainties, and accept the temporary nature of your current position. The Wanderer also suggests the wisdom of keeping things simple and unencumbered, not accumulating baggage or creating complicated entanglements. Success comes through flexibility, courtesy, and recognizing that some situations are meant to be passed through rather than permanently inhabited.`,
}

// Changing line descriptions for hexagrams 49-56
// Each hexagram has 6 lines (bottom to top: line1 through line6)
export const changingLineDescriptions_49_56: Record<HexagramDefinition['number'], string[]> = {
  [49]: [
    `Line 1: At the beginning of revolution, you must first establish firm foundations and gather support. The text warns against moving too quickly - wrapping yourself in the hide of a yellow ox suggests the need for patience and groundedness. This is not yet the time for dramatic action, but for careful preparation and building the credibility that will make transformation possible. Wait until the need for change becomes evident to all, and your position becomes unassailable. Premature revolution fails.`,
    `Line 2: When the right day arrives for revolution, advance with confidence. The time has become ripe for transformation, and you have the mandate to proceed. This line indicates that the need for change has become so obvious that resistance crumbles naturally. You may undertake the revolution now without blame, as circumstances support fundamental transformation. Trust in the rightness of the moment and act decisively with clear purpose.`,
    `Line 3: This line warns against both premature action and excessive delay. When revolution is discussed three times, people begin to recognize its necessity. Yet hasty movement still brings danger. The key is to wait until the tide of opinion has truly turned, until even cautious voices acknowledge that change has become inevitable. Move with deliberation, ensuring that transformation is undertaken with broad support and careful planning.`,
    `Line 4: Revolution undertaken at this stage brings remorse to an end. You have reached the point where fundamental change is not only justified but necessary for continued growth. When you act with sincerity and clarity of purpose, people will trust in the transformation. This line suggests that reform brings good fortune when undertaken with genuine intention and proper authority. The old order gives way naturally to the new.`,
    `Line 5: The great person brings revolution like a tiger changing its stripes - with natural authority and unmistakable clarity. At this stage, the transformation is so evidently right that it requires no divination or justification. People recognize the necessity and rightness of change without being told. This is revolution at its most authentic and powerful, undertaken by someone who embodies the new order they seek to create. Lead with conviction and clarity.`,
    `Line 6: The superior person effects change like a panther transforming its spots - with subtle grace that refines rather than destroys. After the great revolution has been accomplished, there remains the work of cultural refinement and consolidation. This line teaches that small people change their faces (merely outward conformity) while noble people transform their character. Complete the revolution by helping others genuinely adapt to new ways, not merely comply outwardly.`,
  ],
  [50]: [
    `Line 1: The cauldron with legs turned upward can spill out stagnant contents - this is actually favorable, as it clears away what has become rotten or poisonous. Sometimes you must empty out old, toxic accumulations before you can be filled with fresh nourishment. Taking a concubine who brings a son suggests that something initially seeming secondary or irregular actually brings unexpected benefit. Be willing to clear out the old to make room for the new.`,
    `Line 2: The cauldron is filled with nourishment, and while companions may be envious, they cannot harm you. This line indicates that you possess valuable resources or knowledge that others desire. Your cup overflows with good things, and this abundance is protected. Focus on using your resources wisely rather than worrying about others' jealousy. Your genuine substance cannot be stolen or diminished by those who merely covet what you have.`,
    `Line 3: The handles of the cauldron are broken, making it difficult to serve the nourishment within. You possess valuable gifts or resources, but something prevents their proper distribution or use. This brings temporary obstruction and frustration. Like a vessel that cannot be lifted despite being full of food, your efforts are stymied by circumstances. The remedy comes through patience - eventually, conditions will change, the obstruction will clear, and your offerings will find their proper recipients.`,
    `Line 4: The cauldron has broken legs, spilling the prince's meal and staining his person. This line warns of failure in important responsibilities due to insufficient strength or preparation. When you cannot sustain the weight of what you have been entrusted with, humiliation follows. This teaches the importance of ensuring you have adequate capacity before accepting weighty responsibilities. Know your limitations and strengthen your foundations before attempting to carry what requires great stability.`,
    `Line 5: The cauldron has yellow handles and golden carrying rings - the perfect balance of strength and beauty, substance and form. This line represents ideal conditions for nourishment and transformation. Your vessel is both sturdy and elegant, capable of great service while remaining dignified. This is highly favorable for teaching, leading, and any role where you transform resources into benefit for others. Perseverance in this excellent position brings continued good fortune.`,
    `Line 6: The cauldron has rings of jade - the supreme refinement of form and function. This line represents the highest achievement of The Cauldron, where the vessel itself becomes precious beyond its utility. You have reached a position where your mere presence provides value, where your character has been refined to the point of becoming exemplary. Everything furthers. This is a time of great good fortune, where your cultivation benefits all who come near.`,
  ],
  [51]: [
    `Line 1: The shock comes with terror and dread, followed by joyful laughter. The initial fright of sudden change gives way to relieved laughter when you realize no real harm has been done. This line teaches that your fear of shocking events is often worse than the events themselves. Those who can maintain composure through the first shock, who do not panic when thunder roars, will find that what seemed terrifying becomes manageable. Good fortune comes through measured response to crisis.`,
    `Line 2: The shock comes bringing danger and loss of possessions. You must retreat to the high hills, but do not go searching for what has been lost - it will return on its own after seven days. This line counsels acceptance of temporary loss during times of upheaval. Chasing after what shock has scattered only brings more difficulty. Instead, withdraw to safety, maintain your equilibrium, and trust that what truly belongs to you will naturally return when conditions stabilize.`,
    `Line 3: Shock leaves you bewildered and disoriented, but this very disorientation prevents you from making rash moves that would bring misfortune. Sometimes being too stunned to act is better than acting in panic. This line suggests that while the shocking event is uncomfortable, your inability to respond immediately actually protects you from worse outcomes. Wait until clarity returns before taking action. The paralysis is temporary but protective.`,
    `Line 4: The shock bogs you down like sinking into mud. The arousing force has not awakened you but instead has left you stuck and unable to move forward effectively. This line indicates that shock has not served its intended purpose of awakening awareness but has instead created confusion and stagnation. The remedy requires finding firmer ground and clearer understanding before attempting to proceed. Not all shocks lead to positive transformation.`,
    `Line 5: The shock goes and comes in waves, bringing danger but no great loss if you remain centered. You are in the eye of the storm, where successive shocks roll through your sphere. The key is to maintain your equilibrium and essential responsibilities despite the turbulence around you. Do not abandon your central position or core duties because of external upheaval. Those who remain steady in their purpose, even as thunder rolls repeatedly, emerge without serious harm.`,
    `Line 6: The shock brings terror and trembling, causing you to look around in anxious confusion. This is not the time for undertakings, as clarity has been lost. However, if the shock affects your neighbors and not yourself directly, you remain free from blame. This line teaches discernment about which shocks are truly your concern. Not every disturbance requires your response. Sometimes the wise course is to remain still and let others deal with upheavals that are not essentially yours to address.`,
  ],
  [52]: [
    `Line 1: Keep still at the beginning, before momentum builds. When you stop your toes, preventing the first step, you avoid blame. This line teaches the importance of checking impulses at their inception, before they gather force and become harder to control. The easiest time to maintain stillness is before movement begins. By cultivating awareness of the first stirrings of restless energy, you gain mastery over unnecessary action.`,
    `Line 2: Keep your calves still - you cannot save the one you follow, and this brings disquiet to your heart. This line describes the frustration of wanting to help or follow someone who is moving in a problematic direction, yet knowing you must remain still and not enable their mistaken course. Sometimes love and loyalty require you to not follow, even when this refusal brings sorrow. Maintain your boundaries even when doing so feels difficult.`,
    `Line 3: Keeping the loins still, stiffening the spine - this kind of rigidity is dangerous and stifles the heart. There is a difference between wise stillness and rigid obstinacy. This line warns against the kind of forced immobility that comes from fear or stubbornness rather than wisdom. True stillness is supple and alive, not brittle and dead. When keeping still becomes a vice rather than a virtue, when it stifles natural movement and expression, danger follows.`,
    `Line 4: Keep still in your trunk, your core, your center - this brings no blame. When you maintain stillness at your center while remaining flexible at your extremities, you achieve the balanced posture this hexagram recommends. Your essential nature remains calm and unmoved, even as your surface responds adaptively to circumstances. This is the stillness of the mountain that allows weather to pass over its surface while remaining fundamentally unchanged at its core.`,
    `Line 5: Keep still in your jaws, your speech, your expression. When you control what you say and how you express yourself, order prevails and remorse disappears. This line emphasizes the power of restraint in communication. Many difficulties arise from speaking when silence would be wiser, from expressing every passing thought or feeling. The discipline of knowing when to speak and when to remain silent is a mark of cultivation and wisdom.`,
    `Line 6: Magnanimous stillness brings good fortune. At the highest level, keeping still becomes not a restriction but a source of generosity and spaciousness. This is the stillness of complete realization, where you no longer struggle with the impulse to act because you have transcended the compulsion entirely. From this noble stillness flows genuine peace and the ability to benefit others through your mere presence. This is the attainment this hexagram ultimately points toward.`,
  ],
  [53]: [
    `Line 1: The wild goose approaches the shore - this is the beginning stage of gradual advancement. A young person may face criticism or gossip, but there is no blame if progress continues patiently. This line represents the first tentative steps of development, when you are vulnerable to criticism because your position is not yet established. Do not be deterred by initial skepticism or obstacles. Every great journey begins with modest first steps.`,
    `Line 2: The wild goose advances to the cliff, to firm ground. You find food and drink in a pleasant, secure position. This represents reaching the first plateau of development, where you achieve enough stability to rest and be nourished. Eating and drinking with joy indicates that your gradual progress has brought you to a place of modest satisfaction and security. This is favorable, though the journey is not yet complete.`,
    `Line 3: The wild goose advances to the plateau, but the husband goes forth and does not return, while the wife is pregnant but does not give birth. This line warns of disruption in natural progression. Advancement has brought you to a dangerous point where ordinary development is interrupted by crisis or misfortune. Vigilance and defense against misfortune are crucial. Sometimes external threats disrupt even well-paced progress.`,
    `Line 4: The wild goose advances to the trees, finding perhaps a flat branch to rest upon. This represents reaching a position that is not entirely suitable - you have advanced to a place that doesn't quite fit your nature. However, if you remain flexible and adapt skillfully, you will find no blame. Sometimes gradual progress brings you to positions that require adjustment and accommodation rather than perfect fit. Adapt with grace.`,
    `Line 5: The wild goose advances to the summit. A wife remains childless for three years, but in the end nothing can prevent the union. This line promises that what seems blocked will eventually come to fruition. Despite delays and apparent obstacles, the natural course of development will ultimately prevail. Good fortune comes to those who maintain their direction despite temporary setbacks. What is meant to be will eventually manifest.`,
    `Line 6: The wild goose advances to the heights beyond the mountain, where its feathers can be used for sacred ceremonies. This represents the completion of gradual development, where your advancement has brought you to a position of honor and your life takes on exemplary quality. You have become a model for others, your achievements serve purposes beyond yourself. This is the ultimate success of patient, steady progression - reaching a position of genuine distinction.`,
  ],
  [54]: [
    `Line 1: The marrying maiden enters as a subordinate, like a lame person who can still walk. Undertakings bring good fortune despite the imperfect position. This line teaches that even from a disadvantaged or irregular position, you can make progress if you proceed with awareness of your limitations. Do not overreach, but work within your actual capacity. Modest goals suited to your position bring success.`,
    `Line 2: The one-eyed person can still see; the solitary person finds benefit in maintaining their integrity. This line suggests that when your position is incomplete or irregular, your strength lies in maintaining inner constancy and clarity of vision. Even though your perspective may be limited or your situation isolated, steadfast adherence to what is right brings benefit. Quality of character compensates for disadvantage of position.`,
    `Line 3: The marrying maiden goes as a servant or secondary wife, but must return to await a proper position. This line warns that accepting an inappropriate role, even if entered with good intentions, ultimately proves unsatisfactory. Sometimes you must withdraw from an inferior position and wait for better circumstances rather than settling for what diminishes you. Have the courage to reject arrangements that offer no real future.`,
    `Line 4: The marrying maiden exceeds the proper time for marriage. Late marriage is better than wrong marriage. This line teaches the wisdom of waiting rather than forcing connection from desperation or impatience. Missing the expected time is less problematic than entering into arrangements that are fundamentally unsuitable. Better to remain uncommitted than to commit to what cannot succeed. Patient waiting for right circumstances brings eventual good fortune.`,
    `Line 5: The sovereign marries off his daughter, yet her embroidered garments are not as fine as those of her attendant. The moon is nearly full. Good fortune comes through humility even in exalted position. This line teaches that outer magnificence matters less than genuine substance. Sometimes the one in the supposedly superior position is actually less blessed than those in supporting roles. True value lies not in display but in authentic connection and timing. Modesty brings honor.`,
    `Line 6: The woman holds the basket, but it contains no fruit; the man stabs the sheep, but no blood flows. Nothing furthers. This line represents complete hollowness - all form with no substance. The marriage or arrangement is empty of genuine content, all ritual with no reality. This warns that some situations are so fundamentally void that no effort can make them fruitful. Recognition of emptiness is itself a form of wisdom, allowing you to withdraw from what cannot succeed.`,
  ],
  [55]: [
    `Line 1: Meeting the lord of your destiny brings no blame, though the journey lasts ten days. This line teaches that even in times of abundance, significant achievements require sustained effort. Partnership with those of similar magnitude brings mutual benefit. Go forward confidently when you encounter those whose vision and capacity match your own. Great connections forged during abundant times have lasting value.`,
    `Line 2: Abundance is so great that you can see the Pole Star at midday - the glory is almost blinding. Approaching with sincerity earns trust rather than suspicion. This line warns that excessive success can create wariness in others. When your brightness becomes overwhelming, people may doubt your intentions. The remedy is genuine sincerity and sharing your abundance rather than using it to dominate. Authentic humility during times of great success preserves harmonious relationships.`,
    `Line 3: Abundance creates such brilliance that you can see small stars at midday, but in attempting to act, you break your right arm. This line warns that excessive fullness can lead to overconfidence and injury. When abundance is so great that even small things seem magnified, you lose proper sense of proportion. Attempting great deeds from this distorted perspective brings harm. No blame attaches if you recognize this danger and adjust your actions accordingly.`,
    `Line 4: Abundance obscured - as though bushes block the sun at noon, you encounter your equal in the darkness. This line describes finding genuine partnership during times that seem less than optimal. Though full abundance is hidden or obscured, sincere connection with a worthy partner brings good fortune. Sometimes the most valuable relationships form not at the height of glory but in more modest circumstances where pretense is unnecessary.`,
    `Line 5: Lines of development lead to blessing and fame coming to you. This represents abundance that is both deserved and well-used. Your success attracts capable people and creates opportunities for further growth. This is abundance at its best - not static accumulation but dynamic flourishing that benefits all involved. Good fortune and praise are natural results of genuine accomplishment shared generously.`,
    `Line 6: Abundance becomes so extreme that your house is vast but empty, you screen your home so thoroughly that no one can be seen for years. Peering through the gate, you find stillness and emptiness. This line warns of the ultimate danger of abundance - isolation through excess. When success leads you to wall yourself off from ordinary human contact, when your magnificence becomes a barrier rather than a blessing, misfortune follows. Abundance taken to this extreme becomes a form of impoverishment.`,
  ],
  [56]: [
    `Line 1: The wanderer occupies himself with trivial matters and pettiness - this invites the misfortune he encounters. When you are in a vulnerable, transient position, small-mindedness or engagement in petty conflicts brings disaster. As a stranger without established position, you cannot afford the luxury of minor disputes or frivolous concerns. This line teaches that wanderers must maintain dignity and focus on what truly matters, avoiding the temptation to engage in petty affairs.`,
    `Line 2: The wanderer arrives at an inn and keeps his possessions close; he gains the steadfast loyalty of a young servant. When you conduct yourself with appropriate modesty and care during transition, you find assistance and temporary security. This line indicates that right conduct as a stranger brings modest support. By being neither presumptuous nor overly fearful, by protecting what is yours without arrogance, you attract help during your journey. This is as much stability as a wanderer can expect.`,
    `Line 3: The wanderer burns down his inn and loses the loyalty of his servant. Despite being correct, this brings danger. This line warns that even when you are technically in the right, if you act with arrogance or insensitivity to your vulnerable position, you destroy your temporary shelter and support. Wanderers cannot afford to stand on principle in the same way those with established positions can. Know when being "right" is less important than being wise.`,
    `Line 4: The wanderer finds a resting place and recovers his possessions, but his heart is not glad. This represents achieving temporary security and material stability during your journey, yet feeling something essential is missing. This line acknowledges that external success during transition does not necessarily bring inner peace. The wanderer's heart remains uneasy because true belonging has not been found. This is neither good fortune nor misfortune, but the authentic complexity of the wandering state.`,
    `Line 5: The wanderer shoots a pheasant with a single arrow, losing the arrow but gaining praise and office. This line indicates that during your transitional journey, you have an opportunity to demonstrate your worth through skillful action. Though you may lose something in the process (the arrow), your achievement brings recognition and potentially a more stable position. This represents the possibility of transition from wandering to belonging through merit.`,
    `Line 6: A bird's nest burns - the wanderer first laughs, then must lament and weep. Through carelessness, the ox is lost. This line represents the ultimate misfortune of the wanderer: losing not just temporary shelter but even the basic means of survival through inattention or false security. The laughter turning to tears shows how quickly circumstances can reverse when you lack firm ground. This is a serious warning about maintaining vigilance and care, especially regarding fundamental necessities, throughout your entire journey.`,
  ],
}
