// Runtime accessor for the offline-classified seed-difficulty buckets.
//
// `seedsByDifficulty.json` is generated by
// `yarn classify-seed-difficulty` (scripts/classify-seed-difficulty.ts).
// Re-run it after editing seed lists in seeds/*.ts.
//
// This module exposes a single `getSeedsForDifficulty(categoryId,
// difficulty)` helper that returns the matching bucket. Falls back to
// the next-most-permissive bucket (and ultimately the full category
// pool) when the requested bucket is empty for a given category — some
// categories don't have any "hard" seeds, etc.

import { CATEGORIZED_SEEDS } from './seeds'

import classifiedRaw from './seedsByDifficulty.json'

type Difficulty = 'easy' | 'medium' | 'hard'

const CLASSIFIED = classifiedRaw as Record<
  string,
  { easy: string[]; medium: string[]; hard: string[] }
>

// Fallback chain by requested difficulty: if the bucket is empty for
// this category, try the next one toward "broaden" (easy ← medium →
// hard ← medium → easy). Last resort: the full category pool.
const FALLBACK_ORDER: Record<Difficulty, Difficulty[]> = {
  easy: ['easy', 'medium', 'hard'],
  medium: ['medium', 'easy', 'hard'],
  hard: ['hard', 'medium', 'easy'],
}

export function getSeedsForDifficulty(
  categoryId: number,
  difficulty: Difficulty
): string[] {
  const buckets = CLASSIFIED[String(categoryId)]
  if (!buckets) {
    // Category not in classified file — degrade to the unfiltered pool.
    return CATEGORIZED_SEEDS[categoryId] ?? []
  }

  for (const tier of FALLBACK_ORDER[difficulty]) {
    if (buckets[tier].length > 0) return buckets[tier]
  }
  return CATEGORIZED_SEEDS[categoryId] ?? []
}
