import { CardValue, PlayingCard } from '@/app/daily-card-game/domain/types'

const cardValueBaseChips: Record<CardValue, number> = {
  2: 2,
  3: 3,
  4: 4,
  5: 5,
  6: 6,
  7: 7,
  8: 8,
  9: 9,
  10: 10,
  J: 10,
  Q: 10,
  K: 10,
  A: 11,
}

const getDefaultCard = (
  value: CardValue,
  suit: 'hearts' | 'diamonds' | 'clubs' | 'spades'
): PlayingCard => {
  return {
    value: value,
    id: `${value}${suit}`,
    baseChips: cardValueBaseChips[value],
    suit: suit,
    isHolographic: false,
    isFoil: false,
    faceUp: true,
  }
}

export const pokerDeck: PlayingCard[] = [
  getDefaultCard('2', 'hearts'),
  getDefaultCard('2', 'diamonds'),
  getDefaultCard('2', 'clubs'),
  getDefaultCard('2', 'spades'),
  getDefaultCard('3', 'hearts'),
  getDefaultCard('3', 'diamonds'),
  getDefaultCard('3', 'clubs'),
  getDefaultCard('3', 'spades'),
  getDefaultCard('4', 'hearts'),
  getDefaultCard('4', 'diamonds'),
  getDefaultCard('4', 'clubs'),
  getDefaultCard('4', 'spades'),
  getDefaultCard('5', 'hearts'),
  getDefaultCard('5', 'diamonds'),
  getDefaultCard('5', 'clubs'),
  getDefaultCard('5', 'spades'),
  getDefaultCard('6', 'hearts'),
  getDefaultCard('6', 'diamonds'),
  getDefaultCard('6', 'clubs'),
  getDefaultCard('6', 'spades'),
  getDefaultCard('7', 'hearts'),
  getDefaultCard('7', 'diamonds'),
  getDefaultCard('7', 'clubs'),
  getDefaultCard('7', 'spades'),
  getDefaultCard('8', 'hearts'),
  getDefaultCard('8', 'diamonds'),
  getDefaultCard('8', 'clubs'),
  getDefaultCard('8', 'spades'),
  getDefaultCard('9', 'hearts'),
  getDefaultCard('9', 'diamonds'),
  getDefaultCard('9', 'clubs'),
  getDefaultCard('9', 'spades'),
  getDefaultCard('10', 'hearts'),
  getDefaultCard('10', 'diamonds'),
  getDefaultCard('10', 'clubs'),
  getDefaultCard('10', 'spades'),
  getDefaultCard('J', 'hearts'),
  getDefaultCard('J', 'diamonds'),
  getDefaultCard('J', 'clubs'),
  getDefaultCard('J', 'spades'),
  getDefaultCard('Q', 'hearts'),
  getDefaultCard('Q', 'diamonds'),
  getDefaultCard('Q', 'clubs'),
  getDefaultCard('Q', 'spades'),
  getDefaultCard('K', 'hearts'),
  getDefaultCard('K', 'diamonds'),
  getDefaultCard('K', 'clubs'),
  getDefaultCard('K', 'spades'),
  getDefaultCard('A', 'hearts'),
  getDefaultCard('A', 'diamonds'),
  getDefaultCard('A', 'clubs'),
  getDefaultCard('A', 'spades'),
]
