import { createOpenAI } from '@ai-sdk/openai';
import { generateObject } from 'ai';
import { NextResponse } from 'next/server';
import { z } from 'zod';

const RandomCharacterSchema = z.object({
  name: z.string().describe('The name of the character'),
  description: z.string().describe('A detailed description of the character'),
});

// Large list of character categories to choose from
const CHARACTER_CATEGORIES = [
  'medieval fantasy warrior',
  'space marine',
  'cyberpunk hacker',
  'ancient mythology god',
  'steampunk inventor',
  'post-apocalyptic survivor',
  'superhero',
  'supervillain',
  'anime protagonist',
  'horror monster',
  'pirate captain',
  'ninja assassin',
  'wild west gunslinger',
  'mad scientist',
  'robot/android',
  'alien species',
  'vampire',
  'werewolf',
  'wizard/sorcerer',
  'dragon',
  'demon',
  'angel',
  'time traveler',
  'dimension hopper',
  'elemental being',
  'undead creature',
  'shapeshifter',
  'psychic mutant',
  'cosmic entity',
  'nature spirit',
  'ancient warrior',
  'modern soldier',
  'detective',
  'spy/secret agent',
  'bounty hunter',
  'gladiator',
  'samurai',
  'viking berserker',
  'tribal shaman',
  'street fighter',
  'martial artist',
  'professional wrestler',
  'boxer',
  'assassin',
  'thief/rogue',
  'bard/musician',
  'scholar/sage',
  'alchemist',
  'necromancer',
  'paladin',
  'ranger',
  'barbarian',
  'monk',
  'warlock',
  'witch',
  'fairy tale character',
  'mythical beast',
  'legendary hero',
  'fallen hero',
  'anti-hero',
  'trickster god',
  'war deity',
  'love deity',
  'death deity',
  'nature deity',
  'sea creature',
  'sky dweller',
  'underground dweller',
  'forest guardian',
  'mountain guardian',
  'desert nomad',
  'arctic survivor',
  'jungle warrior',
  'urban vigilante',
  'corporate executive',
  'street gang leader',
  'cult leader',
  'religious figure',
  'philosopher',
  'artist',
  'entertainer',
  'athlete',
  'pilot',
  'captain',
  'commander',
  'general',
  'emperor/empress',
  'king/queen',
  'prince/princess',
  'noble',
  'peasant hero',
  'merchant',
  'craftsman',
  'blacksmith',
  'chef',
  'healer',
  'teacher',
  'student',
  'child prodigy',
  'elderly sage',
  'spirit medium',
  'fortune teller',
  'circus performer',
  'gladiator',
  'knight',
  'squire',
  'page',
  'herald',
  'messenger',
  'scout',
  'tracker',
  'hunter',
  'gatherer',
  'farmer',
  'fisherman',
  'sailor',
  'explorer',
  'adventurer',
  'treasure hunter',
  'archaeologist',
  'historian',
  'librarian',
  'keeper of secrets',
  'guardian of ancient knowledge',
  'protector of the innocent',
  'defender of justice',
  'champion of the oppressed',
  'voice of the voiceless',
  'bringer of peace',
  'harbinger of war',
  'messenger of doom',
  'herald of hope',
  'keeper of balance',
  'disruption agent',
  'chaos bringer',
  'order enforcer',
  'law keeper',
  'rule breaker',
  'tradition keeper',
  'innovation bringer',
  'change agent',
  'status quo defender',
  'rebel leader',
  'revolutionary',
  'counter-revolutionary',
  'loyalist',
  'traitor',
  'double agent',
  'triple agent',
  'sleeper agent',
  'deep cover operative',
  'black ops specialist',
  'special forces',
  'elite unit member',
  'lone wolf',
  'pack leader',
  'team player',
  'solo operative',
  'partnership specialist',
  'group coordinator',
  'squad leader',
  'platoon commander',
  'company captain',
  'battalion major',
  'regiment colonel',
  'division general',
  'army marshal',
  'fleet admiral',
  'air force commander',
  'space force captain',
  'galactic admiral',
  'universal guardian',
  'multiverse protector',
  'reality manipulator',
  'dimension walker',
  'time guardian',
  'space wanderer',
  'cosmic explorer',
  'stellar navigator',
  'planetary defender',
  'solar system protector',
  'galaxy guardian',
  'universe keeper',
  'multiverse maintainer',
  'reality anchor',
  'existence guardian',
  'void walker',
  'abyss dweller',
  'light bringer',
  'shadow master',
  'dream weaver',
  'nightmare lord',
  'memory keeper',
  'forgotten one',
  'ancient one',
  'eternal being',
  'immortal warrior',
  'mortal champion',
  'divine avatar',
  'demonic vessel',
  'angelic messenger',
  'neutral arbiter',
  'balance keeper',
  'chaos agent',
  'order guardian',
  'natural force',
  'artificial creation',
  'hybrid being',
  'pure energy',
  'living weapon',
  'sentient tool',
  'conscious machine',
  'digital entity',
  'virtual being',
  'augmented human',
  'enhanced animal',
  'evolved plant',
  'living mineral',
  'elemental fusion',
  'spiritual essence',
  'physical manifestation',
  'mental projection',
  'emotional embodiment',
  'conceptual being',
  'abstract entity',
  'concrete form',
  'fluid shape',
  'solid structure',
  'gaseous form',
  'plasma entity',
  'quantum being',
  'subatomic creature',
  'molecular assembler',
  'atomic manipulator',
  'nuclear controller',
  'fusion master',
  'fission specialist',
  'energy converter',
  'matter transformer',
  'space bender',
  'time twister',
  'reality shaper',
  'dimension crafter',
  'universe builder',
  'multiverse architect',
  'existence designer',
  'void sculptor',
  'creation artist',
  'destruction master',
  'preservation keeper',
  'change catalyst',
  'stability anchor',
  'growth facilitator',
  'decay accelerator',
  'life giver',
  'death dealer',
  'rebirth herald',
  'transformation guide',
  'evolution director',
  'adaptation specialist',
  'survival expert',
  'extinction agent',
  'renaissance bringer',
  'dark age herald',
  'golden age guardian',
  'silver age keeper',
  'bronze age warrior',
  'iron age survivor',
  'stone age primitive',
  'digital age native',
  'space age pioneer',
  'quantum age explorer',
  'infinite age eternal',
];

export async function POST(request: Request) {
  try {
    const openaiClient = createOpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });

    // Get excluded characters from request body to avoid repeats
    const body = await request.json();
    const excludedCharacters = body?.excludedCharacters || [];

    // Choose a random category
    const randomCategory =
      CHARACTER_CATEGORIES[Math.floor(Math.random() * CHARACTER_CATEGORIES.length)];

    // Generate character based on the category
    const result = await generateObject({
      model: openaiClient('gpt-4o-mini'),
      schema: RandomCharacterSchema,
      prompt: `Please tell me the name of a well-known character. The character should be a ${randomCategory}.

${excludedCharacters.length > 0 ? `Do not create any of these characters that have already been generated: ${excludedCharacters.join(', ')}` : ''}`,
      temperature: 0.9, // High temperature for creative variety
      maxTokens: 300,
    });

    return NextResponse.json({
      name: result.object.name,
      description: result.object.description,
      category: randomCategory,
    });
  } catch (error) {
    console.error('Error generating random character:', error);
    return NextResponse.json({ error: 'Failed to generate random character' }, { status: 500 });
  }
}
